# Geospatial {#sec-diag-geo .unnumbered}

::: {.callout-note collapse="true"}
## todo

-   [Rao's score](https://r-spatial.github.io/spdep/reference/SD.RStests.html) (aka Lagrange multiplier test) for Durbin model
-   [Rao's score](https://r-spatial.github.io/spdep/reference/lm.RStests.html) for `lm`
:::

## Misc {#sec-diag-geo-misc .unnumbered}

-   Also see [Geospatial, Spatial Weights](geospatial-spatial-weights.qmd#sec-geo-swgt){style="color: green"}
-   Packages
    -   [{]{style="color: #990000"}[waywiser](https://docs.ropensci.org/waywiser/){style="color: #990000"}[}]{style="color: #990000"} - Measures the performance of models fit to 2D spatial data by implementing a number of well-established assessment methods in a consistent, ergonomic toolbox
        -   Features include new yardstick metrics for measuring agreement and spatial autocorrelation, functions to assess model predictions across multiple scales, and methods to calculate the area of applicability of a model.
    -   [{]{style="color: #990000"}[geospt](https://cran.r-project.org/web/packages/geospt/index.html){style="color: #990000"}[}]{style="color: #990000"} - Estimation of the variogram through trimmed mean, radial basis functions (optimization, prediction and cross-validation), summary statistics from cross-validation, pocket plot, and design of optimal sampling networks through sequential and simultaneous points methods.
    -   [{]{style="color: #990000"}[geosptdb](https://cran.r-project.org/web/packages/geosptdb/index.html){style="color: #990000"}[}]{style="color: #990000"} - Spatio-Temporal Radial Basis Functions with Distance-Based Methods (Optimization, Prediction and Cross Validation)

## Spatial Autocorrelation {#sec-diag-geo-sauto .unnumbered}

-   [Misc]{.underline}

    -   Local metrics can suffer from multiple testing issues when the number of group units is large
    -   Packages
        -   [{]{style="color: #990000"}[spdep::EBImoran.mc](https://r-spatial.github.io/spdep/reference/EBImoran.mc.html){style="color: #990000"}[}]{style="color: #990000"} ([Vignette](https://r-spatial.github.io/spdep/articles/sids.html#probability-mapping)) uses empirical bayes to shrink locations counts/rates that have high variance / small populations towards a global average rate. Then tests (via permutation) for spatial autocorrelation.
            -   Useful for count data with outliers or overdispersion

-   [Moran's I]{.underline}

    $$
    I = \frac{N}{W} \frac{\sum_i \sum_j w_{ij}(x_i - \bar{x})(x_j - \bar{x})}{\sum_i (x_i - \bar{x})^2}
    $$

    -   A measure of global spatial autocorrelation or overall clustering of the data
        -   If there is no global autocorrelation or no clustering, there can still be clusters at a local level (See Local Moran's I)
    -   Assume homegeneity (i.e. only one statistic is needed to summarize the whole study area)
    -   $N$ is the number of spatial units (e.g. counties)
    -   $w_{ij}$ is an element of the spatial weights matrix
    -   $W$ is the sum of all $w_{ij}$
    -   Values significantly *below* the expected value are *negatively* correlated
    -   Values significantly *above* the exected value are *positively* correlated
    -   Range: $w_{\text{min}}\frac{N}{W} \lt I \lt w_{\text{max}}\frac{N}{W}$
        -   For a row normalized weight matrix, $\frac{N}{W} = 1$ (Wiki)
            -   In [{spdep}]{style="color: #990000"}, this would be [style = "W"]{.arg-text}
            -   I don't get this. W = 1, but why would N also equal 1? Not sure if this right.

-   [Local Moran's I]{.underline}\
    $$
    \begin{align}
    &I_i = \frac{x_i - \bar x}{m_2} \sum_{j=1}^N w_{ij} (x_j - \bar x) \\
    &\text{where} \;\; m_2 = \frac{\sum_{i=1}^N (x_i - \bar x)^2}{N}
    \end{align}
    $$

    -   Moran's I is just the average of all $I_i s$, $I = \sum_{i=1}^N I_i /N$

-   [Geary's C]{.underline}\
    $$
    C = \frac{(N-1) \sum_i \sum_j w_{ij}(x_i-x_j)^2}{2W \sum_i (x_i - \bar x)^2}
    $$

    -   A measure of global spatial autocorrelation or overall clustering of the data
        -   More sensitive to local spatial autocorrelation than Moran's I so it can pick-up on spatial autocorrelation that Moran's I might have missed.
    -   $N$ is the number of analysis units on the map
    -   $w_{ij}$ is an element of the spatial weights matrix
    -   $W$ is the sum of all $w_{ij}$

-   [Local Geary's C]{.underline}\
    $$
    \begin{align}
    &C_i = \frac{1}{m_2} \sum_j w_{ij}(x_i - xj)^2\\
    &\text{where} \;\; m_2 = \frac{\sum_i (x_i - \bar x)^2}{N-1}
    \end{align}
    $$

    -   Geary's C is $C=\sum_i C_i/2W$
