<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Science Notebook - 54&nbsp; Econometrics, Mixed Effects, Frequentist</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../qmd/eda-geospatial.html" rel="next">
<link href="../qmd/econometrics-mixed-effects-bayes.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../qmd/econometrics-fixed-effects.html">Econometrics</a></li><li class="breadcrumb-item"><a href="../qmd/econometrics-mixed-effects-frequentist.html"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Econometrics, Mixed Effects, Frequentist</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Data Science Notebook</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://ericbook.netlify.app/" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-house-fill"></i></a>
    <a href="https://github.com/ercbk/Data-Science-Notebook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Algorithms</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/algorithms-learn-to-rank.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learn-to-Rank</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/algorithms-marketing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Marketing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/algorithms-ml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">ML</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/algorithms-product.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Algorithms, Product</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/algorithms-recommendation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Algorithms, Recommendation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/anomaly-detection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Anomaly Detection</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Apache</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/apache-arrow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Apache, Arrow</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/apache-spark.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Spark</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/apis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">APIs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/aws.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">AWS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/base-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Base R</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Bayes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/bayes-priors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Bayes, priors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/bayes-reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bayes, Reporting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/bayes-troubleshooting-hmc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Bayes, Troubleshooting HMC</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/bayes-workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Bayes, Workflow</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/big-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Big Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/business-plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Business Plots</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/causal-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Causal Inference</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Classification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/cli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">CLI</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/cloud-services.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Cloud Services</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Clustering</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/clustering-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Clustering, Time Series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/clustering-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Clustering</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Code</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/code-debug.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Debugging</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/code-optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Code, Optimization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/code-snippets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Snippets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/code-style-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Code, Style Guide</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/code-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Code, Testing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/confidence-and-prediction-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Confidence &amp; Prediction Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/correlation-association-and-distance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Correlation, Association, and Distance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/cross-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Cross-Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/data.table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">data.table</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Databases</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-dbt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">DB, dbt</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-duckdb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DuckDB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-engineering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Engineering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-feature-stores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">DB, Feature Stores</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-lakes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lakes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-other.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Other</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-postgres.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">DB, postgres</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-relational.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">DB, Relational</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-warehouses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Warehouses</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/decison-intelligence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Decison Intelligence</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
 <span class="menu-text">Diagnostics</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Diagnostics, Bayes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Diagnostics, Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Diagnostics, Clustering</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-cv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Diagnostics, CV</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-dl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Diagnostics, DL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-forecasting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Diagnostics, Forecasting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Diagnostics, GLM</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-model-agnostic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Diagnostics, Model Agnostic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-nlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Diagnostics, NLP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-probabilistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Diagnostics, Probabilistic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Diagnostics, Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false">
 <span class="menu-text">Deep Learning</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-audio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">DL, Audio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">DL, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-graph.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">DL, Graph</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-image.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">DL, Image</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-tabular.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">DL, Tabular</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-training.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">DL, Training</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false">
 <span class="menu-text">Docker</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/docker-aws.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Docker, AWS</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/docker-fundamentals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Docker, Fundamentals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/docker-misc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Docker, Misc</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="true">
 <span class="menu-text">Econometrics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/econometrics-fixed-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Econometrics, Fixed Effects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/econometrics-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Econometrics, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/econometrics-mixed-effects-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Econometrics, Mixed Effects, Bayes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/econometrics-mixed-effects-frequentist.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Econometrics, Mixed Effects, Frequentist</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="false">
 <span class="menu-text">EDA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/eda-geospatial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">EDA, Geospatial</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/eda-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">EDA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/eda-multilevel-longitudinal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">EDA, Multilevel, Longitudinal</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/eda-text.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">EDA, Text</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/eda-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">EDA, Time Series</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="false">
 <span class="menu-text">Experiments</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-a_b-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Experiments, A/B Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Experiments, Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Experiments, Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Experiments, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-rct.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Experiments, RCT</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-stepped-wedge-cluster-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Experiments, Stepped Wedge Cluster Design</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/extreme-value-theory-(evt).html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Extreme Value Theory (EVT)</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="false">
 <span class="menu-text">Feature Engineering</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-engineering-embeddings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Feature Engineering, Embeddings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-engineering-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Feature Engineering, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-engineering-geospatial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Feature Engineering, Geospatial</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-engineering-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Feature Engineering, Time Series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-engineering-tokenization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Feature Engineering, Tokenization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-reduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Feature Reduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Feature Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" aria-expanded="false">
 <span class="menu-text">Forecasting</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-decomposition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">74</span>&nbsp; <span class="chapter-title">Forecasting, Decomposition</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-dl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deep Learning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-ensembling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">75</span>&nbsp; <span class="chapter-title">Forecasting, Ensembling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-functional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">76</span>&nbsp; <span class="chapter-title">Forecasting, Functional</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-hierarchical_grouped.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hierarchical/Grouped</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-ml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">77</span>&nbsp; <span class="chapter-title">Forecasting, ML</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-multivariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multivariate</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">78</span>&nbsp; <span class="chapter-title">Forecasting, Nonlinear</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-statistical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">79</span>&nbsp; <span class="chapter-title">Forecasting, Statistical</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/generalized-additive-models-(gam).html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">80</span>&nbsp; <span class="chapter-title">Generalized Additive Models (GAM)</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" aria-expanded="false">
 <span class="menu-text">Geospatial</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/geospatial-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">81</span>&nbsp; <span class="chapter-title">Geospatial, Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/geospatial-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">82</span>&nbsp; <span class="chapter-title">Geospatial, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/geospatial-image-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">Geospatial, Image Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/geospatial-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">84</span>&nbsp; <span class="chapter-title">Geospatial, Processing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" aria-expanded="false">
 <span class="menu-text">Git</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/git-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">85</span>&nbsp; <span class="chapter-title">Git, general</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/git-github-actions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">86</span>&nbsp; <span class="chapter-title">Git, Github Actions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/glossary-ds-terms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">87</span>&nbsp; <span class="chapter-title">Glossary: DS terms</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/gnu-make.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">88</span>&nbsp; <span class="chapter-title">GNU Make</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" aria-expanded="false">
 <span class="menu-text">Google</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/google-analytics-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">89</span>&nbsp; <span class="chapter-title">Google, Analytics, Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/google-analytics-reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">90</span>&nbsp; <span class="chapter-title">Google, Analytics, Reports</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/google-bigquery.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">BigQuery</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/gtable-package.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">91</span>&nbsp; <span class="chapter-title">gtable package</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/h2o-automl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">92</span>&nbsp; <span class="chapter-title">h2o automl</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/html-css.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">93</span>&nbsp; <span class="chapter-title">html, css</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/information-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">94</span>&nbsp; <span class="chapter-title">Information Theory</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/inkscape.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">95</span>&nbsp; <span class="chapter-title">Inkscape</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" aria-expanded="false">
 <span class="menu-text">Job</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/job-management-leadership.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">96</span>&nbsp; <span class="chapter-title">Job, Management / Leadership</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/job-on-the-job.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">97</span>&nbsp; <span class="chapter-title">Job, On the job</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/job-organizational-and-team-development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">98</span>&nbsp; <span class="chapter-title">Job, Organizational and Team Development</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/job-reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">99</span>&nbsp; <span class="chapter-title">Reports</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/job-search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">100</span>&nbsp; <span class="chapter-title">Job, Search</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/js.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">101</span>&nbsp; <span class="chapter-title">JS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/json.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">JSON</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/kubernetes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">102</span>&nbsp; <span class="chapter-title">Kubernetes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/latex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LaTeX</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/loss-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">103</span>&nbsp; <span class="chapter-title">Loss Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" aria-expanded="false">
 <span class="menu-text">Mathematics</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mathematics-linear-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">104</span>&nbsp; <span class="chapter-title">Linear Algebra</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mathematics-glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mathematics-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">105</span>&nbsp; <span class="chapter-title">Mathematics, Notation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mathematics-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">106</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mathematics-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">107</span>&nbsp; <span class="chapter-title">Statistical Concepts</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/misc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Misc</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/missingness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">108</span>&nbsp; <span class="chapter-title">Missingness</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mlops.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">109</span>&nbsp; <span class="chapter-title">MLOps</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" aria-expanded="false">
 <span class="menu-text">Model Building</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-brms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">brms</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-ensembling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ensembling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-modeltime.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">modeltime</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-rstanarm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">rstanarm</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-sklearn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">sklearn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-tidymodels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">tidymodels</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/network-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Network Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" aria-expanded="false">
 <span class="menu-text">NLP</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-21" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-fine-tuning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">110</span>&nbsp; <span class="chapter-title">NLP, Fine Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">111</span>&nbsp; <span class="chapter-title">NLP, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-llms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">112</span>&nbsp; <span class="chapter-title">NLP, LLMs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-prompt-engineering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prompt Engineering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-sentiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">113</span>&nbsp; <span class="chapter-title">NLP, Sentiment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-summarization-extraction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summarization and Extraction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-topic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">114</span>&nbsp; <span class="chapter-title">NLP, Topic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-transformers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">115</span>&nbsp; <span class="chapter-title">NLP, Transformers</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/optimization-equation-systems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">116</span>&nbsp; <span class="chapter-title">Optimization, Equation Systems</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/outliers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Outliers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/package-development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">117</span>&nbsp; <span class="chapter-title">Package Development</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-22" aria-expanded="false">
 <span class="menu-text">Post-Hoc Analysis</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-22" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-22" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/post-hoc-analysis-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">118</span>&nbsp; <span class="chapter-title">Post-Hoc Analysis, ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/post-hoc-analysis-emmeans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">119</span>&nbsp; <span class="chapter-title">Post-Hoc Analysis, emmeans</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/post-hoc-analysis-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">120</span>&nbsp; <span class="chapter-title">Post-Hoc Analysis, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/post-hoc-analysis-mixed-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">121</span>&nbsp; <span class="chapter-title">Post-Hoc Analysis, Mixed Effects</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/privacy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">122</span>&nbsp; <span class="chapter-title">Privacy</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-23" aria-expanded="false">
 <span class="menu-text">Production</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-23" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-23" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-data-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">123</span>&nbsp; <span class="chapter-title">Production, Data Validation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-deployment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deployment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">124</span>&nbsp; <span class="chapter-title">Production, Development</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-ml-monitoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">125</span>&nbsp; <span class="chapter-title">Production, ML Monitoring</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">126</span>&nbsp; <span class="chapter-title">Production, Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">127</span>&nbsp; <span class="chapter-title">Production, Tools</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-24" aria-expanded="false">
 <span class="menu-text">Projects</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-24" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-24" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/project-development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">128</span>&nbsp; <span class="chapter-title">Project, Development</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/project-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">129</span>&nbsp; <span class="chapter-title">Project, Management</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/project-planning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">130</span>&nbsp; <span class="chapter-title">Project, Planning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-25" aria-expanded="false">
 <span class="menu-text">Python</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-25" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-25" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-classes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">131</span>&nbsp; <span class="chapter-title">Python, Classes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">General</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-jupyter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">132</span>&nbsp; <span class="chapter-title">Python, Jupyter</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-misc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">133</span>&nbsp; <span class="chapter-title">Python, Misc</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-numpy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">134</span>&nbsp; <span class="chapter-title">Python, Numpy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-pandas-recipes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">135</span>&nbsp; <span class="chapter-title">Python, Pandas, Recipes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-pandas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pandas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-reticulate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">136</span>&nbsp; <span class="chapter-title">Python, reticulate</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/quarto-rmarkdown.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-26" aria-expanded="false">
 <span class="menu-text">Regression</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-26" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-26" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-discrete.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">137</span>&nbsp; <span class="chapter-title">Regression, Discrete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-gaussian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">138</span>&nbsp; <span class="chapter-title">Regression, Gaussian</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">139</span>&nbsp; <span class="chapter-title">Regression, Interactions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">140</span>&nbsp; <span class="chapter-title">Regression, Logistic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-multivariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">141</span>&nbsp; <span class="chapter-title">Regression, Multivariate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">142</span>&nbsp; <span class="chapter-title">Regression, Nonlinear</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-ordinal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">143</span>&nbsp; <span class="chapter-title">Regression, Ordinal</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-other.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">144</span>&nbsp; <span class="chapter-title">Regression, Other</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">145</span>&nbsp; <span class="chapter-title">Regression, Quantile</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-regularized.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">146</span>&nbsp; <span class="chapter-title">Regression, Regularized</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">147</span>&nbsp; <span class="chapter-title">Regression, Survival</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/renv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">148</span>&nbsp; <span class="chapter-title">Renv</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/scraping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Scraping</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-27" aria-expanded="false">
 <span class="menu-text">Shiny</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-27" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-27" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">149</span>&nbsp; <span class="chapter-title">Shiny, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-hosting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">150</span>&nbsp; <span class="chapter-title">Shiny, Hosting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-modules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">151</span>&nbsp; <span class="chapter-title">Shiny, Modules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-production.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">152</span>&nbsp; <span class="chapter-title">Shiny, Production</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">153</span>&nbsp; <span class="chapter-title">Shiny, Python</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-ui.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">154</span>&nbsp; <span class="chapter-title">Shiny, UI</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-ui-examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">155</span>&nbsp; <span class="chapter-title">Shiny, UI Examples</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/simulation-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">156</span>&nbsp; <span class="chapter-title">Simulation, Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/slack.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">157</span>&nbsp; <span class="chapter-title">Slack</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/spreadsheets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">158</span>&nbsp; <span class="chapter-title">Spreadsheets</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/sql.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SQL</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/stochastic-processes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">159</span>&nbsp; <span class="chapter-title">Stochastic Processes</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-28" aria-expanded="false">
 <span class="menu-text">Surveys</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-28" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-28" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/surveys-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">160</span>&nbsp; <span class="chapter-title">Surveys, Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/surveys-census-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">161</span>&nbsp; <span class="chapter-title">Surveys, Census Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/surveys-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">162</span>&nbsp; <span class="chapter-title">Surveys, Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/surveys-sampling-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">163</span>&nbsp; <span class="chapter-title">Surveys, Sampling Methods</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/teaching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">164</span>&nbsp; <span class="chapter-title">Teaching</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/tidyeval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">165</span>&nbsp; <span class="chapter-title">Tidyeval</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/tuning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">166</span>&nbsp; <span class="chapter-title">Tuning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visualization</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/vs-code.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">167</span>&nbsp; <span class="chapter-title">VS Code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/web-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">168</span>&nbsp; <span class="chapter-title">Web Design</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Econometrics, Mixed Effects, Frequentist</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>TOC</p>
<ul>
<li>Stuff
<ul>
<li>Motivation for using a Random Effects model</li>
<li>Model Choice
<ul>
<li>Pooling</li>
<li>Fixed Effects or Random Effects?</li>
</ul></li>
<li>Advantages of a mixed model (y ~ x + (x | g)) vs a linear model with an interaction (y ~ x * g)</li>
<li>Assumptions</li>
<li>Variable Assignment
<ul>
<li>Fixed Effects</li>
<li>Random Effects</li>
</ul></li>
<li>Specifications and Notation</li>
<li>Strategy</li>
<li>InterClass Coefficient (ICC)</li>
<li>Diagnostics</li>
<li>Examples</li>
</ul></li>
<li>Beyond Multiple Linear Regression
<ul>
<li>Chapter 8 (Introduction to Multilevel Models)
<ul>
<li>2-Stage Model</li>
<li>Multilevel Model</li>
<li>Simple to Complex Model Building Workflow
<ul>
<li>Unconditional Means (aka Random Intercepts)
<ul>
<li>ICC</li>
</ul></li>
<li>Random Slopes and Intercepts Model (with 1 covariate)
<ul>
<li>Pseudo-R2</li>
</ul></li>
<li>Random Slopes and Intercepts Model (with 2 covariates)
<ul>
<li>Pseudo-R2</li>
</ul></li>
<li>Random Intercepts (with 2 covariates)
<ul>
<li>AIC/BIC</li>
</ul></li>
<li>Random Slopes and Intercepts Model (with 3 covariates)
<ul>
<li>LR-Test for comparing nested models</li>
</ul></li>
<li>Final Model</li>
</ul></li>
</ul></li>
<li>Chapter 9 (2-Level Longitudinal Data)</li>
</ul></li>
</ul>
<p>Stuff</p>
<ul>
<li><p>Misc</p>
<ul>
<li>Random Effects model = Multi-level model with random intercepts = Hierarchical model</li>
<li>Packages
<ul>
<li><span style="color: #990000">{</span><a href="https://cran.r-project.org/web/packages/lme4/index.html" style="color: #990000">lme4</a><span style="color: #990000">}</span> - linear and generalized linear mixed-effects models; implemented using the ‘Eigen’ C++ library for numerical linear algebra and ‘RcppEigen’ “glue”.
<ul>
<li>Using <span style="color: #990000">{</span><a href="https://cran.r-project.org/web/packages/lmerTest/index.html" style="color: #990000">lmerTest</a><span style="color: #990000">}</span> will produce a summary of lme4 models with pvals for coefficients</li>
</ul></li>
<li><span style="color: #990000">{</span><a href="https://cran.r-project.org/web/packages/plm/index.html" style="color: #990000">plm</a><span style="color: #990000">}</span> - linear models for panel data; including within/fixed effects, random effects, between, first-difference, nested random effects</li>
<li><span style="color: #990000">{</span><a href="https://glmmtmb.github.io/glmmTMB/" style="color: #990000">glmmTMB</a><span style="color: #990000">}</span> - for fitting generalized linear mixed models (GLMMs) and extensions
<ul>
<li>Wide range of statistical distributions (Gaussian, Poisson, binomial, negative binomial, Beta …) and zero-inflation.</li>
<li>Fixed and random effects models can be specified for the conditional and zero-inflated components of the model, as well as fixed effects for the dispersion parameter.</li>
</ul></li>
<li><span style="color: #990000">{</span><a href="https://cran.r-project.org/web/packages/spaMM/index.html" style="color: #990000">spaMM</a><span style="color: #990000">}</span> - Inference based on models with or without spatially-correlated random effects, multivariate responses, or non-Gaussian random effects (e.g., Beta).</li>
</ul></li>
<li>Mixed Effects and repeated measures (aka longitudinal)
<ul>
<li><strong>Mixed Effects Models</strong> = Fixed Effects <em>and</em> Random Effects
<ul>
<li>i.e.&nbsp;variation within the unit and between the units</li>
</ul></li>
<li>Harrell (<a href="https://www.fharrell.com/post/re/">article</a>)
<ul>
<li>Says that Mixed Models models can capture within-subject correlation of repeated measures over very short time intervals but not&nbsp; over extended time intervals&nbsp; where autocorrelation comes into play
<ul>
<li>Example of a short interval is a series of tests on a subject over minutes when the subject does not fatigue</li>
<li>Example of a long interval is a typical longitudinal clinical trial where patient responses are assessed weekly or monthly</li>
</ul></li>
<li>He recommends a Markov model for longitudinal RCT data (see bkmks)</li>
</ul></li>
<li>Bartlett
<ul>
<li><a href="https://thestatsgeek.com/2020/12/30/mixed-model-repeated-measures-mmrm-in-stata-sas-and-r/">Mixed model repeated measures (MMRM) in Stata, SAS and R</a>
<ul>
<li>Tutorial; uses nlme::gls</li>
</ul></li>
</ul></li>
</ul></li>
<li><span style="color: #990000">{tidymodels}</span> <a href="https://multilevelmod.tidymodels.org/articles/multilevelmod.html#models-using-lmer-glmer-and-stan_glmer'">workflows</a> (optional outputs: lmer, glmer, stan_glmer objects)</li>
</ul></li>
<li><p>Motivation for using a Random Effects model</p>
<ul>
<li>You think the little subgroups are part of some bigger group with a common mean effect
<ul>
<li>e.g.&nbsp;multiple observations of a single person, or multiple people in a school, or multiple schools in a district, or multiple varieties of a single kind of fruit, or multiple kinds of vegetable from the same harvest, or multiple harvests of the same kind of vegetable, etc.</li>
</ul></li>
<li>These subgroup means significantly <em>deviate</em> from the big group mean.</li>
<li>These <em>deviations</em> follow a distribution, typically Gaussian.
<ul>
<li>That’s where the “random” in <strong>random effects</strong> comes in: we’re assuming the <em>deviations</em> of subgroups from a parent follow the distribution of a <em>random</em> (Gaussian) variable
<ul>
<li>The variation between subgroups is assumed to have a normal distribution with a 0 mean and constant variance (variance estimated by the model).</li>
</ul></li>
<li>GEEs are a semi-parametric option for panel data (See <a href="Regression, Other">Regression, Other</a> &gt;&gt; Generalized Estimating Equations (GEE))</li>
</ul></li>
</ul></li>
<li><p>Model Choice</p>
<ul>
<li><p>Pooling <strong>Complete pooling</strong> - Each unit is assumed to have the <em>same</em> effect Example: County is the grouping variable and radon level is the outcome All counties are <em>alike</em>. i.e.&nbsp;all characteristics of counties that affect radon levels in houses have the statistically same effect across counties. Therefore, the variable has no information.</p>
<pre><code>          Run a single regression to estimate the average radon level in the whole state.
              `lm(radon_level ~ predictors)`

              Note that "county" is NOT a predictor in this model

  **No pooling** - All units are assumed to have _independent_ effects
      Example: County is the grouping variable (although not a predictor in this case) and radon level is the outcome
          All counties are _different_ from each other.
              i.e. there are no common characteristics of counties that affect radon levels in houses. Any characteristic a county has that affects radon levels is unique to that county.

          Run a regression for each county to estimate the average radon level for each county.
              `lm(radon_level ~ 0 + county + predictors`

              Using the "0 + " formula removes the common intercept which means each county will get it's own intercept</code></pre>
<ul>
<li><strong>Partial pooling</strong> - Each unit is assumed to have a different effect, but the data for all of the observed units informs the estimates for each unit
<ul>
<li><p>Example: County is the grouping variable (random effect) and radon level is the outcome All counties are <em>similar</em> each other. i.e.&nbsp;all charcteristics of counties that affect radon levels in house have statistically varying effects sizes depending on the particular county</p>
<pre><code>  Run a multi-level regression to share information across counties.
      `lmer(radon_level ~ predictors + (1 + predictor | county))`</code></pre></li>
<li><p>This can be a nice compromise between estimating an effect by completely pooling all groups, which masks group-level variation, and estimating an effect for all groups completely separately, which could give poor estimates for low-sample groups.</p></li>
<li><p>If you have few data points in a group, the group’s effect estimate will be based partially on the more abundant data from other groups. (2 min <a href="https://www.youtube.com/watch?v=qMe7qwNMe-s">video</a>) Partial pooling is typically accomplished through hierarchical models. Hierarchical models directly model the population of units. From a population model perspective, no pooling corresponds to infinite population variance, whereas complete pooling corresponds to zero population variance.</p></li>
</ul></li>
</ul></li>
<li><p>Fixed Effects or Random Effects?</p>
<ul>
<li>If there’s likely correlation between unobserved group/cases variables (e.g.&nbsp;individual talent) and treatment variable (i.e.&nbsp;E(α|x) != 0) AND there’s substantial variance between group units, then FE is a better choice (see <a href="Econometrics, Fixed Effects">Econometrics, Fixed Effects</a> &gt;&gt; Fixed Effects &gt;&gt; 1-way assumptions)</li>
<li>If cases units change little, or not at all, across time, a fixed effects model may not work very well or even at all (SEs for a FE model will be large)
<ul>
<li><strong>The FE model is for analyzing within-units variance</strong></li>
</ul></li>
<li>Do we wish to estimate the effects of variables whose values do not change across time, or do we merely wish to control for them?
<ul>
<li>FE: these effects aren’t estimated but adjusted for by explicitly including a separate intercept term for each individual (αi) in the regression equation</li>
<li>RE: estimates these effects (might be biased if RE assumptions violated)
<ul>
<li><strong>The RE model is for analyzing between-units variance</strong></li>
</ul></li>
</ul></li>
<li>The amount of within-unit variation relative to between-unit variation has important implications for these two approaches
<ul>
<li><a href="https://www.r-bloggers.com/2022/06/fixed-effects-vs-random-effects-for-web-browsing-data-a-simulation/">Article</a> with simulated data showed that within variation around sd &lt; 0.5 didn’t detect the effect of explanatory variable but ymmv (depends on # of units, observations per unit, N)</li>
</ul></li>
<li>Durbin–Wu–Hausman test ({plm::phtest})
<ul>
<li>If H0 is not rejected, then both FE and RE are consistent but only RE is efficient. –&gt; use RE but if you have a lot of data, then FE is also fine.</li>
<li>If H0 is rejected, then only FE is consistent –&gt; use FE</li>
</ul></li>
<li>ICC &gt; 0.1 is generally accepted as the minimal threshold for justifying the use of Mixed Effects Model (See ICC section)</li>
</ul></li>
</ul></li>
<li><p>Advantages of a mixed model (y ~ x + (x | g)) vs a linear model with an interaction (y ~ x * g)</p>
<ul>
<li>From T.J. Mahr <a href="https://twitter.com/tjmahr/status/1504124329319096323">tweet</a></li>
<li>Conceptual: Assumes participant means are drawn from the same latent population</li>
<li>Computational: partial pooling / smoothing</li>
<li>Both will have very similar parameter estimates when the data is balanced with few to no outliers
<ul>
<li>linear least squares regression can overstate precision, producing t-statistics for each fixed effect that tend to be larger than they should be; the number of significant results in LLSR are then too great and not reflective of the true structure of the data</li>
<li>Standard errors are underestimated in the interaction model though.
<ul>
<li>Doesn’t account for dependence in the repeated measure for each subject</li>
</ul></li>
<li>For unbalanced data w/some group categories having few data points or with outliers, the mixed effects model regularizes/shrinks/smooths the estimates to the overall group (i.e.&nbsp;population) mean</li>
</ul></li>
<li>Example of model formula interpretation<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/FLvupd_WYAQPIzA.png" class="img-fluid"></li>
</ul></li>
<li><p>Assumptions E(αi|xit) = 0: No time-constant unobserved heterogeneity i.e.&nbsp;no correlation between time-invariant valued, unobserved variables (aka random effect variable) and the explanatory variable of interest (e.g.&nbsp;treatment) time-invariant valued, unobserved variables: variables that are constant across time for each unit and explain variation <em>between-units</em> e.g.&nbsp;if random effect variable (aka clustering variable) is the individual, then the “time-invariant, unobserved” variable could be something latent like talent or something measureable like intelligence or socio-economic status. Whatever is likely to explain the variance between-units in relation to the response.</p>
<pre><code>      The effect that these variables have must also be time-invariant
      * e.g. the effect of gender on the outcome at time 1 is the same as the effect of gender at time 5
      * If effects are time-varying, then an interaction of gender with time could be included
      It's not reasonable for this to be _exactly_ zero in order to use a mixed effected model, but for situations where there's high correlation, this model should be avoided

  * Example: violation

      ![](./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/unnamed-chunk-21-1.png)
      * Each group's x values get larger from left to right as each group's α (aka y-intercepts) for each unit get larger
          * i.e. multi-effects models fail in cases where there's very high correlation between group intercepts and x, together with large between-group variability compared to the within-group variability
      * \*\*FE model would be better in this case
          * Gelman has a [paper](file:///C:/Users/tbats/Documents/R/Documents/Regression/mixed%20effects/fitting-multilevel-models-when-predictors-group-effects-correlate-Bafumi-Gelman.pdf) that describes how a mixed effect model can be fit in this situation though
  E(ϵit|xit) = 0: No time-varying unobserved heterogeneity
  * i.e no endogeneity (no correlation between the residuals and explanatory variable of interest)
  * If violated, there needs to be explicit measurements of omitted time-invariant variables (see 1st assumption for definition) if they are thought to _interact_ with other variables in the model.</code></pre></li>
<li><p>Variable Assignment</p>
<ul>
<li>Questions (<a href="https://rlbarter.github.io/Practical-Statistics/2017/03/03/fixed-mixed-and-random-effects/">article</a> has examples)
<ul>
<li>Can the groups we see be considered the full population of possible groups we could see, or are they more like a random sample of a larger set of groups?
<ul>
<li>Full Population: Fixed</li>
<li>Random Sample: Random</li>
</ul></li>
<li>Do we want to estimate a coefficient for this grouping, or do we just want to account for the anticipated structure that the groups may impose on our observations?
<ul>
<li>Y: Fixed</li>
<li>N: Random</li>
</ul></li>
</ul></li>
<li><strong>Fixed Effects</strong> provide estimates of mean-differences or slopes.
<ul>
<li>“Fixed” because they are effects that are constant for each subject/unit</li>
<li>Level One: variables measured at the most frequently occurring observational unit
<ul>
<li>i.e.&nbsp;vary for each repeated measure of a subject and vary between subjects
<ul>
<li>In the dataset, these variables that (for the most part) have different values for each row</li>
<li>Time-dependent if you have longitudinal data</li>
</ul></li>
<li>For a RE model, these are usually the adjustment variables
<ul>
<li>e.g.&nbsp;conditioning on a confounder</li>
</ul></li>
</ul></li>
<li>Level Two: variables measured at the observational unit level
<ul>
<li>i.e.&nbsp;constant for each repeated measure of a subject but vary between each subject</li>
<li>For a RE model, these are usually the treatment variables or variables of interest
<ul>
<li>They should contain the information about the between-subject variation</li>
</ul></li>
<li>If a factor variable, it has levels which would not change in replications of the study</li>
</ul></li>
</ul></li>
<li><strong>Random Effects</strong> estimate of variation between and within subgroups
<ul>
<li>Clustering variable</li>
<li>Quantifies how much of the overall variation can be attributed to that particular variable.
<ul>
<li>Example: the variation in beetle DAMAGE was attributable to the FARM at which the damage took place, so you’d cluster by FARM (<code>1|FARM</code>)</li>
</ul></li>
<li>If you want slopes to vary according to a variable, the variation of slopes between-units will be a random effect
<ul>
<li>Usually a level 2 fixed effect variable</li>
</ul></li>
<li>If you want intercepts to vary according to a variable, the variation of intercepts between-units will be a random effect
<ul>
<li>This will the unit/subject variable (e.g student id, store id) that has the repeated observations</li>
</ul></li>
<li>Typically categorical variables that we are <em>not</em> interested in measuring their effects on the outcome variable, but we do want to adjust for. This variation might capture effects of latent variables.
<ul>
<li>This factor variable has levels which can be thought of as a sample from a larger population of factor levels (e.g.&nbsp;hockey players)</li>
<li><span class="ribbon-highlight">Example</span>: 2 hockey players both averaged around 20 minutes per game last year (fixed variable). Predictions of the amount of points scored by just accounting for this fixed variable would produce similar results. But using PLAYER as a random variable will capture the impact of persistent characteristics that might not be observable elsewhere in the explanatory data. PLAYER can be thought of as a proxy for “offensive talent” in a way.</li>
</ul></li>
<li>If the values of the variable were chosen at random, then you should cluster by that variable (i.e.&nbsp;choose as the random variable)
<ul>
<li><span class="ribbon-highlight">Example</span>: If you can rerun the study using different specific farms (i.e .different values of the FARM factor, see above) and still be able to draw the same conclusions, then FARM should be a random effect.
<ul>
<li>However, if you had wanted to compare or control for these particular farms, then Farm would be “fixed.”</li>
<li>Say that there is nothing about comparing these specific fields that is of interest to the researcher. Rather, the researcher wants to generalize the results of this experiment to all fields. Then, FIELD would be “random.”</li>
</ul></li>
</ul></li>
<li>If the random effects are correlated with variables of interest (fixed effects), leaving them out could lead to biased fixed effects. Including them can help more reliably isolate the influence of the fixed effects of interest and more accurately model a clustered system.</li>
<li>To see individual random effects: <code>lme4::ranef(lme_mod)</code> or <code>lme4::ranef(tidy_mod$fit)</code></li>
</ul></li>
</ul></li>
<li><p>Specifications and Notation</p>
<ul>
<li>Varying intercept: <code>(1 | v1)</code>
<ul>
<li><p>aka random intercepts, where each level of the random variable (our random effect) had an adjustment to the overall intercept</p></li>
<li><p><span class="ribbon-highlight">Example</span>: each DEPARTMENT (random variable) has a different starting (intercepts) SALARY (outcome variable) for their faculty members (observations), while the annual rate (slope) at which salaries increase is consistent across the university (i.e.&nbsp;effect is constant between-DEPARTMENTS)<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (925).png" class="img-fluid"><img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (917).png" class="img-fluid"></p>
<ul>
<li><p>where j[i] is the index for “department”</p></li>
<li><p>This strategy allows us to capture variation in the starting SALARY (intercepts) of our faculty</p></li>
</ul></li>
</ul></li>
<li>Varying Slopes: <code>(0 + v2| v1)</code>
<ul>
<li><p>aka random slopes, which would allow the effect of the v2 to vary by v1</p>
<ul>
<li>i.e.&nbsp;v2 is a predictor whose effect varies according to the level of the grouping variable, v1.</li>
</ul></li>
<li><p>i.e.&nbsp;a slope for each level of the random effects variable</p></li>
<li><p><span class="ribbon-highlight">Example</span>: faculty SALARY (outcome) increase at different rates (slopes) depending on the DEPARTMENT (random variable).<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (926).png" class="img-fluid"><img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (919).png" class="img-fluid"></p>
<ul>
<li><p>where j[i] is the index for “department”</p></li>
<li><p>This strategy allows us to capture variation in the <em>change</em> (slopes) in SALARY</p></li>
</ul></li>
</ul></li>
<li>Varying Slopes and Intercepts: <code>(1 + v2 | v1)</code> or just <code>(v2 | v1)</code> (See examples)
<ul>
<li><p>See above for descriptions of each</p></li>
<li><p><span class="ribbon-highlight">Example</span>: each DEPARTMENT (random variable) has a different starting (intercepts) SALARY (outcome variable) for their faculty members (observations), while the annual rate (slope) at which salaries increase varies depending on DEPARTMENT<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (922).png" class="img-fluid"><img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (921).png" class="img-fluid"></p>
<ul>
<li><p>where j[i] is the index for “department”</p></li>
<li><p>See above for descriptions of each type of variation this strategy captures</p></li>
</ul></li>
</ul></li>
<li>Nested effects
<ul>
<li>e.g.&nbsp;studying test scores (outcome variable) within schools (random variable) that are within districts (random variable)</li>
<li>notation: <code>(1 | v1 / v2)</code> says intercepts varying among v1 <em>and</em> v2 <em>within</em> v1.
<ul>
<li>e.g.&nbsp;schools is v2 and districts is v1</li>
</ul></li>
</ul></li>
</ul></li>
<li><p>Strategy</p>
<ul>
<li>Misc
<ul>
<li>begins with a saturated fixed effects model, determines variance components based on that, and then simplifies the fixed part of the model after fixing the random part.</li>
</ul></li>
<li>Overall:
<ul>
<li>EDA</li>
<li>Fit some simple, preliminary models, in part to establish a baseline for evaluating larger models.</li>
<li>Then, build toward a final model for description and inference by attempting to add important covariates, centering certain variables, and checking model assumptions.</li>
</ul></li>
<li>Process
<ul>
<li>EDA at each level (see <a href="EDA, Hierarchical">EDA, Hierarchical</a>)</li>
<li>Examine models with no predictors to assess variability at each level</li>
<li>Create Level One models: starting simple and adding terms as necessary (see Fixed Effects below)</li>
<li>Create Level Two models: starting simple and adding terms as necessary (see Fixed Effects below)
<ul>
<li>Beginning with the equation for the intercept term.</li>
</ul></li>
<li>Examine the random effects and variance components (see Random Effects below)
<ul>
<li>Beginning with a full set of error terms and then removing covariance terms and variance terms where advisable
<ul>
<li>e.g.&nbsp;when parameter estimates are failing to converge or producing impossible or unlikely values</li>
</ul></li>
<li>See Specifications and Notation for different RE modeling strategies.</li>
</ul></li>
</ul></li>
</ul></li>
<li><p><strong>InterClass Coefficient (ICC)</strong>: The proportion of variation that is between-cases<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/ql_5544a786804218cec597e03dee52d1b5_l3.png" class="img-fluid"></p>
<ul>
<li>where σ0 is the between-case variance and σε is the within-case variance.</li>
<li>1-ICC is the proportion of variation within cases</li>
<li>Statistical power is a function of ICC (<a href="https://www.rdatagen.net/post/2023-04-18-generating-variable-cluster-sizes-to-assess-power-in-cluster-randomize-trials/">article</a>)<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/image.png" class="img-fluid">
<ul>
<li>Both higher ICCs and cluster size variability lead to reduced power</li>
<li>The dispersion parameter is a parameter used in the data simulation</li>
</ul></li>
<li>Guideline: ICC &gt; 0.1 is generally accepted as the minimal threshold for justifying the use of Mixed Effects Model</li>
</ul></li>
</ul>
<pre><code>library(sjPlot)
tab_model(lme_fit)</code></pre>
<ul>
<li>Might need <span style="color: #990000">{lmerTest}</span> loaded to get coefficient pvals</li>
<li>Also calculates two R2 values
<ul>
<li>Marginal: proportion of variance explained , by the fixed effects only</li>
<li>Conditional: proportion of variance explained by the fixed effects and random effects</li>
</ul></li>
<li>Diagnostics
<ul>
<li>Misc
<ul>
<li><span style="color: #990000">{</span><a href="https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html" style="color: #990000">DHARMa</a><span style="color: #990000">}</span> - Built for Mixed Effects Models for count distributions but <em>also</em> handles lm, glm (poisson) and MASS::glm.nb (neg.bin)</li>
</ul></li>
<li>Binned Residuals
<ul>
<li>It is not useful to plot the raw residuals, so examine binned residual plots</li>
<li>Misc
<ul>
<li>{arm} will mask some {tidyverse} functions, so don’t load whole package</li>
</ul></li>
<li>Look for :
<ul>
<li>Patterns</li>
<li>Nonlinear trend may be indication that squared term or log transformation of predictor variable required</li>
<li>If bins have average residuals with large magnitude</li>
<li>Look at averages of other predictor variables across bins</li>
<li>Interaction may be required if large magnitude residuals correspond to certain combinations of predictor variables</li>
</ul></li>
<li>Process
<ul>
<li>Extract raw residuals
<ul>
<li>Include <code>type.residuals = "response"</code> in the <code>broom::augment</code> function to get the raw residuals</li>
</ul></li>
<li>Order observations either by the values of the predicted probabilities (or by numeric predictor variable)</li>
<li>Use the ordered data to create g bins of approximately equal size.
<ul>
<li>Default value: g = sqrt(n)</li>
</ul></li>
<li>Calculate average residual value in each bin</li>
<li>Plot average residuals vs.&nbsp;average predicted probability (or average predictor value)</li>
</ul></li>
<li><span class="ribbon-highlight">Example</span>: vs Predicted Values<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/image.1.png" class="img-fluid"></li>
</ul></li>
</ul></li>
</ul>
<pre><code>arm::binnedplot(x = risk_m_aug$.fitted, y = risk_m_aug$.resid,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; xlab = "Predicted Probabilities",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; main = "Binned Residual vs. Predicted Values",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; col.int = FALSE)</code></pre>
<ul>
<li><span class="ribbon-highlight">Example</span>: vs Predictor<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/image.2.png" class="img-fluid"></li>
</ul>
<pre><code>arm::binnedplot(x = risk_m_aug$ageCent,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; y = risk_m_aug$.resid,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; col.int = FALSE,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; xlab = "Age (Mean-Centered)",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; main = "Binned Residual vs. Age")</code></pre>
<ul>
<li>Check that residuals have mean zero: <code>mean(resid(mod))</code></li>
<li>Check that residuals for each level of categorical have mean zero</li>
</ul>
<pre><code>risk_m_aug %&gt;%
&nbsp; group_by(currentSmoker) %&gt;%
&nbsp; summarise(mean_resid = mean(.resid))</code></pre>
<pre><code>Check for normality.</code></pre>
<pre><code># Normal Q-Q plot
qqnorm(resid(mod))
qqline(resid(mod))</code></pre>
<ul>
<li>Check normality per categorical variable level
<ul>
<li>Example: 3 levels</li>
</ul></li>
</ul>
<pre><code>## by level
par(mfrow=c(1,3))

qqnorm(resid(mod)[1:6])
qqline(resid(mod)[1:6])

qqnorm(resid(mod)[7:12])
qqline(resid(mod)[7:12])

qqnorm(resid(mod)[13:18])
qqline(resid(mod)[13:18])</code></pre>
<ul>
<li><p>Data should be sorted by random variable level before modeling. Otherwise you could column bind the residuals to the original data. Then, group by random variable and&nbsp; make q-q plots for each group</p></li>
<li><p><span class="ribbon-highlight">Example</span>: one-way random effects</p></li>
</ul>
<pre><code>re1 &lt;- plm(happiness ~ age, data = df,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; index = c("id", "wave"),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; effect = "individual", model = "random")

summary(re1)
## Effects:
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var std.dev share
## idiosyncratic 0.03641 0.19081 0.096
## individual&nbsp; &nbsp; 0.34396 0.58648 0.904
## theta: 0.8394
## Coefficients:
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error z-value&nbsp; Pr(&gt;|z|)&nbsp; &nbsp;
## (Intercept)&nbsp; 6.933947&nbsp; 1.534054&nbsp; 4.5200 6.183e-06 ***
## age&nbsp; &nbsp; &nbsp; &nbsp; -0.015621&nbsp; 0.031277 -0.4994&nbsp; &nbsp; 0.6175</code></pre>
<ul>
<li><p>In Fixed effects, “id” is the <em>cases</em> variable and “wave” is the time variable, but I’m not sure if that’s how they’re referred to&nbsp; in a Mixed Effects model</p>
<ul>
<li>Maybe indexes are always required for panel data even if it isn’t a FE model</li>
</ul></li>
<li><p><code>effect = "individual", model = "random"</code> specifies the model as a mixed effects model</p></li>
<li><p>idiosyncratic is the time-variant variance (within-cases, ε) variance</p></li>
<li><p>individual is the time-constant (between-cases, α) variance</p></li>
<li><p><span class="ribbon-highlight">Example</span>: random intercept-only model (aka unconditional means model) from https://www.alexcernat.com/etimating-multilevel-models-for-change-in-r/</p></li>
</ul>
<pre><code>library(lme4)
# unconditional means model (a.k.a. random effects model)
m0 &lt;- lmer(data = usl, logincome ~ 1 + (1 | pidp))

# check results
summary(m0)
## Linear mixed model fit by REML ['lmerMod']
## Formula: logincome ~ 1 + (1 | pidp)
##&nbsp; &nbsp; Data: usl
##&nbsp;
## REML criterion at convergence: 101669.8
##&nbsp;
## Scaled residuals:&nbsp;
##&nbsp; &nbsp; Min&nbsp; &nbsp; &nbsp; 1Q&nbsp; Median&nbsp; &nbsp; &nbsp; 3Q&nbsp; &nbsp; Max&nbsp;
## -7.2616 -0.2546&nbsp; 0.0627&nbsp; 0.3681&nbsp; 5.8845&nbsp;
##&nbsp;
## Random effects:
##&nbsp; Groups&nbsp; Name&nbsp; &nbsp; &nbsp; &nbsp; Variance Std.Dev.
##&nbsp; pidp&nbsp; &nbsp; (Intercept) 0.5203&nbsp; 0.7213&nbsp;
##&nbsp; Residual&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 0.2655&nbsp; 0.5152&nbsp;
## Number of obs: 52512, groups:&nbsp; pidp, 8752
##&nbsp;
## Fixed effects:
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error t value
## (Intercept) 7.162798&nbsp; 0.008031&nbsp; 891.8</code></pre>
<ul>
<li><code>usl</code> is UK sociological survey data
<ul>
<li><code>logincome</code>is a logged income variable</li>
<li><code>pidp</code>is the person’s id</li>
</ul></li>
<li>Interpretation
<ul>
<li>Fixed effects:
<ul>
<li>(Intercept) = 7.162798, which is the grand mean
<ul>
<li>says that over all the time points and individuals, the estimated average log income is 7.162798</li>
</ul></li>
</ul></li>
<li>Random effects:
<ul>
<li>everything that varies by “pidp”</li>
<li>between-case (or person, group, cluster, etc.) variance: (Intercept) = 0.5203</li>
<li>within-case (or person, group, cluster, etc.) variance: Residual =&nbsp; 0.2655</li>
</ul></li>
</ul></li>
<li>ICC
<ul>
<li>0.520/(0.520 + 0.265) = 0.662</li>
<li>says about 66% of the variation in log income comes between people while the remaining (~ 34%) is within people.</li>
</ul></li>
<li><code>Example:</code> Random Intercept w/covariate
<ul>
<li>random effect: cases; fixed effect: time</li>
<li>from https://www.alexcernat.com/etimating-multilevel-models-for-change-in-r/</li>
</ul></li>
</ul>
<pre><code>library(lme4)
# unconditional change model (a.k.a. MLMC)
m1 &lt;- lmer(data = usl, logincome ~ 1 + wave0 + (1 | pidp))

summary(m1)
## Linear mixed model fit by REML ['lmerMod']
## Formula: logincome ~ 1 + wave0 + (1 | pidp)
##&nbsp; &nbsp; Data: usl
##&nbsp;
## REML criterion at convergence: 100654.8
##&nbsp;
## Scaled residuals:&nbsp;
##&nbsp; &nbsp; Min&nbsp; &nbsp; &nbsp; 1Q&nbsp; Median&nbsp; &nbsp; &nbsp; 3Q&nbsp; &nbsp; Max&nbsp;
## -7.1469 -0.2463&nbsp; 0.0556&nbsp; 0.3602&nbsp; 5.7533&nbsp;
##&nbsp;
## Random effects:
##&nbsp; Groups&nbsp; Name&nbsp; &nbsp; &nbsp; &nbsp; Variance Std.Dev.
##&nbsp; pidp&nbsp; &nbsp; (Intercept) 0.5213&nbsp; 0.7220&nbsp;
##&nbsp; Residual&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 0.2593&nbsp; 0.5092&nbsp;
## Number of obs: 52512, groups:&nbsp; pidp, 8752
##&nbsp;
## Fixed effects:
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error t value
## (Intercept) 7.057963&nbsp; 0.008665&nbsp; 814.51
## wave0&nbsp; &nbsp; &nbsp; 0.041934&nbsp; 0.001301&nbsp; 32.23
##&nbsp;
## Correlation of Fixed Effects:
##&nbsp; &nbsp; &nbsp; (Intr)
## wave0 -0.375</code></pre>
<ul>
<li><code>usl</code> is UK sociological survey data
<ul>
<li><code>logincome</code>is a logged income variable</li>
<li><code>pidp</code>is the person’s id</li>
<li><code>wave0</code>is the time variable that’s indexed at 0</li>
</ul></li>
<li>Interpretation
<ul>
<li>Fixed effects:
<ul>
<li>(Intercept) = 7.057; the expected log income at the beginning of the study (wave 0).</li>
<li>wave0 = 0.0419
<ul>
<li>the average rate of change with the passing of a wave.
<ul>
<li>I don’t think this is a percentage. It’s the same as a standard OLS regression interpretation.</li>
</ul></li>
<li>So after each wave, individual log income is expected to slowly increase by 0.041 on average.</li>
</ul></li>
</ul></li>
<li>Random effects:
<ul>
<li>everything that varies by “pidp”</li>
<li>between-case (or person, group, cluster, etc.) variance in log income: (Intercept) = 0.5213</li>
<li>within-case (or person, group, cluster, etc.) variance in log income: Residual =&nbsp; 0.2593</li>
<li>So this stuff is still very similar numbers as the random intercept-only model</li>
</ul></li>
</ul></li>
</ul>
<pre><code>usl$pred_m1 &lt;- predict(m1)
usl %&gt;%&nbsp;
&nbsp; filter(pidp %in% 1:5) %&gt;% # select just five individuals
&nbsp; ggplot(aes(wave, pred_m1, color = pidp)) +
&nbsp; geom_point(aes(wave, logincome)) + # points for observed log income
&nbsp; geom_smooth(method = lm, se = FALSE) + # linear line showing wave0 slope
&nbsp; theme_bw() +
&nbsp; labs(x = "Wave", y = "Logincome") +&nbsp;
&nbsp; theme(legend.position = "none")</code></pre>
<p><img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/unnamed-chunk-8-1.png" class="img-fluid"></p>
<ul>
<li>wave was indexed to 0 for the model but now wave starts at 1. He might’ve reverted wave to have a starting value of 1 for graphing purposes</li>
<li>Lines show the small, positive, fixed effect slope for <code>wave0</code></li>
<li>parallel lines means we assume the change in log income over time is the same for all the individuals
<ul>
<li>i.e.&nbsp;we assume there is no between-case variation in the rate of change.</li>
</ul></li>
<li><span class="ribbon-highlight">Example</span>: Random (Varying) Slopes and Intercepts
<ul>
<li>random effect: outcome (i.e.&nbsp;intercept) by cases, time effect by cases; fixed effect: time from https://www.alexcernat.com/etimating-multilevel-models-for-change-in-r/</li>
</ul></li>
</ul>
<pre><code>library(lme4)
# unconditional change model (a.k.a. MLMC) with re for change
m2 &lt;- lmer(data = usl, logincome ~ 1 + wave0 + (1 + wave0 | pidp))

summary(m2)
## Linear mixed model fit by REML ['lmerMod']
## Formula: logincome ~ 1 + wave0 + (1 + wave0 | pidp)
##&nbsp; &nbsp; Data: usl
##&nbsp;
## REML criterion at convergence: 98116.1
##&nbsp;
## Scaled residuals:&nbsp;
##&nbsp; &nbsp; Min&nbsp; &nbsp; &nbsp; 1Q&nbsp; Median&nbsp; &nbsp; &nbsp; 3Q&nbsp; &nbsp; Max&nbsp;
## -7.8825 -0.2306&nbsp; 0.0464&nbsp; 0.3206&nbsp; 5.8611&nbsp;
##&nbsp;
## Random effects:
##&nbsp; Groups&nbsp; Name&nbsp; &nbsp; &nbsp; &nbsp; Variance Std.Dev. Corr&nbsp;
##&nbsp; pidp&nbsp; &nbsp; (Intercept) 0.69590&nbsp; 0.8342&nbsp; &nbsp; &nbsp; &nbsp;
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; wave0&nbsp; &nbsp; &nbsp; 0.01394&nbsp; 0.1181&nbsp; -0.51
##&nbsp; Residual&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 0.21052&nbsp; 0.4588&nbsp; &nbsp; &nbsp; &nbsp;
## Number of obs: 52512, groups:&nbsp; pidp, 8752
##&nbsp;
## Fixed effects:
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error t value
## (Intercept) 7.057963&nbsp; 0.009598&nbsp; 735.39
## wave0&nbsp; &nbsp; &nbsp; 0.041934&nbsp; 0.001723&nbsp; 24.34
##&nbsp;
## Correlation of Fixed Effects:
##&nbsp; &nbsp; &nbsp; (Intr)
## wave0 -0.558</code></pre>
<ul>
<li><code>usl</code> is UK sociological survey data
<ul>
<li><code>logincome</code>is a logged income variable</li>
<li><code>pidp</code>is the person’s id</li>
<li><code>wave0</code>is the time variable that’s indexed at 0</li>
<li><code>(1 + wave0 | pidp)</code>
<ul>
<li>says let both the intercept (“1”) and wave0 vary by pidp
<ul>
<li>which means that average log income varies by person and the rate of change (slope) in log income over time (wave0 fixed effect) varies by person.</li>
</ul></li>
</ul></li>
</ul></li>
<li>Interpretation
<ul>
<li>Fixed effects:
<ul>
<li>(Intercept) =7.057963; the expected log income at the beginning of the study (wave 0).</li>
<li>wave0 = 0.0419
<ul>
<li>the average rate of change with the passing of a wave.
<ul>
<li>I don’t think this is a percentage. It’s the same as a standard OLS regression interpretation.</li>
</ul></li>
<li>So after each wave, individual log income is expected to slowly increase by 0.041 on average.</li>
</ul></li>
</ul></li>
<li>Random effects:
<ul>
<li>everything that varies by “pidp”</li>
<li>between-case (or person, group, cluster, etc.) variance of log income:
<ul>
<li>(Intercept) = 0.69590</li>
<li>how much average log income varies by person at the start of the study (wave = 0)</li>
</ul></li>
<li>within-case (or person, group, cluster, etc.) variance of log income:
<ul>
<li>Residual =&nbsp; 0.21052</li>
<li>how much each person’s log income varies in relation to her average log income</li>
</ul></li>
<li>between-case variance in the rates of change of log income over time
<ul>
<li>wave0 = 0.01394</li>
<li>i.e.&nbsp;how much the fixed effect, wave0, slope varies by person</li>
</ul></li>
</ul></li>
</ul></li>
</ul>
<pre><code>usl$pred_m2 &lt;- predict(m2)
usl %&gt;%&nbsp;
&nbsp; filter(pidp %in% 1:5) %&gt;% # select just two individuals
&nbsp; ggplot(aes(wave, pred_m2, color = pidp)) +
&nbsp; geom_point(aes(wave, logincome)) + # points for observed logincome
&nbsp; geom_smooth(method = lm, se = FALSE) + # linear line based on prediction
&nbsp; theme_bw() + # nice theme
&nbsp; labs(x = "Wave", y = "Logincome") + # nice labels
&nbsp; theme(legend.position = "none")</code></pre>
<p><img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/unnamed-chunk-9-1.png" class="img-fluid"></p>
<ul>
<li><p>Different slopes for each person</p></li>
<li><p><span class="ribbon-highlight">Example</span>: Varying Slopes and Intercepts</p></li>
</ul>
<pre><code>m_slope &lt;- lmer(pp60 ~ position + toi + (1 + age | player),&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; data = df)</code></pre>
<ul>
<li><p>We use this model if we wanted to incorporate an age variable into our model and we wanted the influence of that variable to vary by player, it would be incorporated like so, before the | player:</p></li>
<li><p><span class="ribbon-highlight">Example</span> (ggeffects error bar plot)</p>
<ul>
<li>Description:
<ul>
<li>outcome: Distance; fixed effect: Season; random_effect: Athlete<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/staticunnamed-chunk-6-1.png" class="img-fluid"></li>
</ul></li>
</ul></li>
</ul>
<pre><code>library(ggeffects)
library(ggplot2)
# create plot dataframe
# Has 95% CIs for fixed effects and lists random effects
plot_data &lt;- ggpredict(fit, terms = c("Season"))

#create plot
plot_data %&gt;%
&nbsp; #reorder factor levels for plotting
&nbsp; mutate(x = ordered(x, levels = c("Preseason", "Inseason", "Postseason"))) %&gt;%
&nbsp; #use plot function with ggpredict objects
&nbsp; plot() +&nbsp;
&nbsp; #add ggplot2 as needed
&nbsp; theme_blank() + ylim(c(3000,7000)) + ggtitle("Session Distance by Season Phase")</code></pre>
<ul>
<li>Example: tidymodels</li>
</ul>
<pre><code>lmer_spec &lt;-&nbsp;
&nbsp; linear_reg() %&gt;%&nbsp;
&nbsp; set_engine("lmer")

tidy_mod &lt;-&nbsp;
&nbsp; lmer_spec %&gt;%&nbsp;
&nbsp; fit(pp60 ~ position + toi + (1 | player),
&nbsp; &nbsp; &nbsp; data = df)

tidy_mod
## parsnip model object
##&nbsp;
## Linear mixed model fit by REML ['lmerMod']
## Formula: pp60 ~ position + toi + (1 | player)
##&nbsp; &nbsp; Data: data
## REML criterion at convergence: 115.8825
## Random effects:
##&nbsp; Groups&nbsp; Name&nbsp; &nbsp; &nbsp; &nbsp; Std.Dev.
##&nbsp; player&nbsp; (Intercept) 0.6423&nbsp;
##&nbsp; Residual&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 0.3452&nbsp;
## Number of obs: 80, groups:&nbsp; player, 20
## Fixed Effects:
## (Intercept)&nbsp; &nbsp; positionF&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; toi&nbsp;
##&nbsp; &nbsp; -0.16546&nbsp; &nbsp; &nbsp; 1.48931&nbsp; &nbsp; &nbsp; 0.06254</code></pre>
<p>Beyond Multiple Linear Regression (<a href="https://bookdown.org/roback/bookdown-BeyondMLR/">link</a>) Chapter 8 (Introduction to Multilevel Models)</p>
<ul>
<li>Variable types
<ul>
<li>Level One: variables measured at the most frequently occurring observational unit
<ul>
<li>i.e.&nbsp;variables that (for the most part) have different values for each row</li>
<li>i.e.&nbsp;vary for each repeated measure of a subject and vary between subjects</li>
</ul></li>
<li>Level Two: variables measured on larger observational units
<ul>
<li>i.e.&nbsp;constant for each repeated measure of a subject but vary between each subject</li>
</ul></li>
</ul></li>
<li>Example Description
<ul>
<li>“na” (outcome) - negative affect (i.e.&nbsp;performance anxiety)</li>
<li>“LargeEns” -&nbsp; binary
<ul>
<li>LargeEns = 1 means the performance type is a Large Ensemble</li>
<li>LargeEns = 0 means the performance type is either a solo or small ensemble</li>
</ul></li>
<li>“Orch” - binary
<ul>
<li>Orch = 1 means the instrument is Orchestral</li>
<li>Orch = 0 means the instrument is either a Keyboard or it’s Vocal</li>
</ul></li>
</ul></li>
<li>2-Stage Model
<ul>
<li>The 2-stage model shows a clearer depiction of how a multi-level model is fit in principle
<ul>
<li>2-stage model uses Ordinary Least Squares to fit a system of regression equations in stages</li>
<li>The multi-level model fits a composite of that system of equations using Maximum Likelihood Estimation</li>
</ul></li>
<li>Process
<ul>
<li>Level 1 models are fitted for each subject/unit</li>
<li>Using the estimated level 1 intercepts and slopes as outcome variables, Level 2 intercept and slope models respectively are fit</li>
<li>The errors from the Level 2 models are the random effects</li>
</ul></li>
<li>Issues
<ul>
<li>Weights every subject the same regardless of the number of repeated observations</li>
<li>Responds to missing individual slopes (i.e.&nbsp;subjects never exposed to treatment) by simply dropping those subjects</li>
<li>Does not share strength effectively across subjects</li>
</ul></li>
<li>Specification
<ul>
<li>Level 1<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (929).png" class="img-fluid">
<ul>
<li>bi is the fixed effect for subject/unit i&nbsp; and observation j (i.e.&nbsp;each subject has repeated observations)</li>
</ul></li>
<li>Level 2<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (930).png" class="img-fluid">
<ul>
<li>ui and vi are the random effects for subject/unit i</li>
<li>ai is the true (i.e.&nbsp;not estimated since no hat) mean of performance anxiety (outcome) when subject plays solos or small ensembles (LargeEns = 0)</li>
<li>bi is the true mean difference in performance anxiety (outcome) for subjecti between large ensembles and other performance types (LargeEns contrast)</li>
</ul></li>
</ul></li>
</ul></li>
<li>Multi-Level
<ul>
<li>Process
<ul>
<li>Level 1 and Level 2 equations have been combined through substitution then reduced into a composite model</li>
<li>Parameters estimated through Maximum Likelihood Estimation</li>
</ul></li>
<li>Misc
<ul>
<li>Error Distribution
<ul>
<li>Correlation between parameters is accounted for using a multivariate normal distribution estimated through a variance-covariance matrix of the error terms (aka random effects) of each Level (see <a href="https://bookdown.org/roback/bookdown-BeyondMLR/ch-multilevelintro.html#MVN">link</a> for details)</li>
</ul></li>
<li>Adding Level 1 variables to a model formula should change within-person variability (^σ2 and ^σ)
<ul>
<li>Even without adding a Level 1 variable, <em>small</em> changes could occur due to numerical estimation procedures used in likelihood-based parameter estimates</li>
</ul></li>
<li>Optimization methods
<ul>
<li>Usually very little difference between ML and REML parameter estimates</li>
<li>Restricted Maximum Likelihood (REML) is preferable when the number of parameters is large or the primary interest is obtaining estimates of model parameters, either fixed effects or variance components associated with random effects</li>
<li>Maximum Likelihood (MLE) should be used if nested fixed effects models are being compared using a likelihood ratio test, although REML is fine for nested models of random effects that have the same fixed effects.</li>
</ul></li>
<li>P-Values
<ul>
<li>Can’t be calculated because the exact distribution of the test statistics under the null hypothesis (no fixed effect) is unknown, primarily because the exact degrees of freedom is not known</li>
<li>Rule of Thumb: t-values (ratios of parameter estimates to estimated standard errors) with absolute value above 2 indicate significant evidence that a particular model parameter is different than 0</li>
<li>Packages that do report p-values of fixed effects typically using conservative assumptions, large-sample results, or approximate degrees of freedom for a t-distribution
<ul>
<li>Using <span style="color: #990000">{lmerTest}</span> will produce a summary of {lme4} with pvals for coefficients</li>
</ul></li>
<li>Parametric Bootstrap can be used to approximate the distribution of the likelihood test statistic and produce more accurate p-values by simulating data under the null hypothesis</li>
</ul></li>
<li>Model Comparison
<ul>
<li>Pseudo-R2
<ul>
<li>see below in Simple to Complex Model Building Workflow &gt;&gt;
<ul>
<li>Random Slopes and Intercepts Model (with 1 covariate)&nbsp;</li>
<li>Random Slopes and Intercepts Model (with 2 covariates)</li>
</ul></li>
</ul></li>
<li>AIC, BIC
<ul>
<li>See Simple to Complex Model Building Workflow &gt;&gt; Random Intercepts (with 2 covariates)</li>
</ul></li>
<li>Likelihood Ratio Test (LR-Test)
<ul>
<li>See Simple to Complex Model Building Workflow &gt;&gt; Random Slopes and Intercepts Model (with 3 covariates)</li>
</ul></li>
</ul></li>
</ul></li>
<li>Specification (composite model of level 1 and level 2 equations)<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (932).png" class="img-fluid">
<ul>
<li>Random Slopes and Intercepts Model (with 2 covariates) (see Model Hierarchy section)</li>
<li>Fixed Effects: α0, α1, β0 and β1</li>
<li>“ui + vi*LargeEnsij + εij” is the interesting part.
<ul>
<li>This part has all the error terms and any variables in the Level 2 equations</li>
<li>The first part is a typical regression with interaction terms.</li>
</ul></li>
</ul></li>
<li>Interpretation (
<ul>
<li>see 2-stage model for definitions for ai and bi
<ul>
<li><p>Keyboardists and Vocalists (Orchi = 0) ai = α0 + ui</p>
<pre><code>  bi \= β0 \+ vi</code></pre></li>
<li><p>Orchestral Instrumentalists (Orchi = 1) ai = (α0 + α1) + ui</p>
<pre><code>  bi \= (β0 \+ β1) + vi</code></pre></li>
</ul></li>
<li>Mean performance anxiety (outcome)
<ul>
<li>Keyboardists or vocalists (orch = 0) playing solos or small ensembles (large = 0): α0</li>
<li>Keyboardists or vocalists (orch = 0) playing large ensembles (large = 1): α0 + β0</li>
<li>Orchestral instrumentalists (orch = 1) playing solos or small ensembles (large = 0): α0 + α1α0 + α1</li>
<li>Orchestral instrumentalists (orch = 1) playing large ensembles (large = 1): α0 + α1 + β0 + β1</li>
</ul></li>
</ul></li>
<li>Model Summary (using <code>lmer4::lmer()</code> )</li>
</ul></li>
</ul>
<pre><code>&nbsp; &nbsp; Linear mixed model fit by REML ['lmerMod']&nbsp;
A)&nbsp; Formula: na ~ orch + large + orch:large + (large | id)&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; Data: music&nbsp;
B)&nbsp; REML criterion at convergence: 2987&nbsp;

B2)&nbsp; &nbsp; &nbsp; AIC&nbsp; &nbsp; &nbsp; BIC&nbsp; logLik deviance df.resid&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; 3007&nbsp; &nbsp; 3041&nbsp; &nbsp; -1496&nbsp; &nbsp; 2991&nbsp; &nbsp; &nbsp; 489&nbsp;

&nbsp; &nbsp; Random effects:&nbsp;
&nbsp; &nbsp; &nbsp; Groups&nbsp; Name&nbsp; &nbsp; &nbsp; &nbsp; Variance Std.Dev. Corr&nbsp;
C)&nbsp; id&nbsp; &nbsp; &nbsp; (Intercept)&nbsp; 5.655&nbsp; 2.378&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
D)&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; large&nbsp; &nbsp; &nbsp; &nbsp; 0.452&nbsp; 0.672&nbsp; &nbsp; -0.63&nbsp;
E)&nbsp; Residual&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 21.807&nbsp; 4.670&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
F)&nbsp; Number of obs: 497, groups:&nbsp; id, 37&nbsp;

&nbsp; &nbsp; Fixed effects:&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error t value&nbsp;
G)&nbsp; (Intercept)&nbsp; 15.930&nbsp; &nbsp; &nbsp; 0.641&nbsp; 24.83&nbsp;
H)&nbsp; orch&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1.693&nbsp; &nbsp; &nbsp; 0.945&nbsp; &nbsp; 1.79&nbsp;
I)&nbsp; large&nbsp; &nbsp; &nbsp; &nbsp; -0.911&nbsp; &nbsp; &nbsp; 0.845&nbsp; -1.08&nbsp;
J)&nbsp; orch:large&nbsp; &nbsp; -1.424&nbsp; &nbsp; &nbsp; 1.099&nbsp; -1.30</code></pre>
<ul>
<li>Definitions
<ul>
<li>A: How our multilevel model is written in R, based on the composite model formulation.</li>
<li>B: Measures of model performance. Since this model was fit using REML, this line only contains the REML criterion.</li>
<li>B2: If the model is fit with ML instead of REML, the measures of performance will contain AIC, BIC, deviance, and the log-likelihood.</li>
<li>C: Estimated variance components (^σ2u and ^σu) associated with the intercept equation in Level Two. (between-unit variability)</li>
<li>D: Estimated variance components (^σ2v and ^σv) associated with the large ensemble (large = 1) effect equation in Level Two. (also between-unit variability but just for the slope)
<ul>
<li>Also, in the “Corr” column, the estimated correlation (^ρuv) between the two Level Two error terms.</li>
</ul></li>
<li>E: Estimated variance components (^σ2 and ^σ) associated with the Level One equation. (within-unit variability)</li>
<li>F: Total number of performances where data was collected (Level One observations = 497) and total number of subjects (Level Two observations = 37).</li>
<li>G: Estimated fixed effect (^α0) for the intercept term, along with its standard error and t-value (which is the ratio of the estimated coefficient to its standard error).</li>
<li>H: Estimated fixed effect (^α1) for the orchestral instrument (orch = 1) effect, along with its standard error and t-value.</li>
<li>I: Estimated fixed effect (^β0) for the large ensemble (large = 1) effect, along with its standard error and t-value.</li>
<li>J: Estimated fixed effect (^β1) for the interaction between orchestral instruments (orch = 1) and large ensembles (large = 1), along with its standard error and t-value.</li>
</ul></li>
<li>Interpretations
<ul>
<li>Fixed effects:
<ul>
<li>^α0 = 15.9 — The estimated mean performance anxiety (outcome) for solos and small ensembles (large = 0) for keyboard players and vocalists (orch = 0) is 15.9.</li>
<li>^α1 = 1.7 — Orchestral instrumentalists (orch = 1) have an estimated mean performance anxiety (outcome) for solos and small ensembles (large = 0) which is 1.7 points higher than keyboard players and vocalists (orch = 0).</li>
<li>^β0 = −0.9 — Keyboard players and vocalists (orch = 0) have an estimated mean decrease in performance anxiety (outcome) of 0.9 points when playing in large ensembles (large = 1) instead of solos or small ensembles (large = 0).</li>
<li>^β1 = −1.4 — Orchestral instrumentalists (orch = 1) have an estimated mean decrease in performance anxiety (outcome) of 2.3 points when playing in large ensembles (large = 1) instead of solos or small ensembles (large = 0), 1.4 points greater than the mean decrease among keyboard players and vocalists (orch = 0).
<ul>
<li>He’s calculating simple slope/marginal effect (see <a href="Regression, Interactions">Regression, Interactions</a>) and choosing to use that as the interpretation for the interaction term
<ul>
<li>From ch 1 (<a href="https://bookdown.org/roback/bookdown-BeyondMLR/ch-MLRreview.html#multiple-linear-regression-with-an-interaction-term">link</a>): “we interpret the coefficient for the interaction term by comparing slopes under fast and non-fast conditions; this produces a much more understandable interpretation for a reader than attempting to interpret the -0.011 (interaction coef) directly”
<ul>
<li>fast and non-fast are levels of a main effect and a term in the interaction.</li>
</ul></li>
</ul></li>
<li>Calculation: The interaction is the difference in slopes for one interaction variable (e.g.&nbsp;large) at different values of the other interaction variable (e.g.&nbsp;orch)
<ul>
<li>Regression eq (ignoring the random effects part):
<ul>
<li>^Yi = 15.93 + 1.693orchi - 0.911large − 1.424orchi × largei</li>
</ul></li>
<li>Examining the “large” slope so only dealing with terms that contain “large”
<ul>
<li>large = 1 is reference category in the interaction that the coefficient is associated with so it remains constant</li>
</ul></li>
<li>When orch = 0 and large = 1, the slope for large is -0.911 = ^β0
<ul>
<li>- 0.911large − 1.424orchi × largei = -0.911*1 - 1.424*<strong>0</strong>*1 = -0.911 = ^β0</li>
</ul></li>
<li>When orch = 1 and large = 1, the slope for large is -2.335 (uses this one for his interpretation)
<ul>
<li>- 0.911large − 1.424orchi × largei = -0.911*1 - 1.424*<strong>1</strong>*1 = -0.911 - 1.424 = -2.335 (i.e.&nbsp;“decrease… of 2.3 points”)</li>
</ul></li>
<li>The difference in these slopes is the interaction coefficient: -2.335 - (-0.911) = -1.424</li>
</ul></li>
</ul></li>
</ul></li>
<li>Variance components
<ul>
<li>^σu = 2.4 — The estimated standard deviation of performance anxiety (outcome) for solos and small ensembles (large = 0) is 2.4 points, after controlling for instrument (orch) played.</li>
<li>^σv = 0.7 — The estimated standard deviation of differences in performance anxiety (outcome) between large ensembles (large = 1) and other performance types (large = 0) is 0.7 points, after controlling for instrument (orch) played.</li>
<li>^ρuv = −0.64 — The estimated correlation between performance anxiety scores (outcome) for solos and small ensembles (large = 0) and increases in performance anxiety (outcome) for large ensembles (large = 1) is -0.64, after controlling for instrument (orch) played.
<ul>
<li>Those subjects with higher performance anxiety scores for solos and small ensembles tend to have greater decreases in performance anxiety for large ensemble performances.</li>
</ul></li>
<li>^σ = 4.7 — The estimated standard deviation in residuals for the individual regression models is 4.7 points.</li>
</ul></li>
</ul></li>
<li>Simple to Complex Model Building Workflow (using {lme4})
<ul>
<li>Workflow should include:
<ul>
<li>fixed effects that allow one to address primary research questions</li>
<li>fixed effects that control for important covariates at all levels</li>
<li>investigation of potential interactions</li>
<li>variables that are centered where interpretations can be enhanced</li>
<li>important variance components</li>
<li>removal of unnecessary terms</li>
<li>a final model that tells a “persuasive story parsimoniously”</li>
</ul></li>
<li>Model Comparison (also see multi-level &gt;&gt; misc &gt;&gt; p-values &amp; model comparison)
<ul>
<li>LR-Test for nested models</li>
<li>AIC, BIC for unnested models</li>
<li>Consider models that involve removing terms that have t-stats &lt; |2|</li>
</ul></li>
<li>Models
<ul>
<li>Unconditional Means (aka Random Intercepts)</li>
<li>Random Slopes and Intercepts Model (with 1 covariate)</li>
<li>Random Slopes and Intercepts Model (with 2 covariates)</li>
<li>Random Intercepts (with 2 covariates)</li>
<li>Random Slopes and Intercepts Model (with 3 covariates)</li>
<li>Final Model</li>
</ul></li>
<li><strong>Unconditional Means (aka Random Intercepts)</strong>
<ul>
<li>Specification
<ul>
<li>Level 1<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (931).png" class="img-fluid">
<ul>
<li>ai is the true mean response of all observations for subjecti.</li>
</ul></li>
<li>Level 2<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (932).1.png" class="img-fluid">
<ul>
<li>each subject’s intercept is assumed to be a random value from a normal distribution centered at α0 with variance σ2u.</li>
</ul></li>
<li>Composite<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (933).png" class="img-fluid"></li>
</ul></li>
<li>Model</li>
</ul></li>
</ul></li>
</ul>
<pre><code>#Model A (Unconditional means model)
model.a &lt;- lmer(na ~ 1 + (1 | id), REML = T, data = music)
##&nbsp; Groups&nbsp; Name&nbsp; &nbsp; &nbsp; &nbsp; Variance Std.Dev.
##&nbsp; id&nbsp; &nbsp; &nbsp; (Intercept)&nbsp; 4.95&nbsp; &nbsp; 2.22&nbsp; &nbsp;
##&nbsp; Residual&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 22.46&nbsp; &nbsp; 4.74
##&nbsp; Number of Level Two groups =&nbsp; 37
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error t value
## (Intercept)&nbsp; &nbsp; 16.24&nbsp; &nbsp; 0.4279&nbsp; 37.94</code></pre>
<ul>
<li>Interpretation
<ul>
<li>^α0 = 16.2 — the estimated mean performance anxiety score across all performances and all subjects.</li>
<li>^σ2 = 22.5 — the estimated variance in within-person deviations.</li>
<li>^σ2u = 5.0 (rounded from 4.95) — the estimated variance in between-person deviations.</li>
<li>ICC<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (935).png" class="img-fluid">
<ul>
<li>18.2% of the total variability in performance anxiety scores are attributable to differences among subjects.
<ul>
<li>*For plain random intercepts models only*, you can also say this same number says that the average correlation for any pair of responses from the same individual is a moderately low .182.</li>
</ul></li>
<li>As ρ approaches 0: responses from an individual are essentially independent and accounting for the multilevel structure of the data becomes less crucial. However,</li>
<li>As ρ approaches 1: repeated observations from the same individual essentially provide no additional information and accounting for the multilevel structure becomes very important.</li>
<li>Effective Sample Size: the number of independent pieces of information we have for modeling
<ul>
<li>With ρ near 0: ESS approaches the total number of observations.</li>
<li>With ρ near 1: ESS approaches the number of subjects in the study.</li>
</ul></li>
</ul></li>
</ul></li>
<li><strong>Random Slopes and Intercepts Model (with 1 covariate)</strong>
<ul>
<li>1 - Level 1</li>
<li>Specification
<ul>
<li>Level 1<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (937).png" class="img-fluid"></li>
<li>Level 2<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (938).png" class="img-fluid"></li>
<li>Composite<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (939).png" class="img-fluid"></li>
</ul></li>
<li>Model</li>
</ul></li>
</ul>
<pre><code>model.b &lt;- lmer(na ~ large + (large | id), data = music)
##&nbsp; Groups&nbsp; Name&nbsp; &nbsp; &nbsp; &nbsp; Variance Std.Dev. Corr&nbsp;
##&nbsp; id&nbsp; &nbsp; &nbsp; (Intercept)&nbsp; 6.333&nbsp; 2.517&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; large&nbsp; &nbsp; &nbsp; &nbsp; 0.743&nbsp; 0.862&nbsp; &nbsp; -0.76
##&nbsp; Residual&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 21.771&nbsp; 4.666
##&nbsp; Number of Level Two groups =&nbsp; 37
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error t value
## (Intercept)&nbsp; 16.730&nbsp; &nbsp; 0.4908&nbsp; 34.09
## large&nbsp; &nbsp; &nbsp; &nbsp; -1.676&nbsp; &nbsp; 0.5425&nbsp; -3.09</code></pre>
<ul>
<li><p>“large” is the binary level 1 covariate, “LargeEns”</p></li>
<li><p>Interpretation</p>
<ul>
<li>^α0 = 16.7 — the mean performance anxiety level (outcome) before solos and small ensemble performances (LargeEns = 0).</li>
<li>^β0 = −1.7 — the mean decrease in performance anxiety (outcome) before large ensemble performances (LargeEns = 1).
<ul>
<li>Subjects had a performance anxiety level of 16.7 before solos and small ensembles, and their anxiety levels were 1.7 points lower, on average, before large ensembles, producing an average performance anxiety level before large ensembles of 15.0</li>
<li>Statistically significant since |t-value| &gt; 2</li>
</ul></li>
<li>^σ2 = 21.8 — the variance in within-person deviations.</li>
<li>^σ2u = 6.3 — the variance in between-person deviations in performance anxiety scores (outcome) before solos and small ensembles (LargeEns = 0).</li>
<li>^σ2v = 0.7 — the variance in between-person deviations in increases (or decreases) (slope) in performance anxiety scores (outcome) before large ensembles (LargeEns = 1).</li>
<li>^ρuv = −0.76 (Corr column)
<ul>
<li>Slopes and intercepts are negatively correlated</li>
<li>A strong negative relationship between a subject’s performance anxiety (outcome) before solos and small ensembles (LargeEns = 0) (Intercept) and their (typical) decrease in performance anxiety (Slope) before large ensembles (LargeEns = 1) .</li>
</ul></li>
</ul></li>
<li><p><strong>Pseudo-R2</strong> (Not always a reliable performance measure)<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (941).png" class="img-fluid"></p>
<ul>
<li>Where Model A: Unconditional Means; Model B: Random intercepts and slopes</li>
<li>fyi
<ul>
<li>percent decrease = (original_value - new_value) / orginal_value
<ul>
<li>pseudo-R2 uses this one</li>
<li>if negative, it’s a percent increase.</li>
</ul></li>
<li>percent increase = (new_value - original_value) / original_value
<ul>
<li>if negative, it’s a percent decrease.</li>
</ul></li>
</ul></li>
<li>Positive value means Model B is an improvement over Model A
<ul>
<li>Means the variance in Model B’s error terms is smaller than Model A’s, and therefore better fits the data. (I think)</li>
</ul></li>
<li>The estimated within-person variance ^σ2 decreased by 3.1% (from 22.5 to 21.8) from the unconditional means model</li>
<li>Implies that only 3.1% of within-person variability in performance anxiety scores can be explained by performance type</li>
<li>Values of ^σ2u and ^σ2v from Model B cannot be compared to between-person variability from Model A using pseudo-R2, since the inclusion of performance type has changed the interpretation of these values</li>
<li>Issues
<ul>
<li>“Because of the complexity of estimating fixed effects and variance components at various levels of a multilevel model, it is not unusual to encounter situations in which covariates in a Level Two equation for the intercept (for example) remain constant (while other aspects of the model change), yet the associated pseudo R-squared values differ or are negative.” (?)</li>
</ul></li>
</ul></li>
<li><p><strong>Random Slopes and Intercepts Model (with 2 covariates)</strong></p>
<ul>
<li><p>1 - Level 1; 1 - Level 2</p></li>
<li><p>Specification, Model, Interpretation (see Multi-level section above)</p>
<ul>
<li>Says the “LargeEns” effect (slope) varies across subjects/units</li>
</ul></li>
<li><p>Pseudo-R2<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (945).png" class="img-fluid"></p>
<ul>
<li><p>Model B is Random Slopes and Intercepts Model (with 1 covariate)</p></li>
<li><p>Model C is Random Slopes and Intercepts Model (with 2 covariates)</p></li>
<li><p>The addition of Level 2 variable, “Orch”, in Model C:</p>
<ul>
<li>(Top) Decreased the between-person variability in <em>mean</em> (intercept) performance anxiety (outcome) before solos and small ensembles (LargeEns = 0) by 10.6%</li>
<li>(Bottom) Decreased the between-person variability in the <em>effect</em> (slope) of large ensembles (LargeEns = 1) on performance anxiety (outcome) by 39.2%</li>
</ul></li>
</ul></li>
</ul></li>
<li><p><strong>Random Intercepts (with 2 covariates)</strong></p>
<ul>
<li>1 - Level 1; 1 - Level 2</li>
<li>Instead of assuming that the large ensemble (LargeEns) effects, after accounting for instrument played (Orch), vary by individual, we are assuming that large ensemble effect is fixed across subjects.</li>
<li>Specification
<ul>
<li>Level 1<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (937).png" class="img-fluid"></li>
<li>Level 2<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (948).png" class="img-fluid"><img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (949).png" class="img-fluid">
<ul>
<li>Only difference is the random effect/error term, <em>vi ,</em> isn’t specified</li>
</ul></li>
<li>Composite
<ul>
<li>Not given, but probably very similar to the previous model just without <em>vi</em></li>
</ul></li>
</ul></li>
<li>Model</li>
</ul></li>
</ul>
<pre><code>model.c2 &lt;- lmer(na ~ orch + large + orch:large + (1|id), data = music)
##&nbsp; Groups&nbsp; Name&nbsp; &nbsp; &nbsp; &nbsp; Variance Std.Dev.
##&nbsp; id&nbsp; &nbsp; &nbsp; (Intercept)&nbsp; 5.13&nbsp; &nbsp; 2.27&nbsp; &nbsp;
##&nbsp; Residual&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 21.88&nbsp; &nbsp; 4.68
##&nbsp; Number of Level Two groups =&nbsp; 37
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error t value
## (Intercept)&nbsp; 15.9026&nbsp; &nbsp; 0.6187&nbsp; 25.703
## orch&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1.7100&nbsp; &nbsp; 0.9131&nbsp; 1.873
## large&nbsp; &nbsp; &nbsp; &nbsp; -0.8918&nbsp; &nbsp; 0.8415&nbsp; -1.060
## orch:large&nbsp; -1.4650&nbsp; &nbsp; 1.0880&nbsp; -1.347</code></pre>
<ul>
<li>Interpretation
<ul>
<li>Same as previous model except there’s no between-units variation estimate for the slope (see previous model and Multi-level model section above)</li>
<li>Estimates are similar to the previous model’s. Largest difference seems to be the between-unit variation for the Intercept (5.65 vs 5.13)</li>
</ul></li>
<li>Comparison</li>
</ul>
<pre><code>&nbsp; &nbsp; &nbsp; &nbsp; df&nbsp; AIC
model.c&nbsp; 8 3003
model.c2&nbsp; 6 2999
&nbsp; &nbsp; &nbsp; &nbsp; df&nbsp; BIC
model.c&nbsp; 8 3037
model.c2&nbsp; 6 3025</code></pre>
<ul>
<li><p>Model C is the previous model and Model C2 is this model</p></li>
<li><p>Both criterion pick this model to predict best</p></li>
<li><p>The more complex model (e.g.&nbsp;varying intercepts <em>and</em> varying slopes) doesn’t always perform best</p></li>
<li><p><strong>Random Slopes and Intercepts Model (with 3 covariates)</strong></p>
<ul>
<li>1 - Level 1; 2 - Level 2</li>
<li>“MPQnem” has been centered (mean = 31.63)
<ul>
<li>Otherwise some interpretations would involve MPQnem = 0 when the minimum score is 11 which would make the interpretation nonsensical</li>
</ul></li>
<li>Specification
<ul>
<li>Level 1<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (937).png" class="img-fluid"></li>
<li>Level 2<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (956).png" class="img-fluid"></li>
<li>Composite<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (957).png" class="img-fluid"></li>
</ul></li>
<li>Model</li>
</ul></li>
</ul>
<pre><code>model.d &lt;- lmer(na ~ orch + mpqnem + large +
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; orch:large + mpqnem:large +
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; (large | id),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; data = music)
##&nbsp; Groups&nbsp; Name&nbsp; &nbsp; &nbsp; &nbsp; Variance Std.Dev. Corr&nbsp;
##&nbsp; id&nbsp; &nbsp; &nbsp; (Intercept)&nbsp; 3.286&nbsp; 1.813&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; large&nbsp; &nbsp; &nbsp; &nbsp; 0.557&nbsp; 0.746&nbsp; &nbsp; -0.38
##&nbsp; Residual&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 21.811&nbsp; 4.670
##&nbsp; Number of Level Two groups =&nbsp; 37
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error t value
## (Intercept)&nbsp; 16.25679&nbsp; &nbsp; 0.54756 29.6893
## orch&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1.00069&nbsp; &nbsp; 0.81713&nbsp; 1.2246
## cmpqnem&nbsp; &nbsp; &nbsp; &nbsp; 0.14823&nbsp; &nbsp; 0.03808&nbsp; 3.8925
## large&nbsp; &nbsp; &nbsp; &nbsp; -1.23484&nbsp; &nbsp; 0.84320 -1.4645
## orch:large&nbsp; &nbsp; -0.94927&nbsp; &nbsp; 1.10620 -0.8581
## cmpqnem:large -0.03018&nbsp; &nbsp; 0.05246 -0.5753</code></pre>
<ul>
<li>Interpretation
<ul>
<li>Compared to <strong>Random Slopes and Intercepts Model (with 2 covariates)</strong>:
<ul>
<li>Directions of the effects of instrument (Orch) and performance type (large) are consistent</li>
<li>Effect sizes and levels of significance are reduced because of the relative importance of the negative emotionality (mpqnem) term</li>
</ul></li>
<li>α0 = 16.26 — The estimated mean performance anxiety (outcome) for solos and small ensembles (large = 0) is 16.26 for keyboard players and vocalists (orch=0) with an average level of negative emotionality at baseline (mpqnem = 31.63)</li>
<li>^α1 = 1.00 — Orchestral instrument (orch = 1) players have an estimated mean anxiety (outcome) level before solos and small ensembles (large = 0) which is 1.00 point higher than keyboardists and vocalists (orch = 0), controlling for the effects of baseline negative emotionality.</li>
<li>^α2 = 0.15 — A one point increase in baseline negative emotionality (mpqnem = 0) is associated with an estimated 0.15 mean increase in anxiety (outcome) levels before solos and small ensembles (large = 0), after controlling for instrument (orch).</li>
<li>^β0 = −1.23 — Keyboard players and vocalists (orch = 0) with an average level of baseline negative emotionality levels (mpqnem = 31.63) have an estimated mean decrease in anxiety level (outcome) of 1.23 points before large ensemble performances (large = 1) compared to other performance types (large = 0).
<ul>
<li>See multi-level &gt;&gt; interpretation for explainer on the interaction slope interpretations</li>
</ul></li>
<li>^β1 = −0.95 — After accounting for baseline negative emotionality (mpqnem = 0), orchestral instrument players (orch = 1) have an estimated mean anxiety level (outcome) before solos and small ensembles (large = 0) which is 1.00 point higher than keyboardists and vocalists (orch = 0), while the mean anxiety (outcome) of orchestral players (orch = 1) is only .05 points higher before large ensembles (large = 1) (a difference of .95 points).
<ul>
<li>See multi-level &gt;&gt; interpretation for explainer on the interaction slope interpretations</li>
</ul></li>
<li>^β2 = −0.03 — After accounting for instrument, a one-point increase in baseline negative emotionality is associated with an estimated 0.15 mean increase in anxiety levels before solos and small ensembles, but only an estimated 0.12 increase before large ensembles (a difference of .03 points).</li>
</ul></li>
<li>LR-Test for comparing nested models</li>
</ul>
<pre><code>drop_in_dev &lt;- anova(model.d, model.c, test = "Chisq")
&nbsp; &nbsp; &nbsp; &nbsp; npar&nbsp; AIC&nbsp; BIC logLik&nbsp; dev Chisq Df&nbsp; &nbsp; &nbsp; pval
model.c&nbsp; &nbsp; 8 3007 3041&nbsp; -1496 2991&nbsp; &nbsp; NA NA&nbsp; &nbsp; &nbsp; &nbsp; NA
model.d&nbsp; 10 2996 3039&nbsp; -1488 2976 14.73&nbsp; 2 0.0006319</code></pre>
<ul>
<li><p>MLE must be used instead of REML to estimate the parameters of each model</p></li>
<li><p>“model.d” is the current and more complex model, Random Slopes and Intercepts Model (with 3 covariates)</p></li>
<li><p>“model.c” is the less complex model, Random Slopes and Intercepts Model (with 2 covariates)</p></li>
<li><p>Process</p>
<ul>
<li>The likelihood is larger (and the log-likelihood is less negative) under the larger model (Model D);</li>
<li>Chisq = 14.734 = -2 * (-1488 - (-1496))</li>
<li>Using dof = 2, signifying the number of additional terms in Model D, we obtain a p-value of .0006.</li>
</ul></li>
<li><p>A p-value &lt; 0.05 indicates the difference in log-likelihoods is significantly different from 0, and therefore the more complex model, model.d, fits the data better.</p></li>
<li><p>Note: dropping the “cmpqnem:large” term which has a t-stat &lt; |2| (-0.5753) produces a better model than model.d according the LR-test</p></li>
<li><p><strong>Final Model</strong></p>
<ul>
<li>Description
<ul>
<li>One of other valid final models</li>
<li>performance type categorical is no longer collapsed into the binary “large” ensemble/not large and is has now been collapsed into the binary, solo, not solo</li>
<li>audience categorical has been transformed to dummies: students, juried, public with “Instructor” as the reference category.</li>
<li>Varying/random slopes for previous, students, juried,&nbsp; public, and solo</li>
<li>“mpqnem” is in the “solo” level 2 equation, so the combined model has an interaction between the two in the fixed effects.</li>
</ul></li>
<li>Specification
<ul>
<li>Level 1<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (957).1.png" class="img-fluid"></li>
<li>Level 2<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (958).png" class="img-fluid">
<ul>
<li>Variance-Covariance matrix<img src="./_resources/Econometrics,_Mixed_Effects,_Frequentist.resources/Screenshot (959).png" class="img-fluid"></li>
<li>6 variance terms and 15 correlation terms at Level Two, along with 1 variance term at Level One.
<ul>
<li>The number of correlation terms is equal to the number of unique pairs among Level Two random effects</li>
</ul></li>
</ul></li>
</ul></li>
<li>Model</li>
</ul></li>
</ul>
<pre><code># Model F (One - of many - reasonable final models)
model.f &lt;- lmer(na ~ previous + students + juried +&nbsp;
&nbsp; &nbsp; public + solo + mpqpem + mpqab + orch + mpqnem +&nbsp;
&nbsp; &nbsp; mpqnem:solo + (previous + students + juried +&nbsp;
&nbsp; &nbsp; public + solo | id), REML = T, data = music)

##&nbsp; Groups&nbsp; Name&nbsp; &nbsp; &nbsp; &nbsp; Variance Std.Dev. Corr&nbsp; &nbsp; &nbsp; &nbsp;
##&nbsp; id&nbsp; &nbsp; &nbsp; (Intercept) 14.4802&nbsp; 3.805&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; previous&nbsp; &nbsp; 0.0707&nbsp; 0.266&nbsp; &nbsp; -0.65&nbsp; &nbsp; &nbsp;
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; students&nbsp; &nbsp; 8.2151&nbsp; 2.866&nbsp; &nbsp; -0.63&nbsp; 0.00
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; juried&nbsp; &nbsp; &nbsp; 18.3177&nbsp; 4.280&nbsp; &nbsp; -0.64 -0.12
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; public&nbsp; &nbsp; &nbsp; 12.8094&nbsp; 3.579&nbsp; &nbsp; -0.83&nbsp; 0.33
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; solo&nbsp; &nbsp; &nbsp; &nbsp; 0.7665&nbsp; 0.876&nbsp; &nbsp; -0.67&nbsp; 0.47
##&nbsp; Residual&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 15.2844&nbsp; 3.910&nbsp; &nbsp; &nbsp;
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
##&nbsp; 0.84&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
##&nbsp; 0.66&nbsp; 0.58&nbsp; &nbsp; &nbsp;
##&nbsp; 0.49&nbsp; 0.21&nbsp; 0.90
##&nbsp;
##&nbsp; Number of Level Two groups =&nbsp; 37
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error t value
## (Intercept)&nbsp; 8.36883&nbsp; &nbsp; 1.91369&nbsp; 4.3731
## previous&nbsp; &nbsp; -0.14303&nbsp; &nbsp; 0.06247 -2.2895
## students&nbsp; &nbsp; 3.61115&nbsp; &nbsp; 0.76796&nbsp; 4.7022
## juried&nbsp; &nbsp; &nbsp; 4.07332&nbsp; &nbsp; 1.03130&nbsp; 3.9497
## public&nbsp; &nbsp; &nbsp; 3.06453&nbsp; &nbsp; 0.89274&nbsp; 3.4327
## solo&nbsp; &nbsp; &nbsp; &nbsp; 0.51647&nbsp; &nbsp; 1.39635&nbsp; 0.3699
## mpqpem&nbsp; &nbsp; &nbsp; -0.08312&nbsp; &nbsp; 0.02408 -3.4524
## mpqab&nbsp; &nbsp; &nbsp; &nbsp; 0.20377&nbsp; &nbsp; 0.04740&nbsp; 4.2986
## orch&nbsp; &nbsp; &nbsp; &nbsp; 1.53138&nbsp; &nbsp; 0.58384&nbsp; 2.6230
## mpqnem&nbsp; &nbsp; &nbsp; 0.11465&nbsp; &nbsp; 0.03591&nbsp; 3.1930
## solo:mpqnem&nbsp; 0.08296&nbsp; &nbsp; 0.04158&nbsp; 1.9951</code></pre>
<ul>
<li>Interpretation
<ul>
<li>In general
<ul>
<li>performance anxiety (outcome) is higher when a musician is performing in front of students, a jury, or the general public rather than their instructor
<ul>
<li>“students”, “juried”, and “public” are indicator variables created from the audience categorical variable (so that “Instructor” is the reference level in this model)</li>
</ul></li>
<li>performance anxiety (outcome) is lower for each additional diary the musician previously filled out
<ul>
<li>“previous” is the number of previous diary entries filled out by that individual</li>
</ul></li>
<li>musicians with lower levels of positive emotionality (“mpqpem”) and higher levels of absorption (“mpqab”) tend to experience greater performance anxiety (outcome)</li>
<li>Those who play orchestral instruments experience (orch = 1) more performance anxiety than those who play keyboards or sing (orch = 0)</li>
</ul></li>
<li>Key terms
<ul>
<li>^α4 = 0.11 (mpqnem, fixed) — A one-point increase in baseline level of negative emotionality (mpqnem) is associated with an estimated 0.11 mean increase in performance anxiety (outcome) for musicians performing in an ensemble group (solo=0), after controlling for previous diary entries (previous), audience (dummy vars), positive emotionality (mpqpem), absorption (mpqab), and instrument (orch).</li>
<li>^ζ1 = 0.08 (solo:mpqnem, fixed) — When musicians play solos (solo = 1), a one-point increase in baseline level of negative emotionality (mpqnem) is associated with an estimated 0.19 mean increase in performance anxiety (outcome), 0.08 points (73%) higher than musicians playing in ensemble groups (solo = 0), controlling for the effects of previous diary entries (previous), audience (dummy vars), positive emotionality (mpqpem), absorption (mpqab), and instrument (orch).
<ul>
<li>See multi-level &gt;&gt; interpretation for explainer on the interaction slope interpretations</li>
</ul></li>
</ul></li>
<li>Addressing the researchers’ primary hypothesis:
<ul>
<li>After controlling for all these factors, we have significant evidence that musicians with higher levels of negative emotionality (mpqpem) experience higher levels of performance anxiety (outcome), and that this association is even more pronounced (interaction) when musicians are performing solos (solo = 1) rather than as part of an ensemble group (solo = 0).</li>
</ul></li>
</ul></li>
</ul>
<p>Chapter 9 (2-Level Longitudinal Data)</p>
<ul>
<li>Research Questions
<ul>
<li>Which factors most influence a school’s performance in Minnesota Comprehensive Assessment (MCA) testing?</li>
<li>How do the average math MCA-II scores for 6th graders enrolled in charter schools differ from scores for students who attend non-charter public schools? Do these differences persist after accounting for differences in student populations?</li>
<li>Are there differences in yearly improvement between charter and non-charter public schools?</li>
</ul></li>
<li>data answers
<ul>
<li>Within school—changes over time</li>
<li>Between schools—effects of school-specific covariates (charter or non-charter, urban or rural, percent free and reduced lunch, percent special education, and percent non-white) on 2008 math scores and rate of change between 2008 and 2010.</li>
</ul></li>
<li>Misc
<ul>
<li>Missing data is a common phenomenon in longitudinal studies</li>
</ul></li>
<li></li>
</ul>
<hr>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../qmd/econometrics-mixed-effects-bayes.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Econometrics, Mixed Effects, Bayes</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../qmd/eda-geospatial.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">EDA, Geospatial</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>