# Time Series {#sec-featred-tx .unnumbered}

## Misc {#sec-featred-ts-misc .unnumbered}

-   Also see
    -   [Forecasting, Multivariate \>\> Dynamic Factor Models](forecasting-multivariate.qmd#sec-fcast-multivar-dynfact){style="color: green"}
-   Packages
    -   [{]{style="color: #990000"}[freqdom.fda](https://cran.r-project.org/web/packages/freqdom.fda/index.html){style="color: #990000"}[}]{style="color: #990000"} ([Paper](https://academic.oup.com/jrsssb/article/77/2/319/7040632?login=false)) - Dynamic Functional Principal Components Analysis (FPCA)
    -   [{]{style="color: #990000"}[fdapace](https://cran.r-project.org/web/packages/fdapace/index.html){style="color: #990000"}[}]{style="color: #990000"} - Functional Principal Component Analysis (FPCA) for sparsely or densely sampled random trajectories and time courses, via the Principal Analysis by Conditional Estimation (PACE) algorithm

## Dynamic Mode Decomposition (DMD) {#sec-featred-ts-dmd .unnumbered}

-   Combines PCA and fourier transform
-   Supposed to handle time series better than PCA
-   Packages
    -   [{{]{style="color: goldenrod"}[pydmd](https://mathlab.github.io/PyDMD/){style="color: goldenrod"}[}}]{style="color: goldenrod"}
