# Forecasting, Decomposition

TOC


Misc



Seasonal Trend Decomposition using LOESS (STL)

* Time series get decomposed into trend-cycle (T), seasonal (S), and remainder (R) components
	* Yt = Tt + St + Rt, where t = 1,2,...,N
* LOESS smoothes a time series by:
	* Weights are applied to the neighborhood of each point which depend on the distance from the point
	* A polynomial regression is fit at each data point with points in the neighborhood as explanatory variables
* Components are additive
* Entails two recursive procedures: inner loop and outer loop
	* Each iteration updates the trend-cycle and seasonal components
	* Inner Loop is iterated until there's a robust estimate of the trend and seasonal component
	* The outer loop is only iterated if outliers exist among the data points
	* Inner Loop Procedure
		1. Detrending
			* Initially occurs by subtracting an initial trend component (?) from the original series
		2. Subseries smoothing
			* 12 monthly subseries are separated and collected
			* Each is smoothed with LOESS
			* Re-combined to create the initial seasonal component
		3. Low-Pass filtering of smoothed seasonal component
			* Seasonal component passed through a 3x12x12 moving average.
			* Result is again smoothed by LOESS (length = 13) in order to detect any trend-cycle in it.
		4. Detrending of smoothed subseries
			* Result of low-pass filtering is subtracted from seasonal component in step 2 to get the final seasonal component
		5. De-seasonalization
			* Final seasonal component is subtracted from the original series
		6. Trend smoothing
			* LOESS is applied to deseasonalized series to get the final trend component
	* Outer Loop procedure
		* Final trend and seasonal components are subtracted from the original series to get the remainder/residual series
		* The final trend and seasonal components are tested for outlier points
		* A weight is calculated and used in the next iteration of the Inner Loop to down-weight the outlier points.

