# Geospatial, Image Classification

TOC


Misc

* **(Semantic) Segmentation** - The process of labelling pixels or regions of the image
	* Essential in many applications including infrastructure planning, land cover, humanitarian crisis maps and environmental assessments.
* Resources
	* [GLCM Texture: A Tutorial](https://prism.ucalgary.ca/bitstream/handle/1880/51900/texture%20tutorial%20v%203_0%20180206.pdf)
* Types of Measures
	* texture - descriptive statistic that measures spatial relationships
		* Values cannot be transferred from one situation to another
			* e.g. you can't say, "forests always have Contrast values between .5 and .7”
		* Primarily useful in comparing one part of an image to another part
			* For multi-image comparison (e.g. mosaic):
				* the images analysed must be equivalent radiometrically, in regards to sun angle, and phenologically with regards to cyclically variable ground phenomena
	* spectral - descriptive statistics that essentially measure chemical properties of the ground objects
* Spectral and spatial are very likely to be independent data and so complement one another
* Grey Level Co-occurrence Matrix (GCLM) - Used for texture measurements. A tabulation of how often different combinations of pixel brightness values (grey levels) occur in an image.
* 
























