# Geospatial, Analysis

TOC

-   Misc
-   Terms
-   Disease Mapping

\`\` Misc

-   

Terms

-   **Catchment** - refers to the sphere of influence from which a retail location, such as a shopping center, or service, such as a hospital, is likely to draw its customers. (also see [Retail](Retail) \>\> Catchment)

Disease Mapping

-   Goals
    -   Provide accurate estimates of mortality/incidence risks or rates in space and time
    -   Unveil underlying spatial and spatio-temporal patterns
    -   Detect high-risk areas or hotspots
-   Risk estimation using metrics such as Standardized Mortality Ratio (SMR) when analyzing rare diseases or low-populated areas are highly variable over time, so it's diffficult to spot patterns and form hypotheses
    -   SMR = Observed number of cases / Expected number of cases
        -   SMR \> 1: risk is greater than the whole region under study
            -   Guessing "Expected number of cases" is the average number of cases for the whole study region
-   Statistical models smooth risks by borrowing information from spatio-temporal neighbors
    -   The smoothed gradient over the entire study region makes it easier to detect patterns and form hypotheses than highly variable, local area metric estimates (e.g. SMR in a low populated county)
-   Traditional Models
    -   Types
        -   Mixed Poisson with conditional autoregressive (CAR) priors for "space" and random walk priors for "time" that include space тип time interactions (Knorr-Held, 2000)
        -   Reduced rank multidimensional P-splines (?) (Ugarte et al, 2017)
    -   Issues
        -   Estimating the cov-var matrix becomes intractable with big data and many areas since the covariance must be estimated between each pair of areas
    -   CAR models assume the same level of spatial dependence between all areas which isn't likely.
-   [{bigDM}]{style="color: #990000"}
    -   Scalable non-stationary Bayesian models for high-dim, count data
    -   Dependencies
        -   Uses [{future}]{style="color: #990000"} for distributed computing
        -   Integrated, nested laplace approximation (INLA) method through {R-INLA}
    -   k-order neighborhood model - Breaks up local spatial or spatio-temporal domains so that estimations can distributed
        -   each area model includes k adjacent areas
