# Github Actions {#sec-git-ga .unnumbered}

## Misc {#sec-git-ga-misc .unnumbered}

-   GitHub Actions self-hosted runners provide a flexible option to run CI workloads on the infrastructure of your choice.
-   Actions
    -   [r-lib](https://github.com/r-lib/actions) - GitHub Actions for the R community
        -   setup-r - Sets up R
        -   setup-r-dependencies - Installs packages declared in `DESCRIPTION`
        -   setup-renv - Installs packages from renv lockfile
        -   setup-pandoc - Sets up pandoc
        -   setup-tinytex - Sets up LaTeX with [tinytex](https://yihui.name/tinytex)
        -   check-r-package - Runs `R CMD check` on an R package
        -   pr-fetch - Fetches changes of a PR associated with an event
        -   pr-push - Pushes changes to a PR associated with an event
        -   setup-manifest - Sets up an R project with a Posit Connect `manifest.json` file
    -   [r2u actions](https://github.com/eddelbuettel/github-actions)
        -   r-ci-setup: Adds [r-ci](https://eddelbuettel.github.io/r-ci) 'R Continuous Integration' an action running Ubuntu 22.04 aka 'jammy' or 'macos-latets' by downloading its `run.sh`
        -   r2u-setup: Adds [r2u](https://eddelbuettel.github.io/r2u) to an action running Ubuntu 22.04 aka 'jammy'
-   Tools
    -   [zizmor](https://woodruffw.github.io/zizmor/) - A static analysis tool for GitHub Actions. It can find many common security issues in typical GitHub Actions CI/CD setups.
-   SSHing into your GH Action session ([source](https://blog.davisvaughan.com/posts/2024-10-05-hell-is-debugging-someone-elses-machine/#you-can-ssh-into-github-actions))
    -   Add this to your GitHub Actions workflow file right before the failing step

        ``` yaml
        - name: Setup tmate session
          uses: mxschmitt/action-tmate@v3
          timeout-minutes: 30
        ```

    -   Check output logs of the runner. Look for this line and copy the "random string."

        ```         
        SSH: ssh <random-string>@nyc1.tmate.io
        ```

    -   Paste it into your terminal, execute, and bob's your uncle.

        -   You should end up sitting in front of a remote terminal session connected to the GitHub runner

## Triggering {#sec-git-ga-trig .unnumbered}

-   on.schedule
    -   Syntax

        -   Minute \[0,59\]
        -   Hour \[0,23\]
        -   Day of the month \[1,31\]
        -   Month of the year \[1,12\]
        -   Day of the week (\[0,6\] with 0=Sunday)

    -   [Example]{.ribbon-highlight}

        ``` yaml
        on:
          schedule:
            - cron: '30 5 * * 1,3'
            - cron: '30 5 * * 2,4'

        jobs:
          test_schedule:
            runs-on: ubuntu-latest
            steps:
              - name: Not on Monday or Wednesday
                if: github.event.schedule != '30 5 * * 1,3'
                run: echo "This step will be skipped on Monday and Wednesday"
              - name: Every time
                run: echo "This step will always run"
        ```

        -   This example triggers the workflow to run at 5:30 UTC every Monday-Thursday, but skips the Not on Monday or Wednesday step on Monday and Wednesday.
