# RStudio {#sec-ide-rstudio .unnumbered}

-   Job: Run script in the background

    ``` r
    library(rstudioapi)
    jobRunScript("wfsets_desperation_tune.R", name = "tune", exportEnv = "R_GlobalEnv")
    ```

    -   Need to look up args

    -   I think exportEnv takes the variables in your current environment and runs the script with them as inputs

    -   Shortcuts

        | Shortcut | Description |
        |--------------------------------------------|---------------------------|
        | Alt + Shift + k | Keyboard Shortcuts |
        | Ctrl + Shift + p | Command Palette |
        | Ctrl + Shift + f | Find in Files |
        | Ctrl + Alt + up/down | Multiple Cursors |
        | Ctrl + Shift + z | Reverse Undo |
        | Ctrl + Shift + a | Format highlighted code (style/linter the code) |
        | Ctrl + d | Delete current line |
        | Alt + up/down | Yank line up or down |
        | Ctrl + Alt + up/down | Copy the above line (or selected lines) down or up |
        | Ctrl + . | Go to file/function name |
        | Alt + Shift + m | Focus on Terminal |
        | F1 | Function Documentation |
        | Ctrl + Shift + F | Search for text within all files in the current project |
        | Ctrl + Shift + P | RStudio Command Search |

        -   [Customizing Shortcuts in RStudio](https://support.posit.co/hc/en-us/articles/206382178-Customizing-Keyboard-Shortcuts)

        -   {[shrtcts](https://pkg.garrickadenbuie.com/shrtcts/)} - Make anything a shortcut in RStudio
