# VS Code {#sec-ide-vsc .unnumbered}

## Misc {#sec-ide-vsc-misc .unnumbered}

-   Press "." inside any page in github to create a vscode instance that opens that file.

## Shortcuts {#sec-ide-vsc-shcts .unnumbered}

| Shortcut             | Description                                                                                                                        |
|----------------------|------------------------------------------------------------------------------------------------------------------------------------|
| CTRL + \` (backtick) | Switch focus to terminal                                                                                                           |
| CTRL+ Enter          | Insert a new line directly below, regardless of where you are in the current line                                                  |
| ALT+Shift + Up/Down  | Duplicate your current row up or down                                                                                              |
| ALT + Up/Down        | Move the current row up or down                                                                                                    |
| ALT + Shift + Right  | Hit this twice to select everything within a current bracket(this option is called smartSelect.grow , if it needs to be re-mapped) |
| CTRL + /             | Comment out the current line                                                                                                       |
| CTRL + \[ or \]      | Indent lines inward or outward                                                                                                     |

## Preferences

-   Setting shortcut for running a line of powershell code to ctrl + enter
    -   Press Ctrl+Shift+P, type "Preferences: Open Keyboard Shortcuts (JSON)", and press Enter.

    -   Add this code

        ``` json
        {
            "key": "ctrl+enter", // Replace with your preferred shortcut
            "command": "workbench.action.terminal.runSelectedText",
            "when": "editorTextFocus && editorLangId == 'powershell'"
        }
        ```
