# Positron {#sec-ide-pos .unnumbered}

## Misc

- [Website](https://positron.posit.co/), [Docs](https://positron.posit.co/welcome.html), [Jupyter Analysis Tutorial](https://positron.posit.co/tutorial-get-started-ipynb.html), [Quarto Analysis Tutorial](https://positron.posit.co/tutorial-get-started-quarto.html)

## Extensions

- [Reprex Generator for R](https://open-vsx.org/extension/jemus42/reprex-generator-for-r) - Brings the reprex package to your editor. Same functionality as reprex::reprex() or the RStudio addin to create reproducible examples for GitHub issues, Stack Overflow, or Slack.

## Shortcuts {#sec-ide-pos-short .unnumbered}

- A lot of shortcuts don't work if you're in a quarto file. (e.g. ctrl + B makes text bold instead of unhiding primary side panel)

| Shortcut | Description |
|----|----|
| Ctrl + s, then o | Open file |
| Ctrl + k, then f | Focus on console |
| Up Arrow | (in console) Copy line of code above |
| Ctrl + b | Hide/Unhide Primary Side Panel (e.g. file explorer) |
| Ctrl + Alt + Windows + n | Create new file |
| Ctrl + Alt + o | Open remote connections palette (wsl, ssh) |

## Settings {#sec-ide-pos-set .unnumbered}

- Disable Preview Tabs: `"workbench.editor.enablePreview": false,`

## Workflows

- Start [{uv}]{style="color: goldenrod"} project
  - Click New Folder, Click Python
  - Enter name of folder, Choose the directory, Select git/no git
  - Select new environment or existing environment, Select uv, Select python version
  - Add packages: `uv add numpy scikit-learn polars statsmodels`
  - Do work
- Connect to WSL2
  1.  Ctrl + Alt + o \>\> Connect to WSL
  2.  Ctrl + s, o \>\> enter path to project with WSL2 prefix (mnt) \>\> Select file
      - e.g. `/mnt/c/Users/<you>/Documents/R/Projects/deeplearning-with-r`
  3.  Do work
  4.  Ctrl + Alt + o \>\> Close remote connection
