# Residual Covariance Structures {#sec-me-rcs .unnumbered}

## Misc {#sec-me-rcs-misc .unnumbered}

-   The issue is that the way lmer works by default employs a method that won’t allow it incorporate other covariance structures(this is why it is faster and better performing than other packages).
    -   However many other packages work with lme4 model results, but not nlme, and if you aren’t going to use lme4 for mixed models you might as well go Bayesian with rstanarm or brms instead of nlme.
    -   Even prefers mgcv to nlme because of the other capabilities it provides, and the model objects created are easier to work
-   observations closer in time would be more strongly correlated than those further apart, or that the variance changes over time
-   mixed anova assumption is sphericity. Sphericity is a relaxed form of compound symmetry, where all the correlations have the same value, i.e. $\rho_1 = \rho_2 = \rho_3$, and all variances are equal.
-   residual covariance matrix structures
    -   compound symmetry
        -   Sphericity is a special case
    -   heterogeneous variance
    -   unstructured, or simply ‘symmetric,’ correlation
    -   autocorrelation
