# Bayes {#sec-me-bayes .unnumbered}

## Misc {#sec-me-bayes-misc .unnumbered}

-   Packages
    -   [{]{style="color: #990000"}[blme](https://cran.r-project.org/web/packages/blme/index.html){style="color: #990000"}[}]{style="color: #990000"} - Extends [{lme4}]{style="color: #990000"} to estimate Bayesian Linear Mixed Effects models
        -   Functions for linear and generalized linear mixed-effects models
    -   [{]{style="color: #990000"}[MCMCglmm](https://cran.r-project.org/web/packages/MCMCglmm/index.html){style="color: #990000"}[}]{style="color: #990000"} - MCMC Multivariate Generalized Linear Mixed Models
    -   [{]{style="color: #990000"}[Blend](https://cran.r-project.org/web/packages/Blend/index.html){style="color: #990000"}[}]{style="color: #990000"} - Robust Bayesian Longitudinal Regularized Semiparametric Mixed Models
        -   Can distinguish between time-varying interactions and constant-effect-only cases to avoid model misspecifications.
        -   Uses spike-and-slab priors
        -   C++ for fast, efficient MCMC
    -   [{]{style="color: #990000"}[mixedBayes](https://cran.r-project.org/web/packages/mixedBayes/index.html){style="color: #990000"}[}]{style="color: #990000"} - Bayesian Longitudinal Regularized Quantile Mixed Model
-   Resources
    -   [Bayesian Generalized Linear Mixed Effects Models for Deception Detection Analyses](https://psyarxiv.com/fdh5b/)
        -   An in-depth tutorial that uses [{brms}]{style="color: #990000"}, [{emmeans}]{style="color: #990000"}, [{parameters}]{style="color: #990000"}
