## GLMM {#sec-me-glmm .unnumbered}

## Misc {#sec-me-glmm-misc .unnumbered}

-   Packages
    -   [{]{style="color: #990000"}[glmmTMB](https://cran.r-project.org/web/packages/glmmTMB/index.html){style="color: #990000"}[}]{style="color: #990000"}
        -   Beta, Beta-Binomial, Beta-Ordinal, various extensions for Negative Binomial and Poisson, Log-Normal, Tweedie, Student-T, Gamma, Zero-Inflated, Truncated (See [Manual](https://cran.r-project.org/web/packages/glmmTMB/glmmTMB.pdf) \>\> nbinom2 for details)
        -   Currently has an experimental implementation of fixed effect priors which can be a solution to complete separation errors, singular fits, and instability ([Link](https://cran.r-project.org/web/packages/glmmTMB/vignettes/priors.html)).
        -   [Supports](https://cran.r-project.org/web/packages/glmmTMB/vignettes/parallel.html) parallelization through OpenMP but might not be supported by Mac and has significant overhead on Windows.
    -   [{]{style="color: #990000"}[GLMMadaptive](https://drizopoulos.github.io/GLMMadaptive/){style="color: #990000"}[}]{style="color: #990000"} - For binary/dichotomous data and count data with small counts and few repeated measurements, the accuracy of Laplace approximations (i.e. [{glmmTMB}]{style="color: #990000"}) is low. This package uses adaptive Gaussian quadrature rule which is the recommended, albeit more computationally intensive, approximation method for MLE in this situation.
        -   Supported Distribution Families: Student's-t, Beta, Zero-Inflated and Hurdle Poisson and Negative Binomial, Hurdle Log-Normal, Hurdle Beta, Gamma, and Censored Normal
        -   Currently no nested or crossed random effects designs
        -   Can penalize fixed effects with a student-t prior
        -   Parallelization through [{optimParallel}]{style="color: #990000"} which doesn't seem to have any OS limitations.
    -   [{]{style="color: #990000"}[glmmPen](https://cran.r-project.org/web/packages/glmmPen/index.html){style="color: #990000"}[}]{style="color: #990000"} ([Vignette](https://journal.r-project.org/articles/RJ-2023-086/))
        -   Fits high dimensional penalized generalized linear mixed models using the Monte Carlo Expectation Conditional Minimization (MCECM) algorithm.
        -   Performs variable selection on both the fixed and random effects simultaneously through MCP, SCAD, or LASSO penalties.
        -   Supports Binomial, Gaussian, and Poisson data with canonical links

## Model Equation {#sec-me-glmm-me .unnumbered}

-   Equation\
    $$
    g\{E(y_i \mid b_i)\} = \beta X_i + b_i Z_i,
    $$\
    -   $g(⋅)$: A monotonic link function
    -   $X_i$: A design matrix for the fixed effects
    -   $\beta$: Fixed effects coefficients
    -   $Z_i$: A design matrix for the random effects that's assumed to be a subset of $X_i$
    -   $b_i$: Random effects coefficients
