# Misc {#sec-py-misc .unnumbered}

## Misc {#sec-py-misc-misc .unnumbered}

-   EDA tools
    -   Misc
        -   Notes from - [3 Tools for Fast Data Profiling](https://towardsdatascience.com/3-tools-for-fast-data-profiling-5bd4e962e482) (overview)
    -   [Lux](https://lux-api.readthedocs.io/en/latest/) - Jupyter notebook widget that provides visual data profiling via existing pandas functions which makes this extremely easy to use if you are already a pandas user. It also provides recommendations to guide your analysis with the intent function. However, Lux does not give much indication as to the quality of the dataset such as providing a count of missing values for example.
    -   [{{]{style="color: goldenrod"}[pandas_profiling](https://pandas-profiling.ydata.ai/docs/master/index.html){style="color: goldenrod"}[}}]{style="color: goldenrod"} - Produces a rich data profiling report with a single line of code and displays this in line in a Juypter notebook. The report provides most elements of data profiling including descriptive statistics and data quality metrics. Pandas-profiling also integrates with Lux.
    -   [{{]{style="color: goldenrod"}[sweetviz](https://pypi.org/project/sweetviz/){style="color: goldenrod"}[}}]{style="color: goldenrod"} - Provides a comprehensive and visually attractive dashboard covering the vast majority of data profiling analysis needed. This library also provides the ability to compare two versions of the same dataset which the other tools do not provide.

## Big Data {#sec-py-misc-bd .unnumbered}

-   [{{datatable}}]{style="color: goldenrod"}
    -   Misc

        -   Resources
            -   [An Overview of Python's DataTable](https://towardsdatascience.com/an-overview-of-pythons-datatable-package-5d3a97394ee9)

    -   `fread`  for fast loading of large datasets

        ``` python
        import datatable as dt  # pip install datatable
        tps_dt = dt.fread("data/tps_september_train.csv").to_pandas()
        ```
-   For other options (e.g. Dask, Vaex, or cuDF) see this Kaggle [notebook](https://www.kaggle.com/rohanrao/tutorial-on-reading-large-datasets)
-   [{{cuDF}}]{style="color: goldenrod"}
    -   [Docs](https://docs.rapids.ai/api/cudf/stable/), Beginner's [tutorial](https://developer.nvidia.com/blog/pandas-dataframe-tutorial-beginners-guide-to-gpu-accelerated-dataframes-in-python/)
    -   Useful for extreme data sizes (e.g. 100s of billions of rows)
    -   similar to pandas syntax
-   [{{vaex}}]{style="color: goldenrod"}
    -   [Docs](https://vaex.io/docs/index.html)
-   [{{dask}}]{style="color: goldenrod"}
    -   See [MLOps \>\> Dask](mlops.qmd#sec-mlops-dask){style="color: green"}

## Functions {#sec-py-misc-func .unnumbered}

-   Suppress warnings

    ``` python
    import warnings
    warnings.filterwarnings("ignore")
    ```
