<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Science Notebook - 140&nbsp; Regression, Interactions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../qmd/regression-logistic.html" rel="next">
<link href="../qmd/regression-gaussian.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../qmd/regression-discrete.html">Regression</a></li><li class="breadcrumb-item"><a href="../qmd/regression-interactions.html"><span class="chapter-number">140</span>&nbsp; <span class="chapter-title">Regression, Interactions</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Data Science Notebook</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://ericbook.netlify.app/" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-house-fill"></i></a>
    <a href="https://github.com/ercbk/Data-Science-Notebook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Algorithms</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/algorithms-learn-to-rank.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learn-to-Rank</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/algorithms-marketing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Marketing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/algorithms-ml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">ML</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/algorithms-product.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Algorithms, Product</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/algorithms-recommendation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Algorithms, Recommendation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/anomaly-detection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Anomaly Detection</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Apache</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/apache-arrow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Apache, Arrow</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/apache-spark.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Spark</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/apis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">APIs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/aws.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">AWS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/base-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Base R</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Bayes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/bayes-priors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Bayes, priors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/bayes-reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bayes, Reporting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/bayes-troubleshooting-hmc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Bayes, Troubleshooting HMC</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/bayes-workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Bayes, Workflow</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/big-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Big Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/business-plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Business Plots</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/causal-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Causal Inference</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Classification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/cli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">CLI</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/cloud-services.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Cloud Services</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Clustering</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/clustering-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Clustering, Time Series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/clustering-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Clustering</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Code</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/code-debug.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Debugging</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/code-optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Code, Optimization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/code-snippets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Snippets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/code-style-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Code, Style Guide</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/code-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Code, Testing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/confidence-and-prediction-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Confidence &amp; Prediction Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/correlation-association-and-distance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Correlation, Association, and Distance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/cross-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Cross-Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/data.table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">data.table</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Databases</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-dbt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">DB, dbt</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-duckdb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DuckDB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-engineering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Engineering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-feature-stores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">DB, Feature Stores</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-lakes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lakes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-other.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Other</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-postgres.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">DB, postgres</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-relational.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">DB, Relational</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-warehouses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Warehouses</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/decison-intelligence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Decison Intelligence</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
 <span class="menu-text">Diagnostics</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Diagnostics, Bayes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Diagnostics, Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Diagnostics, Clustering</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-cv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Diagnostics, CV</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-dl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Diagnostics, DL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-forecasting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Diagnostics, Forecasting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Diagnostics, GLM</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-model-agnostic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Diagnostics, Model Agnostic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-nlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Diagnostics, NLP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-probabilistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Diagnostics, Probabilistic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Diagnostics, Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false">
 <span class="menu-text">Deep Learning</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-audio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">DL, Audio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">DL, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-graph.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">DL, Graph</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-image.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">DL, Image</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-tabular.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">DL, Tabular</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-training.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">DL, Training</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false">
 <span class="menu-text">Docker</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/docker-aws.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">Docker, AWS</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/docker-fundamentals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">Docker, Fundamentals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/docker-misc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">Docker, Misc</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="false">
 <span class="menu-text">Econometrics</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/econometrics-fixed-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">Econometrics, Fixed Effects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/econometrics-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Econometrics, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/econometrics-mixed-effects-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Econometrics, Mixed Effects, Bayes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/econometrics-mixed-effects-frequentist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Econometrics, Mixed Effects, Frequentist</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="false">
 <span class="menu-text">EDA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/eda-geospatial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">EDA, Geospatial</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/eda-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">EDA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/eda-multilevel-longitudinal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">EDA, Multilevel, Longitudinal</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/eda-text.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">EDA, Text</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/eda-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">EDA, Time Series</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="false">
 <span class="menu-text">Experiments</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-a_b-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">Experiments, A/B Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">Experiments, Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">Experiments, Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">Experiments, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-rct.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Experiments, RCT</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-stepped-wedge-cluster-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Experiments, Stepped Wedge Cluster Design</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/extreme-value-theory-(evt).html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Extreme Value Theory (EVT)</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="false">
 <span class="menu-text">Feature Engineering</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-engineering-embeddings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Feature Engineering, Embeddings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-engineering-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Feature Engineering, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-engineering-geospatial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Feature Engineering, Geospatial</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-engineering-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Feature Engineering, Time Series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-engineering-tokenization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Feature Engineering, Tokenization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-reduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Feature Reduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Feature Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" aria-expanded="false">
 <span class="menu-text">Forecasting</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-decomposition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">74</span>&nbsp; <span class="chapter-title">Forecasting, Decomposition</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-dl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deep Learning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-ensembling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">75</span>&nbsp; <span class="chapter-title">Forecasting, Ensembling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-functional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">76</span>&nbsp; <span class="chapter-title">Forecasting, Functional</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-hierarchical_grouped.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hierarchical/Grouped</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-ml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">77</span>&nbsp; <span class="chapter-title">Forecasting, ML</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-multivariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multivariate</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">78</span>&nbsp; <span class="chapter-title">Forecasting, Nonlinear</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-statistical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">79</span>&nbsp; <span class="chapter-title">Forecasting, Statistical</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/generalized-additive-models-(gam).html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">80</span>&nbsp; <span class="chapter-title">Generalized Additive Models (GAM)</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" aria-expanded="false">
 <span class="menu-text">Geospatial</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/geospatial-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">81</span>&nbsp; <span class="chapter-title">Geospatial, Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/geospatial-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">82</span>&nbsp; <span class="chapter-title">Geospatial, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/geospatial-image-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">Geospatial, Image Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/geospatial-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">84</span>&nbsp; <span class="chapter-title">Geospatial, Processing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" aria-expanded="false">
 <span class="menu-text">Git</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/git-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">85</span>&nbsp; <span class="chapter-title">Git, general</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/git-github-actions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">86</span>&nbsp; <span class="chapter-title">Git, Github Actions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/glossary-ds-terms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">87</span>&nbsp; <span class="chapter-title">Glossary: DS terms</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/gnu-make.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">88</span>&nbsp; <span class="chapter-title">GNU Make</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" aria-expanded="false">
 <span class="menu-text">Google</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/google-analytics-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">89</span>&nbsp; <span class="chapter-title">Google, Analytics, Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/google-analytics-reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">90</span>&nbsp; <span class="chapter-title">Google, Analytics, Reports</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/google-bigquery.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">BigQuery</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/gtable-package.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">91</span>&nbsp; <span class="chapter-title">gtable package</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/h2o-automl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">92</span>&nbsp; <span class="chapter-title">h2o automl</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/html-css.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">93</span>&nbsp; <span class="chapter-title">html, css</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/information-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">94</span>&nbsp; <span class="chapter-title">Information Theory</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/inkscape.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">95</span>&nbsp; <span class="chapter-title">Inkscape</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" aria-expanded="false">
 <span class="menu-text">Job</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/job-management-leadership.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">96</span>&nbsp; <span class="chapter-title">Job, Management / Leadership</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/job-on-the-job.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">97</span>&nbsp; <span class="chapter-title">Job, On the job</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/job-organizational-and-team-development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">98</span>&nbsp; <span class="chapter-title">Job, Organizational and Team Development</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/job-reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">99</span>&nbsp; <span class="chapter-title">Reports</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/job-search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">100</span>&nbsp; <span class="chapter-title">Job, Search</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/js.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">101</span>&nbsp; <span class="chapter-title">JS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/json.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">JSON</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/kubernetes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">102</span>&nbsp; <span class="chapter-title">Kubernetes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/latex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">LaTeX</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/loss-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">103</span>&nbsp; <span class="chapter-title">Loss Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" aria-expanded="false">
 <span class="menu-text">Mathematics</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mathematics-linear-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">104</span>&nbsp; <span class="chapter-title">Linear Algebra</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mathematics-glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossary</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mathematics-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">105</span>&nbsp; <span class="chapter-title">Mathematics, Notation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mathematics-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">106</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mathematics-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">107</span>&nbsp; <span class="chapter-title">Statistical Concepts</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/misc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Misc</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/missingness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">108</span>&nbsp; <span class="chapter-title">Missingness</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mlops.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">109</span>&nbsp; <span class="chapter-title">MLOps</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" aria-expanded="false">
 <span class="menu-text">Model Building</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-brms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">brms</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-ensembling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ensembling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-modeltime.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">modeltime</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-rstanarm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">rstanarm</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-sklearn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">sklearn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-tidymodels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">tidymodels</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/network-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Network Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" aria-expanded="false">
 <span class="menu-text">NLP</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-21" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-fine-tuning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">110</span>&nbsp; <span class="chapter-title">NLP, Fine Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">111</span>&nbsp; <span class="chapter-title">NLP, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-llms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">112</span>&nbsp; <span class="chapter-title">NLP, LLMs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-prompt-engineering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prompt Engineering</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-sentiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">113</span>&nbsp; <span class="chapter-title">NLP, Sentiment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-summarization-extraction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summarization and Extraction</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-topic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">114</span>&nbsp; <span class="chapter-title">NLP, Topic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-transformers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">115</span>&nbsp; <span class="chapter-title">NLP, Transformers</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/optimization-equation-systems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">116</span>&nbsp; <span class="chapter-title">Optimization, Equation Systems</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/outliers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Outliers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/package-development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">117</span>&nbsp; <span class="chapter-title">Package Development</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-22" aria-expanded="false">
 <span class="menu-text">Post-Hoc Analysis</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-22" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-22" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/post-hoc-analysis-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">118</span>&nbsp; <span class="chapter-title">Post-Hoc Analysis, ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/post-hoc-analysis-emmeans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">119</span>&nbsp; <span class="chapter-title">Post-Hoc Analysis, emmeans</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/post-hoc-analysis-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">120</span>&nbsp; <span class="chapter-title">Post-Hoc Analysis, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/post-hoc-analysis-mixed-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">121</span>&nbsp; <span class="chapter-title">Post-Hoc Analysis, Mixed Effects</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/privacy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">122</span>&nbsp; <span class="chapter-title">Privacy</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-23" aria-expanded="false">
 <span class="menu-text">Production</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-23" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-23" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-data-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">123</span>&nbsp; <span class="chapter-title">Production, Data Validation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-deployment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deployment</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">124</span>&nbsp; <span class="chapter-title">Production, Development</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-ml-monitoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">125</span>&nbsp; <span class="chapter-title">Production, ML Monitoring</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">126</span>&nbsp; <span class="chapter-title">Production, Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">127</span>&nbsp; <span class="chapter-title">Production, Tools</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-24" aria-expanded="false">
 <span class="menu-text">Projects</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-24" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-24" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/project-development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">128</span>&nbsp; <span class="chapter-title">Project, Development</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/project-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">129</span>&nbsp; <span class="chapter-title">Project, Management</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/project-planning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">130</span>&nbsp; <span class="chapter-title">Project, Planning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-25" aria-expanded="false">
 <span class="menu-text">Python</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-25" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-25" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-classes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">131</span>&nbsp; <span class="chapter-title">Python, Classes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">132</span>&nbsp; <span class="chapter-title">Python, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-jupyter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">133</span>&nbsp; <span class="chapter-title">Python, Jupyter</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-misc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">134</span>&nbsp; <span class="chapter-title">Python, Misc</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-numpy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">135</span>&nbsp; <span class="chapter-title">Python, Numpy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-pandas-recipes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">136</span>&nbsp; <span class="chapter-title">Python, Pandas, Recipes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-pandas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pandas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-reticulate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">137</span>&nbsp; <span class="chapter-title">Python, reticulate</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/quarto-rmarkdown.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-26" aria-expanded="true">
 <span class="menu-text">Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-26" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-26" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-discrete.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">138</span>&nbsp; <span class="chapter-title">Regression, Discrete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-gaussian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">139</span>&nbsp; <span class="chapter-title">Regression, Gaussian</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-interactions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">140</span>&nbsp; <span class="chapter-title">Regression, Interactions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">141</span>&nbsp; <span class="chapter-title">Regression, Logistic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-multivariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">142</span>&nbsp; <span class="chapter-title">Regression, Multivariate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">143</span>&nbsp; <span class="chapter-title">Regression, Nonlinear</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-ordinal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">144</span>&nbsp; <span class="chapter-title">Regression, Ordinal</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-other.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">145</span>&nbsp; <span class="chapter-title">Regression, Other</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">146</span>&nbsp; <span class="chapter-title">Regression, Quantile</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-regularized.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">147</span>&nbsp; <span class="chapter-title">Regression, Regularized</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">148</span>&nbsp; <span class="chapter-title">Regression, Survival</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/renv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">149</span>&nbsp; <span class="chapter-title">Renv</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/scraping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Scraping</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-27" aria-expanded="false">
 <span class="menu-text">Shiny</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-27" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-27" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">150</span>&nbsp; <span class="chapter-title">Shiny, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-hosting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">151</span>&nbsp; <span class="chapter-title">Shiny, Hosting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-modules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">152</span>&nbsp; <span class="chapter-title">Shiny, Modules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-production.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">153</span>&nbsp; <span class="chapter-title">Shiny, Production</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">154</span>&nbsp; <span class="chapter-title">Shiny, Python</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-ui.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">155</span>&nbsp; <span class="chapter-title">Shiny, UI</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-ui-examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">156</span>&nbsp; <span class="chapter-title">Shiny, UI Examples</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/simulation-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">157</span>&nbsp; <span class="chapter-title">Simulation, Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/slack.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">158</span>&nbsp; <span class="chapter-title">Slack</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/spreadsheets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">159</span>&nbsp; <span class="chapter-title">Spreadsheets</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/sql.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SQL</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/stochastic-processes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">160</span>&nbsp; <span class="chapter-title">Stochastic Processes</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-28" aria-expanded="false">
 <span class="menu-text">Surveys</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-28" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-28" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/surveys-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">161</span>&nbsp; <span class="chapter-title">Surveys, Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/surveys-census-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">162</span>&nbsp; <span class="chapter-title">Surveys, Census Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/surveys-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">163</span>&nbsp; <span class="chapter-title">Surveys, Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/surveys-sampling-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">164</span>&nbsp; <span class="chapter-title">Surveys, Sampling Methods</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/teaching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">165</span>&nbsp; <span class="chapter-title">Teaching</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/tidyeval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">166</span>&nbsp; <span class="chapter-title">Tidyeval</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/tuning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">167</span>&nbsp; <span class="chapter-title">Tuning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">168</span>&nbsp; <span class="chapter-title">Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/vs-code.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">169</span>&nbsp; <span class="chapter-title">VS Code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/web-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">170</span>&nbsp; <span class="chapter-title">Web Design</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">140</span>&nbsp; <span class="chapter-title">Regression, Interactions</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>TOC</p>
<ul>
<li>Misc</li>
<li>Terms</li>
<li>Processing</li>
<li>Linear
<ul>
<li>numeric:numeric
<ul>
<li>Interpretation of model effects</li>
<li>Calculate simple slopes for the IV at 3 representative values for the moderator variable</li>
<li>Plot simple slopes (coefs)</li>
<li>Test pairwise differences (contrasts) of simple slopes (coefs)</li>
<li>Test pairwise differences (contrasts) of simple effects (predicted means)</li>
</ul></li>
<li>numeric:binary
<ul>
<li>Interpretation of model effects</li>
<li>Simple slopes of numeric (IV) by each level of the categorical (moderator)</li>
<li>Simple effects at values of the moderator</li>
<li>Plotting the numeric by binary interaction</li>
</ul></li>
<li>categorical:categorical
<ul>
<li>Interpretation of model effects</li>
<li>Marginal Means for all combinations of the interaction variable levels</li>
<li>Simple Effects of the IV for all values of the moderator variable</li>
</ul></li>
</ul></li>
<li>Logistic Regression
<ul>
<li>numeric:binary
<ul>
<li>Simple slopes of numeric (IV) by each level of the categorical (moderator)</li>
<li>Simple effects at values of the IV</li>
<li>Plot simple effects
<ul>
<li>output: probabilities</li>
<li>output: log-odds (logits)</li>
</ul></li>
<li>Simple Effects at values of the moderator and adjustment variable</li>
<li>Plot simple effects and facet by values of the adjustment variable</li>
</ul></li>
</ul></li>
<li>Poisson/Neg.Binomial</li>
</ul>
<p>Misc</p>
<ul>
<li>Also see <a href="Post-Hoc Analysis, emmeans">Post-Hoc Analysis, emmeans</a> &gt;&gt; Interactions</li>
<li>Selecting values of continuous predictors to use for calculating marginal effects
<ul>
<li>Mean/Median and quantiles are popular choices</li>
<li>Check if they’re multi-modal. If so, then the mean or median may not be a useful value to use for that variable when computing marginal effects.
<ul>
<li>Modes for the distribution would be a suitable alternative.</li>
</ul></li>
<li>May also be useful to try to find intervals of values where there is no significant marginal effect.</li>
<li>Using all combinations of values in the observed data to compute individual marginal effects and then taking the average will result in the average interaction effect
<ul>
<li>Helpful in generating inferences about the whole population of interest instead of scenarios of interest or groups of interest</li>
</ul></li>
</ul></li>
<li>Gelman and Hill: “Interactions can be important. In practice, inputs that have large main effects also tend to have large interactions with other inputs. (However, small main effects do not preclude the possibility of large interactions.)”</li>
<li>We can probe or decompose interactions by asking the following research questions:
<ul>
<li>What is the predicted Y given a particular X and W? (predicted value)</li>
<li>What is relationship of X on Y at particular values of W? (simple slopes/effects)</li>
<li>Is there a difference in the relationship of X on Y for different values of W? (comparing simple slopes)</li>
</ul></li>
<li>Predictors that are uncorrelated with each other still might have interaction effects on the response variable.
<ul>
<li>Example: plant growth requires sunlight and rain. Without rain, sunlight will not increase growth and vice versa, but rain with sunlight does cause growth. This interaction effect exists even though amounts of sunlight and rain aren’t (very) correlated with each other</li>
</ul></li>
<li>Quadratic interaction <a href="https://vincentarelbundock.github.io/marginaleffects/articles/mfx02_mfx.html#example-quadratic">example</a> from <span style="color: #990000">{marginaleffects}</span> vignette</li>
<li>Dropping main effects
<ul>
<li>For the cont x cat interaction, as long as you don’t drop a categorical main effect, I don’t think it affects the model. It may or may not reparameterize the interaction coefficients so they’re the marginal effects instead contrasts. (see <a href="https://stats.oarc.ucla.edu/stata/faq/what-happens-if-you-omit-the-main-effect-in-a-regression-model-with-an-interaction/#:~:text=Is%20it%20really%20necessary%20to,were%20included%20in%20the%20model.">article</a>)
<ul>
<li>e.g.&nbsp;for <code>admit ~ dept + gender:dept</code> , the interpretation of an interaction coefficient might be something like male-female at dept A.</li>
</ul></li>
<li>Whether it’s okay to drop the categorical variable, may depend on whether the main effects are significant or not</li>
<li>Dropping a continuous main effects changes the model, so best not to ever do that in cat x cont or cont x cont interactions.</li>
<li>Harrell said in a SO post that you should never do it.
<ul>
<li>He had a link to blog post he’d written but the link was dead and there wasn’t anything in his RMS book.</li>
</ul></li>
</ul></li>
<li>False linearity assumptions of main effects can inflate apparent interaction effects because interactions may be colinear with the omitted non-linear effect</li>
<li>Interactions may also be non-linear, but shouldn’t do this w/smaller sample sizes
<ul>
<li>With smaller sample sizes, make the main effect non-linear and the interaction component linear if the non-linear relationship is present between the interaction and outcome.</li>
</ul></li>
</ul>
<p>Terms</p>
<ul>
<li><p><strong>Disordinal Interactions</strong> (aka <strong>crossover</strong> or <strong>antagonistic</strong>) - Interaction results whose lines do cross. (see fig in Ordinal Interactions)</p>
<ul>
<li>When an interaction is significant and “disordinal”, interpretation of main effects is likely to be misleading.
<ul>
<li>To determine exactly which parts of the interaction are significant, the omnibus F test must be followed by more focused tests or comparisons.</li>
</ul></li>
</ul></li>
<li><p><strong>Marginal Effects (aka Simple Slope)</strong> - partial derivatives of the regression equation with respect to each variable in the model for each unit (i.e.&nbsp;observation) in the data; average marginal effects are simply the mean of these unit-specific partial derivatives over some sample</p>
<ul>
<li>i.e.&nbsp;the slope of the prediction function, measured at a specific value of the regressor</li>
<li>In OLS regression with no interactions or higher-order term, the estimated slope coefficients are average marginal effects</li>
<li>In other cases and for generalized linear models, the coefficients are NOT marginal effects at least not on the scale of the response variable</li>
</ul></li>
<li><p><strong>Moderator Variable (MV)</strong> - a predictor that changes the relationship of the IV on the DV, and it can be continuous or discrete. Used in an interaction to estimate its effect. (also see <a href="Causal Inference">Causal Inference</a> &gt;&gt; Moderator Analysis)</p></li>
<li><p><strong>Ordinal Interactions</strong> - Interaction results whose lines do not cross<img src="./_resources/Regression,_Interactions.resources/Screenshot (829).png" class="img-fluid"></p>
<ul>
<li>This looks like an EDA plot but also see OLS &gt;&gt; Numeric:Numeric &gt;&gt; Plot Simple Slopes
<ul>
<li>Similar plot but for post-hoc analysis of a regression with an interaction</li>
</ul></li>
<li><strong>Exponential Interaction</strong>: If the lines are not parallel but one line is steeper than the other, the interaction effect will be significant (i.e.&nbsp;detected) only if there’s enough statistical power.</li>
<li>If the lines are exactly parallel, then there is no interaction effect</li>
</ul></li>
<li><p><strong>Simple Effect</strong> - when a Independent Variable interacts with a moderator variable (MV), it’s the differences in predicted values of the outcome variable at a particular levels or values of the MV</p>
<ul>
<li>The article used as reference for OLS section uses Simple Effects and Slopes interchangeably and also confuses regression coefficients with predicted values when referring to those terms throughout the tutorial. It’s confusing, so I’ve seperated the terms — one for coefficients (slopes) and another for predicted values/means (effects).</li>
<li>Each of these predicted values is a <strong>Marginal Mean</strong> (term used in <span style="color: #990000">{emmeans}</span>). So, the simple effect would be the difference (aka contrast) of marginal means.
<ul>
<li><span style="color: #990000">{marginaleffects}</span> calls these “<strong>adjusted predictions</strong>” or “marginal means” but both seem to be the same thing.</li>
</ul></li>
<li>The interaction coefficient is the difference of simple effects (aka the “difference in differences”)</li>
<li>IMO this is the value is more useful than than a contrast of simple slopes
<ul>
<li>For the contrast of simple slopes, the pvals are unhelpful and the interpretation of the results is kind of janky (see interpretation in numeric:numeric &gt;&gt; Test pairwise differences (contrasts) of simple slopes section).</li>
</ul></li>
</ul></li>
<li><p><strong>Simple Slope (aka Marginal Effect)</strong>: when a Independent Variable interacts with a moderator variable (MV), its slope at a particular level or value of the MV</p>
<ul>
<li>The main effect when an interaction is specified</li>
<li>e.g.&nbsp;Y ~ b0 + b1X1 + b2X2 + b3X1X2
<ul>
<li>Interpret simple slope, b1, as the expected change in Y after 1 unit change in X1 when X2 = 0</li>
</ul></li>
<li>The article used as reference for OLS section uses Simple Effects and Slopes interchangeably and also mixes regression coefficients with predicted values when referring to those terms throughout the tutorial. It’s confusing, so I’ve seperated the terms — one for coefficients (slopes) and another for predicted values/means (effects).</li>
</ul></li>
<li><p><strong>Spotlight Analysis</strong>: Comparison of simple slopes to see analyze the effect of the variable of interest at different levels of the moderator</p>
<ul>
<li>When an interaction is significant, choose representative values for the moderator variable and plot the simple slopes of explanatory variable to decompose the relationship between the variables involved in the interaction.</li>
<li>Made popular by Leona Aiken and Stephen West’s book Multiple Regression: Testing and Interpreting Interactions (1991).</li>
</ul></li>
</ul>
<p>Processing</p>
<ul>
<li>Center numeric variables
<ul>
<li>Centering fixes collinearity issues when creating powers and interaction terms (<a href="https://stats.stackexchange.com/a/29782">CV post</a>)
<ul>
<li>Collinearity between the created terms and the main effects</li>
</ul></li>
<li>Interpretation of effects with be at the mean of the explanatory variable
<ul>
<li>e.g.&nbsp;Since X = 0 implies , the intercept, simple slopes and simple effects are interpreted at X = mean(x).</li>
<li>Discourages unreasonable extrapolations</li>
</ul></li>
</ul></li>
</ul>
<p>Linear</p>
<ul>
<li>Misc
<ul>
<li>Notes from <a href="https://stats.oarc.ucla.edu/r/seminars/interactions-r/">Article</a></li>
<li>If the interaction term <em>is not</em> significant but the main effect <em>is</em> significant then the <em>intercepts</em> (i.e.&nbsp;response means) of at least one pair of the levels DO differ.
<ul>
<li>{emmeans::emmeans} can explore and test these types of scenarios</li>
</ul></li>
<li>factor(var) might be necessary for character variables with more than one level (to get the contrasts) but isn’t necessary for 0/1 variables (same coefficient estimates with or without).</li>
<li><code>emtrends</code> takes all differences (aka contrasts) <em>from</em> the reference group. So signs may be different from the <code>summary</code> stats values</li>
</ul></li>
<li><strong>Numeric:Numeric</strong>
<ul>
<li><span class="ribbon-highlight">Example</span>: Does the effect of workout duration (IV) on weight loss (Outcome) change due to the intensity of your workout (Moderator)?</li>
</ul></li>
</ul>
<pre><code>contcont &lt;- lm(loss ~ hours + effort + hours:effort, data=dat)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error t value Pr(&gt;|t|)&nbsp;
(Intercept)&nbsp; 7.79864&nbsp; 11.60362&nbsp; 0.672&nbsp; 0.5017&nbsp;
hours&nbsp; &nbsp; &nbsp; &nbsp; -9.37568&nbsp; &nbsp; 5.66392&nbsp; -1.655&nbsp; 0.0982 .
effort&nbsp; &nbsp; &nbsp; -0.08028&nbsp; &nbsp; 0.38465&nbsp; -0.209&nbsp; 0.8347&nbsp;
hours:effort&nbsp; 0.39335&nbsp; &nbsp; 0.18750&nbsp; 2.098&nbsp; 0.0362 *</code></pre>
<ul>
<li>(Intercept): the intercept, or the predicted outcome when Hours = 0 and Effort = 0.</li>
<li>hours (simple slope, Indepenedent Variable (IV)): for a one unit change in Hours, the predicted change in weight loss at Effort=0.</li>
<li>effort (simple slope, moderator): for a one unit change in Effort the predicted change in weight loss at Hours=0.</li>
<li>hours:effort: the change in the slope of Hours for every one unit increase in Effort (or vice versa).</li>
<li>Spotlight Analysis
<ul>
<li>Calculate representative values for the moderator variable</li>
</ul></li>
</ul>
<pre><code>eff_high &lt;- round(mean(dat$effort) + sd(dat$effort), 1) # 34.8
eff &lt;- round(mean(dat$effort), 1) # 29.7
eff_low &lt;- round(mean(dat$effort) - sd(dat$effort), 1) # 24.5</code></pre>
<ul>
<li><p>mean, +1 sd, -1&nbsp; sd</p></li>
<li><p>Calculate simple slopes for the IV at 3 representative values for the moderator variable</p></li>
</ul>
<pre><code># via [{emmeans}]{style='color: #990000'}
mylist &lt;- list(effort = c(eff_low, eff, eff_high))&nbsp;
emtrends(contcont, ~effort, var = "hours", at = mylist)
effort hours.trend&nbsp; &nbsp; SE&nbsp; df lower.CL upper.CL
24.5&nbsp; &nbsp; &nbsp; 0.261 1.352 896&nbsp; -2.392&nbsp; &nbsp; 2.91
29.7&nbsp; &nbsp; &nbsp; 2.307 0.915 896&nbsp; &nbsp; 0.511&nbsp; &nbsp; 4.10
34.8&nbsp; &nbsp; &nbsp; 4.313 1.308 896&nbsp; &nbsp; 1.745&nbsp; &nbsp; 6.88
Confidence level used: 0.95

# via [{marginaleffects}]{style='color: #990000'}
loss_grid &lt;- datagrid(effort = c(eff_high, eff, eff_low),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; model = contcont)
marginaleffects(contcont, newdata = loss_grid)
&nbsp; rowid&nbsp; &nbsp; type&nbsp; term&nbsp; &nbsp; &nbsp; dydx&nbsp; std.error&nbsp; &nbsp; hours effort
1&nbsp; &nbsp; 1 response&nbsp; hours 4.3127872 1.30838659 2.002403&nbsp; 34.8
2&nbsp; &nbsp; 2 response&nbsp; hours 2.3067185 0.91488236 2.002403&nbsp; 29.7
3&nbsp; &nbsp; 3 response&nbsp; hours 0.2613152 1.35205286 2.002403&nbsp; 24.5
4&nbsp; &nbsp; 1 response effort 0.7073625 0.08795998 2.002403&nbsp; 34.8
5&nbsp; &nbsp; 2 response effort 0.7073625 0.08795998 2.002403&nbsp; 29.7
6&nbsp; &nbsp; 3 response effort 0.7073625 0.08795999 2.002403&nbsp; 24.5
&gt;</code></pre>
<ul>
<li><span style="color: #990000">{emmeans}</span>
<ul>
<li>“contcont” is the model (e.g.&nbsp;lm)</li>
<li>“~effort” tells <code>emtrends</code> to stratify by the moderator variable “effort”</li>
<li>df is 896 because we have a sample size of 900, 3 predictors and 1 intercept (df = 900 - 3 -1 = 896)</li>
</ul></li>
<li><span style="color: #990000">{marginaleffects}</span>
<ul>
<li>Shows how “hours” is held constant at its mean when it’s simple slope is calculated at the values specified for “effort”</li>
<li>Additionally gives you the simple slope for “effort” at the mean of “hours”</li>
</ul></li>
<li>Interpretation:
<ul>
<li>When effort = 24.5, a one unit increase in hours results in a 0.26 increase in weight loss on average</li>
<li>As we increase levels of Effort, the effect of hours on weight loss seems to increase</li>
<li>Simple slope of Hours is significant only for mean Effort levels and above (i.e.&nbsp;CIs for mean and high effort don’t include 0)</li>
</ul></li>
<li>Plot simple slopes for the IV (hours)<img src="./_resources/Regression,_Interactions.resources/rinteract_fig02.png" class="img-fluid"></li>
</ul>
<pre><code># via [{emmeans}]{style='color: #990000'}
mylist &lt;- list(hours = seq(0,4, by = 0.4), effort = c(eff_low, eff, eff_high))
emmip(contcont, effort ~ hours, at = mylist, CIs = TRUE)

# via [{marginaleffects}]{style='color: #990000'}
plot_cap(contcont, condition = c("hours", "effort")) # creates it's own subset of values for effort</code></pre>
<ul>
<li>predicted outcome vs IV (newdata) by moderator (new data)
<ul>
<li>For each value of effort, the slope of the hours line at the mean of hours (for that effort level) is the value of the hours marginal effect</li>
</ul></li>
<li>Interpretation:
<ul>
<li>Suggests that hours spent exercising is only effective for weight loss if we put in more effort. (i.e.&nbsp;as effort increases so does the effect of hours)</li>
<li>At the highest levels of Effort, we achieve higher weight loss for a given time input.</li>
</ul></li>
<li>ggplot<img src="./_resources/Regression,_Interactions.resources/rinteract_fig05c.png" class="img-fluid"></li>
</ul>
<pre><code># via [{emmeans}]{style='color: #990000'}
contcontdat &lt;- emmip(contcont,effort~hours,at=mylist, CIs=TRUE, plotit=FALSE)
contcontdat$feffort &lt;- factor(contcontdat$effort)
levels(contcontdat$feffort) &lt;- c("low","med","high")
ggplot(data=contcontdat, aes(x=hours,y=yvar, color=feffort)) +
&nbsp; &nbsp; geom_line() +
&nbsp; &nbsp; geom_ribbon(aes(ymax=UCL, ymin=LCL, fill=feffort), alpha=0.4) +
&nbsp; &nbsp; labs(x="Hours", y="Weight Loss", color="Effort", fill="Effort")

# via [{marginaleffects}]{style='color: #990000'}
moose &lt;- predictions(contcont, newdata = datagrid(hours = seq(0,4, by = 0.4),&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; effort = c(eff_low, eff, eff_high),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; grid.type = "counterfactual"))
ggplot(data=moose, aes(x=hours,y=predicted, color=factor(effort))) +
&nbsp; geom_line() +
&nbsp; geom_ribbon(aes(ymax=conf.high, ymin=conf.low, fill=factor(effort)), alpha=0.4) +
&nbsp; labs(x="Hours", y="Weight Loss", color="Effort", fill="Effort")</code></pre>
<ul>
<li>Test pairwise differences (contrasts) of simple slopes</li>
</ul>
<pre><code>emtrends(contcont, pairwise ~effort, var="hours",at=mylist)
$contrasts
contrast&nbsp; &nbsp; estimate&nbsp; &nbsp; SE&nbsp; df t.ratio p.value
24.5 - 29.7&nbsp; &nbsp; -2.05 0.975 896 -2.098&nbsp; 0.0362&nbsp;
24.5 - 34.8&nbsp; &nbsp; -4.05 1.931 896 -2.098&nbsp; 0.0362&nbsp;
29.7 - 34.8&nbsp; &nbsp; -2.01 0.956 896 -2.098&nbsp; 0.0362&nbsp;
Results are averaged over the levels of: hours</code></pre>
<ul>
<li><span style="color: #990000">{marginaleffects}</span> doesn’t do this from what I can tell and IMO looking at contrasts of simple effects (next section) is a better method</li>
<li><span style="color: #990000">{emmeans}</span>
<ul>
<li>“pairwise ~effort” tells the function that we want pairwise differences of the simple slopes of var=“hours” for each level of effort specified “at=mylist”
<ul>
<li>hours not specified in mylist just the 3 values for effort</li>
</ul></li>
<li>The results are with the arg, adjust=“none”, which removes the Tukey multiple test adjustment. Removed it from the code, because it’s bad practice.</li>
</ul></li>
<li>Interpretation
<ul>
<li>A one unit change in hours when effort is high (34.8) results is 4 lbs more weight loss than a one unit change in hours when effort is low (24.5)</li>
<li>Based on the NHST, all the simple slopes are significantly different from each other</li>
</ul></li>
<li>For numeric:numeric, p-values will all be the same and identical the interaction p-value of the model (has to do with the slope formula)
<ul>
<li>Testing the simple effects contrasts (see below) may be the better option</li>
</ul></li>
<li>Test pairwise differences (contrasts) of simple effects</li>
</ul>
<pre><code># via [{emmeans}]{style='color: #990000'}
mylist &lt;- list(hours = 4, effort = c(eff_low, eff_high))
emmeans(contcont, pairwise ~ hours*effort, at=mylist)
$emmeans
hours effort emmean&nbsp; SE&nbsp; df lower.CL upper.CL
&nbsp; &nbsp; 4&nbsp; 24.5&nbsp; 6.88 2.79 896&nbsp; &nbsp; &nbsp; 1.4&nbsp; &nbsp; 12.4
&nbsp; &nbsp; 4&nbsp; 34.8&nbsp; 22.26 2.68 896&nbsp; &nbsp; 17.0&nbsp; &nbsp; 27.5
Confidence level used: 0.95&nbsp;
$contrasts
contrast&nbsp; &nbsp; &nbsp; &nbsp; estimate&nbsp; SE&nbsp; df t.ratio p.value
4,24.5 - 4,34.8&nbsp; &nbsp; -15.4 3.97 896 -3.871&nbsp; 0.0001


# via [{marginaleffects}]{style='color: #990000'}
comparisons(contcont,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; variables = list(effort = c(eff_low, eff_high)),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; newdata = datagrid(hours = 4)) %&gt;%&nbsp;
&nbsp; tidy()
&nbsp; rowid&nbsp; &nbsp; type&nbsp; &nbsp; &nbsp; &nbsp; term contrast_effort comparison std.error statistic&nbsp; &nbsp; &nbsp; p.value conf.low conf.high&nbsp; effort hours
1&nbsp; &nbsp; 1 response interaction&nbsp; &nbsp; 34.8 - 24.5&nbsp; 15.37904&nbsp; 3.97295&nbsp; 3.870938 0.0001084175 7.592203&nbsp; 23.16588 29.65922&nbsp; &nbsp; 4

# alternate (difference in results could be due to rounding of eff_low, eff_high)
comparisons(contcont,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; variables = list(effort = "2sd"),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; newdata = datagrid(hours = 4,&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; grid.type = "counterfactual")) %&gt;%&nbsp;
&nbsp; tidy()
&nbsp; &nbsp; &nbsp; type&nbsp; &nbsp; &nbsp; &nbsp; term&nbsp; &nbsp; contrast_effort estimate std.error statistic&nbsp; &nbsp; &nbsp; p.value conf.low conf.high
1 response interaction (x + sd) - (x - sd) 15.35743&nbsp; 3.967367&nbsp; 3.870938 0.0001084175 7.581535&nbsp; 23.13333</code></pre>
<ul>
<li>One reason to look at the tests for the predicted means contrast instead of the slope contrasts is the constant p-value across slope contrasts (see above)</li>
<li>If hours isn’t specified emmeans holds hours at the sample mean.
<ul>
<li>Using <span style="color: #990000">{marginaleffects}</span> and holding hours at sample mean (and probably every other variable in the model), <code>comparisons(contcont, variables = list(effort = "2sd")) %&gt;% tidy()</code></li>
</ul></li>
<li>Specification
<ul>
<li>hours has a fixed value and the moderator is allowed to vary between high and low effort</li>
<li>emmeans
<ul>
<li>“pairwise ~ hours*effort to tell the function that we want pairwise contrasts of each distinct combination of Hours and Effort specified at=mylist</li>
</ul></li>
<li>marginaleffects
<ul>
<li>effort = “2d” says compare (effort + 1 sd) to (effort - 1 sd)</li>
<li>grid.type = “counterfactual” because there is no observation in the data with hours = 4</li>
</ul></li>
</ul></li>
<li>Interpretation
<ul>
<li>Based on the NHST, the difference between the predicted means of high and low effort are significantly different from each other when hours = 4</li>
<li>After 4 hours of exercise, high effort (34.8) will result in about 15 pounds more weight loss than low effort (24.5) on average.</li>
</ul></li>
<li><strong>Numeric:Binary</strong>
<ul>
<li>The change in the slope of the numeric (IV) after a change from the reference level to the other level in the binary (Moderator)
<ul>
<li>Note that this value is an additional change to the effect of the numeric (i.e when binary = 1, the effect = numeric effect + interaction effect)</li>
</ul></li>
<li>Significant means that the factor variable does increase/decrease the effect of the numeric variable</li>
<li><span class="ribbon-highlight">Example</span>: Does the effect of workout duration (IV) on weight loss (Outcome) change because you are a male or female (Moderator)?</li>
</ul></li>
</ul>
<pre><code>dat &lt;- dat %&gt;%&nbsp;
&nbsp; mutate(gender = factor(gender, labels = c("male", "female")) # male = 1, female = 2,
&nbsp; &nbsp; &nbsp; &nbsp; gender = relevel(gender, ref = "female")
&nbsp; )
contcat &lt;- lm(loss ~ hours * gender, data=dat)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error t value Pr(&gt;|t|)&nbsp;
(Intercept)&nbsp; &nbsp; &nbsp; &nbsp; 3.335&nbsp; &nbsp; &nbsp; 2.731&nbsp; 1.221&nbsp; &nbsp; 0.222&nbsp;
hours&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3.315&nbsp; &nbsp; &nbsp; 1.332&nbsp; 2.489&nbsp; &nbsp; 0.013 *
gendermale&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 3.571&nbsp; &nbsp; &nbsp; 3.915&nbsp; 0.912&nbsp; &nbsp; 0.362&nbsp;
hours:gendermale&nbsp; -1.724&nbsp; &nbsp; &nbsp; 1.898&nbsp; -0.908&nbsp; &nbsp; 0.364</code></pre>
<ul>
<li>Intercept (b0): predicted weight loss when Hours = 0 in the reference group of Gender, which is&nbsp; females.</li>
<li>hours (b1, Independent Variable): the simple slope of Hours for the reference group&nbsp; (e.g.&nbsp;females).
<ul>
<li>hours simple slope for males is b1 + b3 or <code>emtrends(contcat, ~ gender, var="hours")</code> will give both simple slopes</li>
</ul></li>
<li>gendermale (b2, Moderator) (reference group: female): the difference in the effect of being male compared to female at hours = 0.</li>
<li>hours:gendermale (b3): the difference in the simple slopes of Hours for males to Hours for females.
<ul>
<li><code>emtrends</code> can also give the <code>summary</code> stats for the interaction (sign different in this case, since difference is <em>from</em> the reference group, female)</li>
</ul></li>
</ul>
<pre><code>hours_slope &lt;- emtrends(contcat, pairwise ~ gender, var="hours")
hours_slope$contrasts
contrast&nbsp; &nbsp; &nbsp; estimate&nbsp; SE&nbsp; df t.ratio p.value
female - male&nbsp; &nbsp; 1.72 1.9 896 0.908&nbsp; 0.3639</code></pre>
<ul>
<li>Simple slopes of numeric (IV) by each level of the categorical (moderator)</li>
</ul>
<pre><code># via [{emmeans}]{style='color: #990000'}
emtrends(contcat, ~ gender, var="hours")
gender hours.trend&nbsp; SE&nbsp; df lower.CL upper.CL
female&nbsp; &nbsp; &nbsp; &nbsp; 3.32 1.33 896&nbsp; &nbsp; 0.702&nbsp; &nbsp; 5.93
male&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 1.59 1.35 896&nbsp; -1.063&nbsp; &nbsp; 4.25

# via [{marginaleffects}]{style='color: #990000'}
marginaleffects(contcat) %&gt;%
&nbsp; &nbsp; tidy(by = "gender")
&nbsp; &nbsp; &nbsp; type&nbsp; term&nbsp; &nbsp; &nbsp; contrast gender&nbsp; estimate std.error statistic&nbsp; &nbsp; p.value&nbsp; conf.low conf.high
1 response&nbsp; hours&nbsp; &nbsp; &nbsp; &nbsp; dY/dX&nbsp; male 1.59113665 1.3523002 1.1766150 0.23934921 -1.0593230&nbsp; 4.241596
2 response&nbsp; hours&nbsp; &nbsp; &nbsp; &nbsp; dY/dX female 3.31506746 1.3316491 2.4894453 0.01279426&nbsp; 0.7050833&nbsp; 5.925052
3 response gender male - female&nbsp; male 0.09616813 0.9382760 0.1024945 0.91836418 -1.7428191&nbsp; 1.935155
4 response gender male - female female 0.14194405 0.9382968 0.1512784 0.87975610 -1.6970840&nbsp; 1.980972</code></pre>
<ul>
<li><span style="color: #990000">{emmeans}</span>
<ul>
<li>~gender says obtain separate estimates for females and males</li>
<li>var=“hours” says obtain simple slopes (or trends) for hours</li>
</ul></li>
<li><span style="color: #990000">{marginaleffects}</span>
<ul>
<li>Can also use <code>summary(by = "gender")</code></li>
</ul></li>
<li>Interpretation
<ul>
<li>hours by female is the same as the model coefficient above.
<ul>
<li>See model interpretation above</li>
</ul></li>
</ul></li>
<li>Simple effects at values of the moderator</li>
</ul>
<pre><code># via [{emmeans}]{style='color: #990000'}
mylist &lt;- list(hours=c(0,2,4),gender=c("male","female"))
emcontcat&nbsp; &lt;- emmeans(contcat, ~ hours*gender, at=mylist)
contrast(emcontcat, "pairwise",by="hours")
hours = 0:
contrast&nbsp; &nbsp; &nbsp; estimate&nbsp; &nbsp; SE&nbsp; df t.ratio p.value
male - female&nbsp; &nbsp; 3.571 3.915 896&nbsp; 0.912&nbsp; 0.3619&nbsp;
hours = 2:
contrast&nbsp; &nbsp; &nbsp; estimate&nbsp; &nbsp; SE&nbsp; df t.ratio p.value
male - female&nbsp; &nbsp; 0.123 0.938 896&nbsp; 0.131&nbsp; 0.8955&nbsp;
hours = 4:
contrast&nbsp; &nbsp; &nbsp; estimate&nbsp; &nbsp; SE&nbsp; df t.ratio p.value
male - female&nbsp; -3.325 3.905 896 -0.851&nbsp; 0.3948

# via [{marginaleffects}]{style='color: #990000'}
comparisons(contcat,
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; variables = "gender",
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; newdata = datagrid(hours = c(0, 2, 4)))
&nbsp; rowid&nbsp; &nbsp; type&nbsp; &nbsp; &nbsp; &nbsp; term contrast_gender comparison std.error&nbsp; statistic&nbsp; p.value&nbsp; conf.low conf.high gender hours
1&nbsp; &nbsp; 1 response interaction&nbsp; male - female&nbsp; 3.5710607&nbsp; 3.914762&nbsp; 0.9122038 0.3616614&nbsp; -4.101731 11.243853&nbsp; male&nbsp; &nbsp; 0
2&nbsp; &nbsp; 2 response interaction&nbsp; male - female&nbsp; 0.1231991&nbsp; 0.937961&nbsp; 0.1313478 0.8955002&nbsp; -1.715171&nbsp; 1.961569&nbsp; male&nbsp; &nbsp; 2
3&nbsp; &nbsp; 3 response interaction&nbsp; male - female -3.3246625&nbsp; 3.905153 -0.8513527 0.3945735 -10.978622&nbsp; 4.329297&nbsp; male&nbsp; &nbsp; 4</code></pre>
<ul>
<li>The moderator is now “hours”</li>
<li>Note that output for hours = 0, the effect 3.571 matches the b2 coefficient</li>
<li>Interpretation
<ul>
<li>as Hours increases, the male versus female difference becomes more negative (females are losing more weight than males)</li>
</ul></li>
<li>Plotting the numeric by binary interaction<img src="./_resources/Regression,_Interactions.resources/rinteract_fig03b.png" class="img-fluid"></li>
</ul>
<pre><code># via [{emmeans}]{style='color: #990000'}
mylist &lt;- list(hours=seq(0,4,by=0.4),gender=c("female","male"))
emmip(contcat, gender ~hours, at=mylist,CIs=TRUE)</code></pre>
<ul>
<li>For ggplot, see Numeric:Numeric &gt;&gt; Plot Simple Slopes for IV section (should be similar code)</li>
<li>Interpretation
<ul>
<li>Although it looks like there’s a cross-over interaction, the large overlap in confidence intervals suggests that the slope of Hours is not different between males and females
<ul>
<li>Confirmed by looking at the standard error of the interaction coefficient (1.898) is large relative to the absolute value of the coefficient itself (1.724)</li>
</ul></li>
</ul></li>
<li><strong>Categorical:Categorical</strong>
<ul>
<li>From <span style="color: #990000">{marginaleffects}</span> Contrasts vignette, “Since derivatives are only properly defined for continuous variables, we cannot use them to interpret the effects of changes in categorical variables. For this, we turn to contrasts between adjusted predictions (aka Simple Effects).”
<ul>
<li>i.e.&nbsp;contrasts of simple slopes aren’t possible</li>
</ul></li>
<li>2x3 cat:cat interaction</li>
<li><span class="ribbon-highlight">Example</span>: Do males and females (IV) lose weight (Outcome) differently depending on the type of exercise (Moderator) they engage in?</li>
</ul></li>
</ul>
<pre><code>dat &lt;- dat %&gt;%&nbsp;
&nbsp; mutate(gender = factor(gender, labels = c("male", "female")),
&nbsp; &nbsp; &nbsp; &nbsp; gender = relevel(gender, ref = "female"),
&nbsp; &nbsp; &nbsp; &nbsp; prog = factor(prog, labels = c("jog","swim","read")),
&nbsp; &nbsp; &nbsp; &nbsp; prog = relevel(prog, ref="read")
&nbsp; )
catcat &lt;- lm(loss ~ gender * prog, data = dat)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error t value Pr(&gt;|t|)&nbsp; &nbsp;
(Intercept)&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -3.6201&nbsp; &nbsp; 0.5322&nbsp; -6.802 1.89e-11 ***
gendermale&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -0.3355&nbsp; &nbsp; 0.7527&nbsp; -0.446&nbsp; &nbsp; 0.656&nbsp; &nbsp;
progjog&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 7.9088&nbsp; &nbsp; 0.7527&nbsp; 10.507&nbsp; &lt; 2e-16 ***
progswim&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 32.7378&nbsp; &nbsp; 0.7527&nbsp; 43.494&nbsp; &lt; 2e-16 ***
gendermale:progjog&nbsp; &nbsp; 7.8188&nbsp; &nbsp; 1.0645&nbsp; 7.345 4.63e-13 ***
gendermale:progswim&nbsp; -6.2599&nbsp; &nbsp; 1.0645&nbsp; -5.881 5.77e-09 ***</code></pre>
<ul>
<li>Description
<ul>
<li>Intercept (b0): the intercept, or the predicted weight loss when gendermale = 0, progjog = 0, and progswim = 0
<ul>
<li>i.e.&nbsp;the intercept for females in the reading program</li>
</ul></li>
<li>gendermale (b1): the simple effect of males when progjog = 0 and progswim = 0
<ul>
<li>i.e.&nbsp;the&nbsp; male – female weight loss in the reading group</li>
</ul></li>
<li>progjog (b2): the simple effect of jogging when gendermale = 0
<ul>
<li>i.e.&nbsp;the difference in weight loss between jogging versus reading for females</li>
</ul></li>
<li>progswim (b3):&nbsp; the simple effect of swimming when gendermale = 0
<ul>
<li>i.e.&nbsp;the difference in weight loss between swimming versus reading for females</li>
</ul></li>
<li>gendermale:progjog (b4): the male effect (male – female) in the jogging condition versus the male effect in the reading condition.
<ul>
<li>Also, the jogging effect (jogging – reading) for males versus the jogging effect for females.</li>
</ul></li>
<li>gendermale:progswim (b5): the male effect (male – female) in the swimming condition versus the male effect in the reading condition.
<ul>
<li>Also, the swimming effect (swimming- reading) for males versus the swimming effect for females.</li>
</ul></li>
<li>Gender is the independent variable</li>
<li>Prog is the moderator</li>
<li>reference groups
<ul>
<li>prog == read</li>
<li>gender == female</li>
</ul></li>
<li>b1 + b4: is the simple slope of gender == males in the prog == jogging group.</li>
<li>b1 + b5: is the simple slope of gender == males in the prog == swimming group.</li>
</ul></li>
<li>Marginal Means for all combinations of the interaction variable levels</li>
</ul>
<pre><code># via [{emmeans}]{style='color: #990000'}
emcatcat &lt;- emmeans(catcat, ~ gender*prog)
gender prog emmean&nbsp; &nbsp; SE&nbsp; df lower.CL upper.CL
female read&nbsp; -3.62 0.532 894&nbsp; &nbsp; -4.66&nbsp; &nbsp; -2.58
male&nbsp; read&nbsp; -3.96 0.532 894&nbsp; &nbsp; -5.00&nbsp; &nbsp; -2.91
female jog&nbsp; &nbsp; 4.29 0.532 894&nbsp; &nbsp; 3.24&nbsp; &nbsp; 5.33
male&nbsp; jog&nbsp; 11.77 0.532 894&nbsp; &nbsp; 10.73&nbsp; &nbsp; 12.82
female swim&nbsp; 29.12 0.532 894&nbsp; &nbsp; 28.07&nbsp; &nbsp; 30.16
male&nbsp; swim&nbsp; 22.52 0.532 894&nbsp; &nbsp; 21.48&nbsp; &nbsp; 23.57

# via [{marginaleffects}]{style='color: #990000'}
predictions(catcat, variables = c("gender", "prog"))
&nbsp; rowid&nbsp; &nbsp; type predicted std.error&nbsp; conf.low conf.high gender prog
1&nbsp; &nbsp; 1 response 11.772028 0.5322428 10.727437 12.816619&nbsp; male&nbsp; jog
2&nbsp; &nbsp; 2 response 22.522383 0.5322428 21.477792 23.566974&nbsp; male swim
3&nbsp; &nbsp; 3 response -3.955606 0.5322428 -5.000197 -2.911016&nbsp; male read
4&nbsp; &nbsp; 4 response&nbsp; 4.288681 0.5322428&nbsp; 3.244091&nbsp; 5.333272 female&nbsp; jog
5&nbsp; &nbsp; 5 response 29.117691 0.5322428 28.073100 30.162282 female swim
6&nbsp; &nbsp; 6 response -3.620149 0.5322428 -4.664740 -2.575559 female read</code></pre>
<ul>
<li>Marginal means generated using the regression coefficients<img src="./_resources/Regression,_Interactions.resources/Screenshot (833).png" class="img-fluid">
<ul>
<li>Kinda weird. Since these are predicted means (i.e.&nbsp;outcome values), I wouldn’t have thought they could be generated by the model coefficients. ¯\_(ツ)_/¯</li>
</ul></li>
<li>Interpretation
<ul>
<li>females in the reading program have an estimated weight gain of 3.62 pounds</li>
<li>males in the swimming program have an average weight loss of 22.52 pounds</li>
</ul></li>
<li>Simple Effects of the IV for all values of the moderator variable</li>
</ul>
<pre><code># via [{emmeans}]{style='color: #990000'}
contrast(emcatcat, "revpairwise", by="prog") # see above code chunk for emcatcat
prog = read:
contrast&nbsp; &nbsp; &nbsp; estimate&nbsp; &nbsp; SE&nbsp; df t.ratio p.value
male - female&nbsp; -0.335 0.753 894 -0.446&nbsp; 0.6559&nbsp;
prog = jog:
contrast&nbsp; &nbsp; &nbsp; estimate&nbsp; &nbsp; SE&nbsp; df t.ratio p.value
male - female&nbsp; &nbsp; 7.483 0.753 894&nbsp; 9.942&nbsp; &lt;.0001&nbsp;
prog = swim:
contrast&nbsp; &nbsp; &nbsp; estimate&nbsp; &nbsp; SE&nbsp; df t.ratio p.value
male - female&nbsp; -6.595 0.753 894 -8.762&nbsp; &lt;.0001

# via [{marginaleffects}]{style='color: #990000'}
comparisons(catcat,&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; variables = "gender",&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; newdata = datagrid(prog = c("read", "jog", "swim")))
&nbsp; rowid&nbsp; &nbsp; type&nbsp; &nbsp; &nbsp; &nbsp; term contrast_gender comparison std.error&nbsp; statistic&nbsp; &nbsp; &nbsp; p.value&nbsp; conf.low conf.high gender prog
1&nbsp; &nbsp; 1 response interaction&nbsp; male - female -0.3354569 0.7527049 -0.4456686 6.558367e-01 -1.810731&nbsp; 1.139818&nbsp; male read
2&nbsp; &nbsp; 2 response interaction&nbsp; male - female&nbsp; 7.4833463 0.7527049&nbsp; 9.9419388 2.734522e-23&nbsp; 6.008072&nbsp; 8.958621&nbsp; male&nbsp; jog
3&nbsp; &nbsp; 3 response interaction&nbsp; male - female -6.5953078 0.7527049 -8.7621425 1.915739e-18 -8.070582 -5.120033&nbsp; male swim</code></pre>
<ul>
<li><span style="color: #990000">{emmeans}</span>
<ul>
<li>“revpairwise” rather than “pairwise” because by default the reference group (female) would come first</li>
<li>The results are with the arg, adjust=“none”, which removes the Tukey multiple test adjustment. Removed it from the code, because it’s bad practice.</li>
</ul></li>
<li>Interpretation
<ul>
<li>male effect for jogging and swimming are significant at the 0.05 level (with no adjustment of p-values), but not for the reading condition.</li>
<li>males lose more weight in the jogging condition (positive) but females lose more weight in the swimming condition (negative)</li>
</ul></li>
<li>Plotting the categorical by categorical interaction
<ul>
<li><span style="color: #990000">{emmeans}</span> <code>emmip(catcat, prog ~ gender,CIs=TRUE)</code><img src="./_resources/Regression,_Interactions.resources/rinteract_fig04b.png" class="img-fluid"></li>
<li>{ggplot2}<img src="./_resources/Regression,_Interactions.resources/rinteract_fig06b.png" class="img-fluid"></li>
</ul></li>
</ul>
<pre><code>catcatdat &lt;- emmip(catcat, gender ~ prog, CIs=TRUE, plotit=FALSE)
&nbsp; gender prog&nbsp; &nbsp; &nbsp; yvar&nbsp; &nbsp; &nbsp; &nbsp; SE&nbsp; df&nbsp; &nbsp; &nbsp; LCL&nbsp; &nbsp; &nbsp; UCL&nbsp; tvar xvar
1 female read -3.620149 0.5322428 894 -4.664740 -2.575559 female read
2&nbsp; male read -3.955606 0.5322428 894 -5.000197 -2.911016&nbsp; male read
3 female&nbsp; jog&nbsp; 4.288681 0.5322428 894&nbsp; 3.244091&nbsp; 5.333272 female&nbsp; jog
4&nbsp; male&nbsp; jog 11.772028 0.5322428 894 10.727437 12.816619&nbsp; male&nbsp; jog
5 female swim 29.117691 0.5322428 894 28.073100 30.162282 female swim
6&nbsp; male swim 22.522383 0.5322428 894 21.477792 23.566974&nbsp; male swim

# via [{marginaleffects}]{style='color: #990000'}
predictions(catcat, variables = c("gender", "prog"))

ggplot(data=catcatdat, aes(x=prog,y=yvar, fill=gender)) +
&nbsp; &nbsp; geom_bar(stat="identity",position="dodge") +
&nbsp; &nbsp; geom_errorbar(position=position_dodge(.9),width=.25, aes(ymax=UCL, ymin=LCL),alpha=0.3)
&nbsp; &nbsp; labs(x="Program", y="Weight Loss", fill="Gender")</code></pre>
<ul>
<li>I think I like the emmeans plot better</li>
<li>Values come from the Marginal Means for all combinations of the interaction variable levels section above</li>
</ul>
<p>Logistic Regression</p>
<ul>
<li>* categorical:categorical and numeric:numeric should be should be similar to analysis for binary:numeric and the code/analysis in the OLS section *
<ul>
<li>For more details on these other interaction types see the article linked below</li>
</ul></li>
<li>Misc
<ul>
<li>Notes from
<ul>
<li><a href="https://stats.oarc.ucla.edu/stata/faq/how-can-i-understand-a-categorical-by-continuous-interaction-in-logistic-regression-stata-11/">How Can I Understand A Categorical By Continuous Interaction In Logistic Regression</a></li>
<li><a href="https://stats.oarc.ucla.edu/stata/seminars/deciphering-interactions-in-logistic-regression-2/">Deciphering Interactions In Logistic Regression</a>
<ul>
<li>See this article for numeric:numeric, cat:cat</li>
</ul></li>
</ul></li>
<li>Also see
<ul>
<li><a href="Regression, Logistic">Regression, Logistic</a> &gt;&gt; Marginal Effects</li>
<li><a href="Post-Hoc Analysis, emmeans">Post-Hoc Analysis, emmeans</a> &gt;&gt; Logistic Regression</li>
</ul></li>
<li>Reminder: OR significance is being different from 1 and log odds ratios (logits) significance is being different from 0</li>
<li>Although the interaction is quantified appropriately by the interaction coefficient when interpreting effects on the scale of log-odds or log-counts, the interaction effect will not reduce to the coefficient of the the interaction coefficient when describing effects on the natural response scale (i.e.&nbsp;probabilities, counts) because of the inverse-link transformation.
<ul>
<li>In order to get e.g.&nbsp;probabilities, the inverse-link function must be used, and this complicates the derivatives of the marginal effect calculation. The chain rule must be appied. This means the interaction <em>effect</em> is no longer equivalent to the interaction <em>coefficient.</em></li>
<li>Therefore, effects or contrasts are differences in marginal effects rather than coefficients
<ul>
<li>Interaction effects represent change in a marginal effect of one predictor for a change in another predictoreraction effects represent change in a marg</li>
</ul></li>
</ul></li>
<li>Standard errors of point estimate values of interaction <em>effects</em> (as well as their corresponding statistical significance) may also vary as a function of the predictors.</li>
<li>Need to decide whether the interaction is to be conceptualized in terms of log odds (logits) or odds ratios or probability
<ul>
<li>An interaction that is significant in log odds may not be significant in terms of probability or vice versa
<ul>
<li>Even if they do agree, the p-values do not have the be the same. (see below, binary:numeric &gt;&gt; Simple Effects &gt;&gt; second example &gt;&gt; probabilities)</li>
</ul></li>
</ul></li>
</ul></li>
<li><strong>binary:numeric</strong>
<ul>
<li><span class="ribbon-highlight">Example</span>:
<ul>
<li>Description</li>
</ul></li>
</ul></li>
</ul>
<pre><code>dat_clean &lt;- dat %&gt;%&nbsp;
&nbsp; mutate(f = factor(f, labels = c("female", "male")))
concat &lt;- glm(y ~ f*s, family = binomial, data = dat_clean)
summary(concat)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error z value Pr(&gt;|z|)&nbsp; &nbsp;
(Intercept) -9.25380&nbsp; &nbsp; 1.94189&nbsp; -4.765 1.89e-06 ***
fmale&nbsp; &nbsp; &nbsp; &nbsp; 5.78681&nbsp; &nbsp; 2.30252&nbsp; 2.513&nbsp; 0.0120 *&nbsp;
s&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 0.17734&nbsp; &nbsp; 0.03644&nbsp; 4.867 1.13e-06 ***
fmale:s&nbsp; &nbsp; -0.08955&nbsp; &nbsp; 0.04392&nbsp; -2.039&nbsp; 0.0414 *</code></pre>
<ul>
<li><p>y: binary outcome</p></li>
<li><p>s (IV): continuous variable</p></li>
<li><p>f (moderator):&nbsp; gender variable with female as the reference</p></li>
<li><p>cv1: continuous adjustment variable</p></li>
<li><p>Simple slopes of numeric (IV) by each level of the categorical (moderator)</p></li>
</ul>
<pre><code># via [{marginaleffects}]{style='color: #990000'}
marginaleffects(concat, variables = "s") %&gt;%
&nbsp; &nbsp; tidy(by = "f")
&nbsp; &nbsp; &nbsp; type term&nbsp; &nbsp; &nbsp; f&nbsp; estimate&nbsp; std.error statistic&nbsp; &nbsp; p.value&nbsp; conf.low&nbsp; conf.high
1 response&nbsp; &nbsp; s&nbsp; male 0.01473352 0.003237072&nbsp; 4.551498 5.32654e-06 0.00838898 0.02107807
2 response&nbsp; &nbsp; s female 0.02569069 0.001750066 14.679842 0.00000e+00 0.02226062 0.02912075</code></pre>
<ul>
<li>Interpetation
<ul>
<li>Increasing s by 1 unit given that the person is male will result in around a 1% increase on average in the probability of the event, y.</li>
</ul></li>
<li>Simple effects at values of the IV</li>
</ul>
<pre><code># via [{marginaleffects}]{style='color: #990000'}
comp &lt;- comparisons(concat2,&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; variables = "f",&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; newdata = datagrid(s = seq(20, 70, by = 2)))
head(comp)
&nbsp; rowid&nbsp; &nbsp; type&nbsp; &nbsp; &nbsp; &nbsp; term&nbsp; &nbsp; contrast_f comparison&nbsp; std.error statistic&nbsp; &nbsp; p.value&nbsp; &nbsp; conf.low conf.high&nbsp; &nbsp; f&nbsp; s
1&nbsp; &nbsp; 1 response interaction male - female&nbsp; 0.1496878 0.09871431&nbsp; 1.516374 0.12942480 -0.043788674 0.3431643 male 20
2&nbsp; &nbsp; 2 response interaction male - female&nbsp; 0.1724472 0.10430544&nbsp; 1.653291 0.09827172 -0.031987695 0.3768821 male 22
3&nbsp; &nbsp; 3 response interaction male - female&nbsp; 0.1975119 0.10886095&nbsp; 1.814351 0.06962377 -0.015851616 0.4108755 male 24
4&nbsp; &nbsp; 4 response interaction male - female&nbsp; 0.2246979 0.11209440&nbsp; 2.004542 0.04501204&nbsp; 0.004996938 0.4443989 male 26
5&nbsp; &nbsp; 5 response interaction male - female&nbsp; 0.2536377 0.11376972&nbsp; 2.229395 0.02578761&nbsp; 0.030653136 0.4766222 male 28
6&nbsp; &nbsp; 6 response interaction male - female&nbsp; 0.2837288 0.11375073&nbsp; 2.494303 0.01262048&nbsp; 0.060781436 0.5066761 male 30</code></pre>
<ul>
<li>Shows the predicted value contrasts for the moderator at different values of the independent variable.
<ul>
<li>“concat2” model defined in “Simple Effects at values of the moderator and adjustment variable” (see below)</li>
</ul></li>
<li>For <code>comparisons</code> , the default is type = “response” so the output is probabilities. (type = “link” for log-ORs aka logits)</li>
<li>Interpretation
<ul>
<li>For s = 26, 28, and 30, there is substantial evidence that there are differences in male and female probabilites of the event, y.</li>
</ul></li>
<li><span class="ribbon-highlight">Example</span>: (<a href="https://cscu.cornell.edu/wp-content/uploads/84_lgsint.pdf">article</a>)
<ul>
<li>Description
<ul>
<li>lowbwt: binary outcome, low birthweight = 1</li>
<li>age (IV): continuous, age of the mother</li>
<li>ftv (moderator): binary, whether or not the mother made frequent physician visits during the first trimester of pregnancy</li>
</ul></li>
<li>Simple Effects: Odds Ratios<img src="./_resources/Regression,_Interactions.resources/Screenshot (837).png" class="img-fluid">
<ul>
<li>ORftv is the odds-ratio contrast of (ftv = 1) - (ftv = 0) at the specified age of the mother</li>
<li>Interpretation
<ul>
<li>a mother at the age of 30 who visits the physician frequently has 0.174 times the odds of having a low birth weight baby as compared to those of the same age who don’t visit the doctor frequently</li>
<li>For women whose ages are between 17 and 24, the 95% confidence intervals of the odds ratios include the null value of 1, so we do not have strong evidence of an association between frequent doctor visits and low birth weight for that age range.</li>
<li>For mothers aged 25 years and older, the odds of having a low birth weight baby significantly decrease if the mother frequently visits her physician.</li>
</ul></li>
</ul></li>
<li>Simple Effects: Probabilities<img src="./_resources/Regression,_Interactions.resources/Screenshot (838).png" class="img-fluid">
<ul>
<li>“Difference in probability” is the probability contrast of (ftv = 1) - (ftv = 0) at the specified age of the mother</li>
<li>Note that the results agree with the OR results, but the pvals are different
<ul>
<li>So it’s probably possible that in terms of “significance,” you could get different conclusions based on the metric used.</li>
</ul></li>
<li>Interpretation
<ul>
<li>For young mothers (less than 24 years old), we do not have strong evidence of an association between low birth weight and frequent physician visits.</li>
<li>For mothers aged 25 years and older, we reject the null hypothesis of no difference in probability between those with frequent physician visits and those without.</li>
<li>Overall, the difference between the probability of low birth weight comparing those with frequent visits to those without increases as the mother’s age increases.</li>
</ul></li>
</ul></li>
</ul></li>
<li>Plot the simple effects<img src="./_resources/Regression,_Interactions.resources/image.png" class="img-fluid"></li>
</ul>
<pre><code>ggplot(comp, aes(x = s, y = comparison)) +&nbsp;
&nbsp; geom_line() +
&nbsp; geom_ribbon(aes(ymax=conf.high, ymin=conf.low), alpha=0.4) +&nbsp;
&nbsp; geom_hline(yintercept=0, linetype="dashed") +
&nbsp; labs(title = "Male-Female Difference", y="Probability Contrast")</code></pre>
<ul>
<li><span style="color: #990000">{marginaleffects}</span>
<ul>
<li>You change the <code>comparisons</code> (see above) type arg to “type = link” to get log-ORs (aka logits) instead of probabilities and then plot<img src="./_resources/Regression,_Interactions.resources/image.2.png" class="img-fluid"></li>
</ul></li>
<li>Interpretation
<ul>
<li>The difference in probabilities for male and females is statistically significant between values of “s” approximately between 28 to 55.</li>
</ul></li>
<li>Simple Effects at values of the moderator and adjustment variable</li>
</ul>
<pre><code>concat2 &lt;- glm(y ~ f*s + cv1, family = binomial, data = dat_clean)
comp2 &lt;- comparisons(concat2,&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; variables = "f",&nbsp;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; newdata = datagrid(s = seq(20, 70, by = 2),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; cv1 = c(40, 50, 60)))
head(comp2)
&nbsp; rowid&nbsp; &nbsp; type&nbsp; &nbsp; &nbsp; &nbsp; term&nbsp; &nbsp; contrast_f comparison&nbsp; std.error statistic&nbsp; &nbsp; &nbsp; p.value&nbsp; &nbsp; conf.low conf.high&nbsp; &nbsp; f&nbsp; s cv1
1&nbsp; &nbsp; 1 response interaction male - female&nbsp; 0.2307214 0.15001700&nbsp; 1.537968 1.240564e-01 -0.06330656 0.5247493 male 20&nbsp; 40
2&nbsp; &nbsp; 2 response interaction male - female&nbsp; 0.6603841 0.20879886&nbsp; 3.162777 1.562722e-03&nbsp; 0.25114590 1.0696224 male 20&nbsp; 50
3&nbsp; &nbsp; 3 response interaction male - female&nbsp; 0.9135206 0.07865839 11.613773 3.507873e-31&nbsp; 0.75935304 1.0676882 male 20&nbsp; 60
4&nbsp; &nbsp; 4 response interaction male - female&nbsp; 0.2361502 0.14294726&nbsp; 1.652009 9.853270e-02 -0.04402131 0.5163217 male 22&nbsp; 40
5&nbsp; &nbsp; 5 response interaction male - female&nbsp; 0.6663811 0.19447902&nbsp; 3.426494 6.114278e-04&nbsp; 0.28520927 1.0475530 male 22&nbsp; 50
6&nbsp; &nbsp; 6 response interaction male - female&nbsp; 0.9097497 0.07571970 12.014703 2.974362e-33&nbsp; 0.76134178 1.0581575 male 22&nbsp; 60</code></pre>
<ul>
<li>Plot simple effects and facet by values of the adjustment variable<img src="./_resources/Regression,_Interactions.resources/image.1.png" class="img-fluid"></li>
</ul>
<pre><code>ggplot(comp2, aes(x = s, y = comparison, group = factor(cv1))) +&nbsp;
&nbsp; geom_line() +
&nbsp; geom_ribbon(aes(ymax=conf.high, ymin=conf.low), alpha=0.4) +&nbsp;
&nbsp; geom_hline(yintercept=0, linetype="dashed") +
&nbsp; facet_wrap(~ cv1) +
&nbsp; labs(title = "Male-Female Difference", y="Probability Contrast")</code></pre>
<ul>
<li>Interpretation
<ul>
<li>It seems clear from looking at the three graphs that the male-female difference in probability increases as cv1 increases except for high values of s.</li>
</ul></li>
</ul>
<p>Poisson/Neg.Binomial</p>
<ul>
<li>Misc
<ul>
<li>Notes from Paper <a href="https://psyarxiv.com/th94c/">Interpreting interaction effects in generalized linear models of nonlinear probabilities and counts</a></li>
<li>Although the interaction is quantified appropriately by the interaction coefficient when interpreting effects on the scale of log-odds or log-counts, the interaction effect will not reduce to the coefficient of the the interaction coefficient when describing effects on the natural response scale (i.e.&nbsp;probabilities, counts) because of the inverse-link transformation.
<ul>
<li>In order to get e.g.&nbsp;probabilities, the inverse-link function must be used, and this complicates the derivatives of the marginal effect calculation. The chain rule must be appied. This means the interaction <em>effect</em> is no longer equivalent to the interaction <em>coefficient.</em></li>
<li>Therefore, effects or contrasts are differences in marginal effects rather than coefficients
<ul>
<li>Interaction effects represent change in a marginal effect of one predictor for a change in another predictoreraction effects represent change in a marg</li>
</ul></li>
</ul></li>
<li>Standard errors of point estimate values of interaction <em>effects</em> (as well as their corresponding statistical significance) may also vary as a function of the predictors.</li>
</ul></li>
<li>Types
<ul>
<li>Both Continuous — the rate-of-change in the marginal effect of one predictor given a change in another predictor
<ul>
<li>Also, the amount the effect of x1 on E[Y|x] changes for every one-unit increase in x2 (and vice versa), holding all else constant.</li>
</ul></li>
<li>Continuous : Discrete — difference in the marginal effect of the continuous predictor between two selected values of the discrete predictor
<ul>
<li>Example: Poisson outcome (population)<img src="./_resources/Regression,_Interactions.resources/Screenshot (1200).png" class="img-fluid">
<ul>
<li>x1 is continuous, x2 is continuous, x3 is binary (e.g.&nbsp;sex where female = 1).</li>
<li>The interaction effect, γ213,&nbsp; of x1x3 is the difference between the marginal effect of x1 for females versus males</li>
<li>Note that x2 is included in the effect calculation for an interaction it isn’t part of</li>
<li>Specific values for x1 and x2 must be chosen to the calculate the value of the effect<img src="./_resources/Regression,_Interactions.resources/Screenshot (1202).png" class="img-fluid">
<ul>
<li>For x2, the 25th, 50th, 75th quartiles are used and x1 would be held at one value of substantive interest (e.g.&nbsp;mean)</li>
<li>Standard errors via delta method for all 3 values can be computed along with p-values</li>
</ul></li>
<li>Visual<img src="./_resources/Regression,_Interactions.resources/image.3.png" class="img-fluid">
<ul>
<li>x2 is held at its mean, and various values of x1 are used</li>
<li>Interpretation: the expected population (count of Y) is larger among females than males across all values of x1 with x2 held at its mean.</li>
</ul></li>
</ul></li>
</ul></li>
<li>Discrete : Discrete — the difference between the model evaluated at two categories of one variable (a, b) minus the difference in this model evaluated at two categories of another variable (c, d) (aka discrete double difference)</li>
</ul></li>
</ul>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../qmd/regression-gaussian.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">139</span>&nbsp; <span class="chapter-title">Regression, Gaussian</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../qmd/regression-logistic.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">141</span>&nbsp; <span class="chapter-title">Regression, Logistic</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>