# Multivariate {#sec-reg-multivar .unnumbered}

## Misc {#sec-reg-multivar-misc .unnumbered}

-   Also see [Mathematics, Statistics \>\> Multivariate](mathematics-statistics.qmd#sec-math-statc-desc-multiv){style="color: green"}
-   Packages
    -   [Compositional]{.underline}
        -   [{]{style="color: #990000"}[Compositional](https://cran.r-project.org/web/packages/Compositional/index.html){style="color: #990000"}[}]{style="color: #990000"} - **Compositional** Data Analysis
            -   Regression, classification, contour plots, hypothesis testing and fitting of distributions for compositional data are some of the functions included.
            -   Functions for percentages (or proportions) are also included.
        -   [{]{style="color: #990000"}[CompositionalSR](https://cran.r-project.org/web/packages/CompositionalSR/index.html){style="color: #990000"}[}]{style="color: #990000"} - **Spatial Regression** Models with **Compositional** Data
        -   [{]{style="color: #990000"}[DirichletRF](https://cran.r-project.org/web/packages/DirichletRF/index.html){style="color: #990000"}[}]{style="color: #990000"} - "**Dirichlet Random Forest**" Implementation of the Dirichlet Random Forest algorithm for **compositional** response data
        -   [{]{style="color: #990000"}[ZIDM](https://github.com/mkoslovsky/ZIDM){style="color: #990000"}[}]{style="color: #990000"} ([Vignette](https://github.com/mkoslovsky/ZIDM/blob/main/vignettes/ZIDM-vignette.pdf), [Paper](https://arxiv.org/abs/2302.12283)) - Model for Multivariate **Compositional Count** Data
            -   Uses a **Bayesian Zero-Inflated Dirichlet**-Multinomial Regression model
    -   [General]{.underline}
        -   [{]{style="color: #990000"}[BCD](https://cran.r-project.org/web/packages/BCD/index.html){style="color: #990000"}[}]{style="color: #990000"} - Implementation of **bivariate** binomial, geometric, and Poisson distributions based on conditional specifications.
        -   [{]{style="color: #990000"}[heplots](https://friendly.github.io/heplots/){style="color: #990000"}[}]{style="color: #990000"} - Mostly for **visualizing hypothesis tests** in multivariate linear models (“MLM” = {MANOVA, multivariate multiple regression, MANCOVA, and repeated measures designs}).
            -   Also provides other tools for analysis and graphical display of MLMs.
            -   `robmlm` fits a multivariate linear model by robust regression using a simple M estimator that down-weights observations with large residuals
            -   **Robust** estimation for multivariate linear models (MLMs) using iteratively reweighted least squares (IRLS)
        -   [{]{style="color: #990000"}[kernreg](https://cran.r-project.org/web/packages/kernreg/index.html){style="color: #990000"}[}]{style="color: #990000"} - Fast implementation of Nadaraya-Watson **kernel regression** for either univariate or multivariate responses, with one or more bandwidths. K-fold cross-validation is also performed
        -   [{]{style="color: #990000"}[randomForestSRC](https://www.randomforestsrc.org/){style="color: #990000"}[}]{style="color: #990000"} - Fast Unified **Random Forests** for Survival, Regression, and Classification (RF-SRC)
            -   New Mahalanobis splitting rule for correlated real-valued outcomes in multivariate regression settings
        -   [{]{style="color: #990000"}[savvyPR](https://cran.r-project.org/web/packages/savvyPR/index.html){style="color: #990000"}[}]{style="color: #990000"} - Implements the Savvy Parity Regression methodology for multivariate linear regression analysis
            -   Solves an optimization problem that balances the contribution of each predictor variable to ensure estimation stability in the presence of **multicollinearity**
            -   Supports two distinct parameterization methods, a Budget-based approach that allocates a fixed loss contribution to each predictor, and a Target-based approach (t-tuning) that utilizes a relative elasticity weight for the response variable.
        -   [{]{style="color: #990000"}[savvySh](https://cran.r-project.org/web/packages/savvySh/index.html){style="color: #990000"}[}]{style="color: #990000"} - Implements a suite of **shrinkage** estimators for multivariate linear regression to improve estimation stability and predictive accuracy
            -   Includes the Stein estimator, Diagonal Shrinkage, the general Shrinkage estimator (solving a Sylvester equation), and Slab Regression (Simple and Generalized)
-   Papers
    -   [Soil texture prediction with Bayesian generalized additive models for spatial compositional data](https://arxiv.org/abs/2508.07708)
        -   Uses [{brms}]{style="color: #990000"} to fit a Bayesian GAM to model a compositional response. Model includes variables for elevation, slope, longitude, latitude. Includes R^2^ metrics for compositional modeling.

## Generalized Joint Regression Modelling (GJRM) {#sec-reg-multivar-gjrm .unnumbered}

-   A flexible statistical framework that generalizes classical regression models to jointly model multiple responses (or multi-response), potentially of different types, while accounting for dependencies between them.
    -   It is particularly useful when you have multiple outcomes (e.g., continuous, binary, count data) that may influence each other.
    -   Handles nonlinear associations between the reponse variables
-   Packages
    -   [{]{style="color: #990000"}[GJRM](https://cran.r-project.org/web/packages/GJRM/index.html){style="color: #990000"}[}]{style="color: #990000"} - Routines for fitting various joint (and univariate) regression models, with several types of covariate effects, in the presence of equations' errors association, endogeneity, non-random sample selection or partial observability.
-   Papers
    -   [Copula based joint regression models for correlated data: an analysis in the bivariate case](https://arxiv.org/abs/2410.11892)
-   Comparison to a Gaussian Multivariate Regression Model
    -   Allows for more flexible marginal distributions, not limited to normal distributions.
    -   Dependence Structure
        -   Multivariate regression models the correlation between responses using a multivariate normal distribution, which implies a linear association.
        -   GJRM uses copulas to model the dependence structure, allowing for more complex, non-linear associations between responses.
    -   Flexibility
        -   In multivariate regression with splines, the same spline structure is typically applied across all response variables..
        -   In GJRM, each marginal can have its own unique non-linear structure, potentially using different splines or smoothing approaches for each response variable.
    -   GJRM allows different link functions for each marginal distribution, accommodating various types of responses and not just continuous responses
    -   GJRM can handle mixed types of responses (e.g., a combination of continuous, binary, and count data) in a single model.
-   Steps
    -   First stage: Models each marginal distribution separately, allowing for different distributions and link functions for each response.
    -   Second stage: Combines these marginals using a copula function to create the joint distribution.
