<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Data Science Notebook - 160&nbsp; Regression, Ordinal</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../qmd/regression-other.html" rel="next">
<link href="../qmd/regression-nonlinear.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../qmd/regression-discrete.html">Regression</a></li><li class="breadcrumb-item"><a href="../qmd/regression-ordinal.html"><span class="chapter-number">160</span>&nbsp; <span class="chapter-title">Regression, Ordinal</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Data Science Notebook</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://ericbook.netlify.app/" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-house-fill"></i></a>
    <a href="https://github.com/ercbk/Data-Science-Notebook" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Algorithms</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/algorithms-learn-to-rank.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learn-to-Rank</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/algorithms-marketing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Marketing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/algorithms-ml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Algorithms, ML</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/algorithms-product.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Algorithms, Product</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/algorithms-recommendation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Algorithms, Recommendation</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/anomaly-detection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Anomaly Detection</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Apache</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/apache-arrow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Apache, Arrow</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/apache-spark.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Apache, Spark</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/apis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">APIs</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/aws.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">AWS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/base-r.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Base R</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Bayes</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/bayes-priors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Bayes, priors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/bayes-reporting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Bayes, Reporting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/bayes-troubleshooting-hmc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Bayes, Troubleshooting HMC</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/bayes-workflow.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Bayes, Workflow</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/big-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Big Data</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/business-plots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Business Plots</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/causal-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Causal Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Classification</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/cli.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">CLI</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/cloud-services.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Cloud Services</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Clustering</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/clustering-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Clustering, Time Series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/clustering-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Clustering</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Code</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/code-optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Code, Optimization</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/code-snippets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Snippets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/code-style-guide.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Code, Style Guide</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/code-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Code, Testing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/confidence-and-prediction-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Confidence &amp; Prediction Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/correlation-association-and-distance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Correlation, Association, and Distance</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/cross-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Cross-Validation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/data.table.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">data.table</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Databases</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-dbt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">DB, dbt</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-duckdb.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DuckDB</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-engineering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">DB, Engineering</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-feature-stores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">DB, Feature Stores</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-postgres.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">DB, postgres</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-relational.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">DB, Relational</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/db-warehouses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">DB, Warehouses</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/decison-intelligence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Decison Intelligence</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
 <span class="menu-text">Diagnostics</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Diagnostics, Bayes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">35</span>&nbsp; <span class="chapter-title">Diagnostics, Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">36</span>&nbsp; <span class="chapter-title">Diagnostics, Clustering</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-cv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">37</span>&nbsp; <span class="chapter-title">Diagnostics, CV</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-dl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">38</span>&nbsp; <span class="chapter-title">Diagnostics, DL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-forecasting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">39</span>&nbsp; <span class="chapter-title">Diagnostics, Forecasting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">40</span>&nbsp; <span class="chapter-title">Diagnostics, GLM</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-model-agnostic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">41</span>&nbsp; <span class="chapter-title">Diagnostics, Model Agnostic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-nlp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">42</span>&nbsp; <span class="chapter-title">Diagnostics, NLP</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-probabilistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">43</span>&nbsp; <span class="chapter-title">Diagnostics, Probabilistic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/diagnostics-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">44</span>&nbsp; <span class="chapter-title">Diagnostics, Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">45</span>&nbsp; <span class="chapter-title">Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false">
 <span class="menu-text">Deep Learning</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-audio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">46</span>&nbsp; <span class="chapter-title">DL, Audio</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">47</span>&nbsp; <span class="chapter-title">DL, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-graph.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">48</span>&nbsp; <span class="chapter-title">DL, Graph</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-image.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">49</span>&nbsp; <span class="chapter-title">DL, Image</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-tabular.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">50</span>&nbsp; <span class="chapter-title">DL, Tabular</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/dl-training.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">51</span>&nbsp; <span class="chapter-title">DL, Training</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false">
 <span class="menu-text">Docker</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/docker-aws.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">52</span>&nbsp; <span class="chapter-title">Docker, AWS</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/docker-fundamentals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">53</span>&nbsp; <span class="chapter-title">Docker, Fundamentals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/docker-misc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">54</span>&nbsp; <span class="chapter-title">Docker, Misc</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="false">
 <span class="menu-text">Econometrics</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/econometrics-fixed-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">55</span>&nbsp; <span class="chapter-title">Econometrics, Fixed Effects</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/econometrics-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">56</span>&nbsp; <span class="chapter-title">Econometrics, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/econometrics-mixed-effects-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">57</span>&nbsp; <span class="chapter-title">Econometrics, Mixed Effects, Bayes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/econometrics-mixed-effects-frequentist.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">58</span>&nbsp; <span class="chapter-title">Econometrics, Mixed Effects, Frequentist</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="false">
 <span class="menu-text">EDA</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-11" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-11" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/eda-geospatial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">59</span>&nbsp; <span class="chapter-title">EDA, Geospatial</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/eda-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">60</span>&nbsp; <span class="chapter-title">EDA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/eda-multilevel-longitudinal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">61</span>&nbsp; <span class="chapter-title">EDA, Multilevel, Longitudinal</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/eda-text.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">62</span>&nbsp; <span class="chapter-title">EDA, Text</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/eda-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">63</span>&nbsp; <span class="chapter-title">EDA, Time Series</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="false">
 <span class="menu-text">Experiments</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-12" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-12" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-a_b-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">64</span>&nbsp; <span class="chapter-title">Experiments, A/B Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">65</span>&nbsp; <span class="chapter-title">Experiments, Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">66</span>&nbsp; <span class="chapter-title">Experiments, Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">67</span>&nbsp; <span class="chapter-title">Experiments, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-rct.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">68</span>&nbsp; <span class="chapter-title">Experiments, RCT</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/experiments-stepped-wedge-cluster-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">69</span>&nbsp; <span class="chapter-title">Experiments, Stepped Wedge Cluster Design</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/extreme-value-theory-(evt).html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">70</span>&nbsp; <span class="chapter-title">Extreme Value Theory (EVT)</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="false">
 <span class="menu-text">Feature Engineering</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-13" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-13" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-engineering-embeddings.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">71</span>&nbsp; <span class="chapter-title">Feature Engineering, Embeddings</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-engineering-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">72</span>&nbsp; <span class="chapter-title">Feature Engineering, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-engineering-geospatial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">73</span>&nbsp; <span class="chapter-title">Feature Engineering, Geospatial</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-engineering-time-series.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">74</span>&nbsp; <span class="chapter-title">Feature Engineering, Time Series</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-engineering-tokenization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">75</span>&nbsp; <span class="chapter-title">Feature Engineering, Tokenization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-reduction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">76</span>&nbsp; <span class="chapter-title">Feature Reduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/feature-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">77</span>&nbsp; <span class="chapter-title">Feature Selection</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" aria-expanded="false">
 <span class="menu-text">Forecasting</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-14" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-14" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-decomposition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">78</span>&nbsp; <span class="chapter-title">Forecasting, Decomposition</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-dl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">79</span>&nbsp; <span class="chapter-title">Forecasting, DL</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-ensembling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">80</span>&nbsp; <span class="chapter-title">Forecasting, Ensembling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-functional.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">81</span>&nbsp; <span class="chapter-title">Forecasting, Functional</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-hierarchical_grouped.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">82</span>&nbsp; <span class="chapter-title">Forecasting, Hierarchical/Grouped</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-ml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">83</span>&nbsp; <span class="chapter-title">Forecasting, ML</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-multivariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">84</span>&nbsp; <span class="chapter-title">Forecasting, Multivariate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">85</span>&nbsp; <span class="chapter-title">Forecasting, Nonlinear</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/forecasting-statistical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">86</span>&nbsp; <span class="chapter-title">Forecasting, Statistical</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/generalized-additive-models-(gam).html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">87</span>&nbsp; <span class="chapter-title">Generalized Additive Models (GAM)</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" aria-expanded="false">
 <span class="menu-text">Geospatial</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-15" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-15" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/geospatial-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">88</span>&nbsp; <span class="chapter-title">Geospatial, Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/geospatial-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">89</span>&nbsp; <span class="chapter-title">Geospatial, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/geospatial-image-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">90</span>&nbsp; <span class="chapter-title">Geospatial, Image Classification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/geospatial-processing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">91</span>&nbsp; <span class="chapter-title">Geospatial, Processing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" aria-expanded="false">
 <span class="menu-text">Git</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-16" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-16" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/git-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">92</span>&nbsp; <span class="chapter-title">Git, general</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/git-github-actions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">93</span>&nbsp; <span class="chapter-title">Git, Github Actions</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/glossary-ds-terms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">94</span>&nbsp; <span class="chapter-title">Glossary: DS terms</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/gnu-make.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">95</span>&nbsp; <span class="chapter-title">GNU Make</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" aria-expanded="false">
 <span class="menu-text">Google</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-17" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-17" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/google-analytics-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">96</span>&nbsp; <span class="chapter-title">Google, Analytics, Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/google-analytics-reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">97</span>&nbsp; <span class="chapter-title">Google, Analytics, Reports</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/google-bigquery.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">98</span>&nbsp; <span class="chapter-title">Google, BigQuery</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/gtable-package.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">99</span>&nbsp; <span class="chapter-title">gtable package</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/h2o-automl.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">100</span>&nbsp; <span class="chapter-title">h2o automl</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/html-css.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">101</span>&nbsp; <span class="chapter-title">html, css</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/information-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">102</span>&nbsp; <span class="chapter-title">Information Theory</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/inkscape.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">103</span>&nbsp; <span class="chapter-title">Inkscape</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" aria-expanded="false">
 <span class="menu-text">Job</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-18" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-18" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/job-management-leadership.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">104</span>&nbsp; <span class="chapter-title">Job, Management / Leadership</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/job-on-the-job.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">105</span>&nbsp; <span class="chapter-title">Job, On the job</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/job-organizational-and-team-development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">106</span>&nbsp; <span class="chapter-title">Job, Organizational and Team Development</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/job-reports.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">107</span>&nbsp; <span class="chapter-title">Reports</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/job-search.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">108</span>&nbsp; <span class="chapter-title">Job, Search</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/js.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">109</span>&nbsp; <span class="chapter-title">JS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/json.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">110</span>&nbsp; <span class="chapter-title">JSON</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/kubernetes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">111</span>&nbsp; <span class="chapter-title">Kubernetes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/latex.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">112</span>&nbsp; <span class="chapter-title">LaTeX</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/loss-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">113</span>&nbsp; <span class="chapter-title">Loss Functions</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" aria-expanded="false">
 <span class="menu-text">Mathematics</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-19" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-19" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mathematics-linear-algebra.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">114</span>&nbsp; <span class="chapter-title">Linear Algebra</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mathematics-glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">115</span>&nbsp; <span class="chapter-title">Mathematics, Glossary</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mathematics-notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">116</span>&nbsp; <span class="chapter-title">Mathematics, Notation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mathematics-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">117</span>&nbsp; <span class="chapter-title">Probability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mathematics-statistics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">118</span>&nbsp; <span class="chapter-title">Statistical Concepts</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/misc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">119</span>&nbsp; <span class="chapter-title">Misc</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/missingness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">120</span>&nbsp; <span class="chapter-title">Missingness</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/mlops.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">121</span>&nbsp; <span class="chapter-title">MLOps</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" aria-expanded="false">
 <span class="menu-text">Model Building</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-20" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-20" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-brms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">brms</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-concepts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Concepts</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-ensembling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ensembling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-modeltime.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">modeltime</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-rstanarm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">rstanarm</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-sklearn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">sklearn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/model-building-tidymodels.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">tidymodels</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/network-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">122</span>&nbsp; <span class="chapter-title">Network Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" aria-expanded="false">
 <span class="menu-text">NLP</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-21" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-21" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-fine-tuning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">123</span>&nbsp; <span class="chapter-title">NLP, Fine Tuning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">124</span>&nbsp; <span class="chapter-title">NLP, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-llms.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">125</span>&nbsp; <span class="chapter-title">NLP, LLMs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-prompt-engineering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">126</span>&nbsp; <span class="chapter-title">NLP, Prompt Engineering</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-sentiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">127</span>&nbsp; <span class="chapter-title">NLP, Sentiment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-topic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">128</span>&nbsp; <span class="chapter-title">NLP, Topic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/nlp-transformers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">129</span>&nbsp; <span class="chapter-title">NLP, Transformers</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/optimization-equation-systems.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">130</span>&nbsp; <span class="chapter-title">Optimization, Equation Systems</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/outliers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">131</span>&nbsp; <span class="chapter-title">Outliers</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/package-development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">132</span>&nbsp; <span class="chapter-title">Package Development</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-22" aria-expanded="false">
 <span class="menu-text">Post-Hoc Analysis</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-22" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-22" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/post-hoc-analysis-anova.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">133</span>&nbsp; <span class="chapter-title">Post-Hoc Analysis, ANOVA</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/post-hoc-analysis-emmeans.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">134</span>&nbsp; <span class="chapter-title">Post-Hoc Analysis, emmeans</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/post-hoc-analysis-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">135</span>&nbsp; <span class="chapter-title">Post-Hoc Analysis, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/post-hoc-analysis-mixed-effects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">136</span>&nbsp; <span class="chapter-title">Post-Hoc Analysis, Mixed Effects</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/privacy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">137</span>&nbsp; <span class="chapter-title">Privacy</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-23" aria-expanded="false">
 <span class="menu-text">Production</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-23" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-23" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-data-validation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">138</span>&nbsp; <span class="chapter-title">Production, Data Validation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-deployment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">139</span>&nbsp; <span class="chapter-title">Production, Deployment</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">140</span>&nbsp; <span class="chapter-title">Production, Development</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-ml-monitoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">141</span>&nbsp; <span class="chapter-title">Production, ML Monitoring</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">142</span>&nbsp; <span class="chapter-title">Production, Testing</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/production-tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">143</span>&nbsp; <span class="chapter-title">Production, Tools</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-24" aria-expanded="false">
 <span class="menu-text">Projects</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-24" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-24" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/project-development.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">144</span>&nbsp; <span class="chapter-title">Project, Development</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/project-management.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">145</span>&nbsp; <span class="chapter-title">Project, Management</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/project-planning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">146</span>&nbsp; <span class="chapter-title">Project, Planning</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-25" aria-expanded="false">
 <span class="menu-text">Python</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-25" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-25" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-classes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">147</span>&nbsp; <span class="chapter-title">Python, Classes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">148</span>&nbsp; <span class="chapter-title">Python, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-jupyter.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">149</span>&nbsp; <span class="chapter-title">Python, Jupyter</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-misc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">150</span>&nbsp; <span class="chapter-title">Python, Misc</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-numpy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">151</span>&nbsp; <span class="chapter-title">Python, Numpy</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-pandas-recipes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">152</span>&nbsp; <span class="chapter-title">Python, Pandas, Recipes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-pandas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pandas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/python-reticulate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">153</span>&nbsp; <span class="chapter-title">Python, reticulate</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/quarto-rmarkdown.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-26" aria-expanded="true">
 <span class="menu-text">Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-26" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-26" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-discrete.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">154</span>&nbsp; <span class="chapter-title">Regression, Discrete</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-gaussian.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">155</span>&nbsp; <span class="chapter-title">Regression, Gaussian</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">156</span>&nbsp; <span class="chapter-title">Regression, Interactions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">157</span>&nbsp; <span class="chapter-title">Regression, Logistic</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-multivariate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">158</span>&nbsp; <span class="chapter-title">Regression, Multivariate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-nonlinear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">159</span>&nbsp; <span class="chapter-title">Regression, Nonlinear</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-ordinal.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">160</span>&nbsp; <span class="chapter-title">Regression, Ordinal</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-other.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">161</span>&nbsp; <span class="chapter-title">Regression, Other</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-quantile.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">162</span>&nbsp; <span class="chapter-title">Regression, Quantile</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-regularized.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">163</span>&nbsp; <span class="chapter-title">Regression, Regularized</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/regression-survival.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">164</span>&nbsp; <span class="chapter-title">Regression, Survival</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/renv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">165</span>&nbsp; <span class="chapter-title">Renv</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/scraping.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">166</span>&nbsp; <span class="chapter-title">Scraping</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-27" aria-expanded="false">
 <span class="menu-text">Shiny</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-27" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-27" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-general.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">167</span>&nbsp; <span class="chapter-title">Shiny, General</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-hosting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">168</span>&nbsp; <span class="chapter-title">Shiny, Hosting</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-modules.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">169</span>&nbsp; <span class="chapter-title">Shiny, Modules</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-production.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">170</span>&nbsp; <span class="chapter-title">Shiny, Production</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">171</span>&nbsp; <span class="chapter-title">Shiny, Python</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-ui.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">172</span>&nbsp; <span class="chapter-title">Shiny, UI</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/shiny-ui-examples.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">173</span>&nbsp; <span class="chapter-title">Shiny, UI Examples</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/simulation-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">174</span>&nbsp; <span class="chapter-title">Simulation, Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/slack.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">175</span>&nbsp; <span class="chapter-title">Slack</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/spreadsheets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">176</span>&nbsp; <span class="chapter-title">Spreadsheets</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/sql.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">177</span>&nbsp; <span class="chapter-title">SQL</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/stochastic-processes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">178</span>&nbsp; <span class="chapter-title">Stochastic Processes</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-28" aria-expanded="false">
 <span class="menu-text">Surveys</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-28" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-28" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/surveys-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">179</span>&nbsp; <span class="chapter-title">Surveys, Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/surveys-census-data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">180</span>&nbsp; <span class="chapter-title">Surveys, Census Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/surveys-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">181</span>&nbsp; <span class="chapter-title">Surveys, Design</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/surveys-sampling-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">182</span>&nbsp; <span class="chapter-title">Surveys, Sampling Methods</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/teaching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">183</span>&nbsp; <span class="chapter-title">Teaching</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/tidyeval.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">184</span>&nbsp; <span class="chapter-title">Tidyeval</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/tuning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">185</span>&nbsp; <span class="chapter-title">Tuning</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/visualization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">186</span>&nbsp; <span class="chapter-title">Visualization</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/vs-code.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">187</span>&nbsp; <span class="chapter-title">VS Code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../qmd/web-design.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">188</span>&nbsp; <span class="chapter-title">Web Design</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">160</span>&nbsp; <span class="chapter-title">Regression, Ordinal</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>TOC</p>
<ul>
<li>Misc</li>
<li>EDA</li>
<li>Diagnostics</li>
<li>Logistic Regression</li>
<li>Cumulative Link Models (CLMs)</li>
<li>Proportional Odds</li>
<li>Partial Proportional Odds</li>
<li>Scale Effects</li>
<li>Generalized Ordinal Regression</li>
</ul>
<p>todo</p>
<ul>
<li>interpreting scale effects model
<ul>
<li>ordinal vignette again, citatation in vignette, google</li>
<li>“The thresholds are fixed on the scale, but the location of the latent distribution, and therefore also the four areas under the curve, changes with xi”</li>
</ul></li>
<li>diagnostics
<ul>
<li>maybe that survival paper</li>
</ul></li>
<li>Harrell’s RMS notes/chapters</li>
<li>Harrell’s data methods post</li>
<li>what are profile CIs</li>
<li>both TDS articles</li>
</ul>
<p>Misc</p>
<ul>
<li>Notes from
<ul>
<li><a href="http://people.vcu.edu/~dbandyop/BIOS625/CLM_R.pdf">Analysis of ordinal data with cumulative link models — estimation with the R-package ordinal</a></li>
<li><span style="color: #990000">{ordinal}</span> vignette, see below</li>
</ul></li>
<li>Packages
<ul>
<li>Cumulative Link Models (CLMs)
<ul>
<li><span style="color: #990000">{ordinal}</span>
<ul>
<li>CLMs and CLMMs with location, scale and nominal effects (aka partial proportional odds), structured thresholds and flexible link functions</li>
<li>methods for marginal means, tests of functions of the coefficients, goodness-of-fit tests</li>
<li><a href="https://cran.r-project.org/web/packages/ordinal/vignettes/clm_article.pdf">vignette</a></li>
<li>*response variable should be an ordered factor class</li>
<li>Compatible with {marginaleffects}, {emmeans}, {ggeffects}</li>
</ul></li>
<li>{MASS::polr}
<ul>
<li>standard CLMs allowing for the 5 standard link functions but no further extensions</li>
</ul></li>
<li>{VGAM::vglm}
<ul>
<li>CLMs using the cumulative link; allows for several link functions as well as partial effects.</li>
</ul></li>
<li>{rms::lrm, orm}
<ul>
<li>CLMs with the 5 standard link functions but without scale effects, partial or structured thresholds.</li>
</ul></li>
<li><a href="file:///C:/Users/tbats/Downloads/v93i04.pdf"><span style="color: #990000">{mvord}</span></a>:
<ul>
<li>An R Package for Fitting Multivariate Ordinal Regression Models</li>
</ul></li>
<li><span style="color: #990000">{</span><a href="https://cran.r-project.org/web/packages/ordinalNet/index.html" style="color: #990000">ordinalNet</a><span style="color: #990000">}</span>:
<ul>
<li>Fits ordinal regression models with elastic net penalty. Supported model families include cumulative probability, stopping ratio, continuation ratio, and adjacent category</li>
</ul></li>
<li><span style="color: #990000">{brms}</span>
<ul>
<li>CLMs that include structured thresholds in addition to random-effects.</li>
</ul></li>
<li><span style="color: goldenrod">{{mord}}</span>
<ul>
<li>ordinal classification and prediction focused at machine learning applications</li>
</ul></li>
</ul></li>
<li>{partykit::ctree}
<ul>
<li>takes ordered factors as response vars and handles the rest (see vignette)</li>
</ul></li>
</ul></li>
<li>xgboost
<ul>
<li>objective arg: “rank:pairwise”, “rank:ndcp”, “rank:map”</li>
<li>something else needs to be done. xgboost::predict returned 0.5 for all values (sliced s1e6)</li>
</ul></li>
<li>Ordered probit regression: This is very, very similar to running an ordered logistic regression. The main difference is in the interpretation of the coefficients.</li>
<li>Sample size: Both ordered logistic and ordered probit, using maximum likelihood estimates, require sufficient sample size. How big is big is a topic of some debate, but they almost always require more cases than OLS regression.</li>
<li>Harrell summary and comparison of a PO model vs Logistic in the case of an ordinal outcome<img src="./_resources/Regression,_Ordinal.resources/Screenshot (763).png" class="img-fluid">
<ul>
<li>Formula is an ordinal outcome, Y, with binary treatment variable, Tx, and adjustment variables, X.</li>
<li>Sometimes researchers tend to collapse an ordinal outcome into a binary outcome. Harrell is showing how using a logistic model is inefficient and lower power than a PO model</li>
<li>Original is interactive with additional information (<a href="https://atlas.mindmup.com/vbiostat/po/#">link</a>)</li>
<li>includes: efficiency, infomation used, assumptions, special cases, estimands, misc</li>
</ul></li>
</ul>
<p>EDA</p>
<ul>
<li>Examine distributions of the variables to get an idea of potential relationships
<ul>
<li>Crosstabs for ordinal response and categorical explanatory variables</li>
</ul></li>
</ul>
<pre><code>ftable(xtabs(~ public + apply + pared, data = dat))

##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; pared&nbsp; 0&nbsp; 1
## public apply&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
## 0&nbsp; &nbsp; &nbsp; unlikely&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 175&nbsp; 14
##&nbsp; &nbsp; &nbsp; &nbsp; somewhat likely&nbsp; &nbsp; &nbsp; &nbsp; 98&nbsp; 26
##&nbsp; &nbsp; &nbsp; &nbsp; very likely&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 20&nbsp; 10
## 1&nbsp; &nbsp; &nbsp; unlikely&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 25&nbsp; 6
##&nbsp; &nbsp; &nbsp; &nbsp; somewhat likely&nbsp; &nbsp; &nbsp; &nbsp; 12&nbsp; 4
##&nbsp; &nbsp; &nbsp; &nbsp; very likely&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 7&nbsp; 3</code></pre>
<ul>
<li><p>apply is the response variable</p></li>
<li><p>Empty cells or small cells: If a cell has very few cases, the model may become unstable or it might not run at all.</p></li>
<li><p>Can plot a histogram or compute percentages for each level of the variable</p></li>
<li><p>Example: lvl_1% = lvl_1/N =&nbsp; 0.2219, lvl_2% = 0.2488, lvl_3% = 0.25, and lvl_4% = 0.2794</p>
<ul>
<li>Skewed and monotonicly increasing</li>
</ul></li>
<li><p>Example</p>
<ul>
<li>If distributions of a pre-treatment/baseline (outcome) variable looks substantially different than the (post-treatment) outcome variable, then the treatment likely had an effect</li>
</ul></li>
<li><p>Descriptive stats for numeric explanatory variables</p></li>
<li><p>Bi-variate boxplots</p>
<ul>
<li>Look for trends of the median</li>
<li>Example: ordinal vs ordinal<img src="./_resources/Regression,_Ordinal.resources/Screenshot (1141).png" class="img-fluid">
<ul>
<li>No idea what the red/blue splits mean</li>
<li>Y-Axis: ordinal outcome: 4 levels (y-xis is messed up)</li>
<li>X-Axis: pre-treatment variable: 7 levels</li>
<li>Boxes have the counts</li>
<li>Steady increase in the median
<ul>
<li>Makes sense because someone starting w/a higher score (pre-treatment) should mostly end up with a higher score (post-treatment)</li>
</ul></li>
</ul></li>
<li>Example: numeric vs ordinal<img src="./_resources/Regression,_Ordinal.resources/image.png" class="img-fluid"></li>
</ul></li>
</ul>
<pre><code>ggplot(dat, aes(x = apply, y = gpa)) +
&nbsp; geom_boxplot(size = .75) +
&nbsp; geom_jitter(alpha = .5) +
&nbsp; facet_grid(pared ~ public, margins = TRUE) +
&nbsp; theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))</code></pre>
<ul>
<li><p>In the lower right hand corner, is the overall relationship between apply and gpa which appears slightly positive.</p></li>
<li><p>Pre-intervention means of the outcome by explanatory variables</p>
<ul>
<li>Example</li>
</ul></li>
</ul>
<pre><code>CC = 0, TV = 0 2.152
CC = 0, TV = 1 2.087
CC = 1, TV = 0 2.050
CC = 1, TV = 1 1.979</code></pre>
<ul>
<li>CC and TV are binary explanatory variables</li>
<li>The mean score of the pre-treatment outcome doesn’t change much given these two explanatory variables.</li>
<li>I think this shows that for the most part that assignment of the two different treatments was balanced in terms of the scores of the baseline variable.</li>
</ul>
<p>Diagnostics</p>
<ul>
<li>Deviance: -2*(LogLik Reduced Model - LogLik Saturated model)
<ul>
<li>likelihood ratio statistic for the comparison of the full and reduced models</li>
<li>Reduced model is the model you just fit.
<ul>
<li>Can usually be extracted from the model object (e.g.&nbsp;<span style="color: #990000">{ordinal}</span><code>ll_reduced &lt;- mod$logLik</code>)</li>
</ul></li>
<li>Saturated model also called the Full model (Also see <a href="Regression, Discrete">Regression, Discrete</a> &gt;&gt; Misc)
<ul>
<li>The full model has a parameter for each observation and describes the data perfectly while the reduced model provides a more concise description of the data with fewer parameters.</li>
<li>Usually calculated from the data themselves</li>
</ul></li>
</ul></li>
</ul>
<pre><code>data(wine, package = "ordinal")
tab &lt;- with(wine, table(temp:contact, rating))
## Get full log-likelihood (aka saturated model log-likelihood)
pi.hat &lt;- tab / rowSums(tab)
(ll.full &lt;- sum(tab * ifelse(pi.hat &gt; 0, log(pi.hat), 0))) ## -84.01558</code></pre>
<ul>
<li>GOF: as a rule of thumb, if the deviance about the same size as the difference in the number of parameters (i.e.&nbsp;pfull - preduced), there is NOT evidence of lack of fit. (<span style="color: #990000">{ordinal}</span> <a href="http://people.vcu.edu/~dbandyop/BIOS625/CLM_R.pdf">vignette</a>, pg 14)
<ul>
<li>Example (have doubts this is correct)
<ul>
<li>Looking at the number of params (“no.par”) for fm1 in Example: <span style="color: #990000">{ordinal}</span>, model selection with LR tests below and the model summary in Proportional Odds (PO) &gt;&gt; Example: <span style="color: #990000">{ordinal}</span>, response = wine rating (1 to 5 = most bitter), the number of parameters for the reduced model is the number of regression parameters (2) + number of thresholds (4)</li>
<li>For the full model (aka saturated), the number of thresholds should be the same, and there should be one more regression parameter, an interaction between “temp” and “contact”. So, 7 should be the number of parameters for the full model</li>
<li>Therefore, for a good-fitting model, the deviance should be close to pfull - preduced = 7 - 6 = 1</li>
<li>This example uses “number of parameters” which is the phrase in the vignette but I think it’s possible he might mean degrees of freedom (dof) which he immediatedly discusses afterwards. In the LR Test example below, under LR.Stat, which is essentially what deviance is, the number is around 11 which is quite aways from 1. Not exactly an apples to apples comparison, but the size after adding 1 parameter just makes me wonder if dof would match this scale of numbers for deviances better.</li>
</ul></li>
</ul></li>
<li>Model selection: A difference in deviance between two nested models is identical to the likelihood ratio statistic for the comparison of these models
<ul>
<li>see below, Example: <span style="color: #990000">{ordinal}</span>, model selection with LR test</li>
</ul></li>
<li>Requirement: Deviance tests are fine if the expected frequencies under the reduced model are not too small and as a general rule they should all be at least five.
<ul>
<li>Also see Discrete Analysis notebook</li>
</ul></li>
<li>Residual Deviance: Dresid = Dtotal - Dreduced
<ul>
<li>a concept similar to a residual sums of squares (RSS)</li>
<li>Total Deviance (Dtotal) is the Null Deviance: -2*(LogLik Null Model - LogLik Saturated model)
<ul>
<li>analogous to the total sums of squares for linear models</li>
</ul></li>
<li>Dreduced is the calculation of “Deviance” shown above</li>
<li>See example 7, pg 13 (<span style="color: #990000">{ordinal}</span> <a href="http://people.vcu.edu/~dbandyop/BIOS625/CLM_R.pdf">vignette</a>) for (manual) code</li>
</ul></li>
<li><span class="ribbon-highlight">Example</span>: <span style="color: #990000">{ordinal}</span>, model selection with LR tests</li>
</ul>
<pre><code>fm2 &lt;- clm(rating ~ temp, data = wine)
anova(fm2, fm1)

Likelihood ratio tests of cumulative link models:
&nbsp; &nbsp; formula:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; link:&nbsp; threshold:
fm2 rating ~ temp&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; logit&nbsp; flexible
fm1 rating ~ temp + contact logit&nbsp; flexible
&nbsp; &nbsp; no.par AIC&nbsp; &nbsp; logLik&nbsp; LR.stat df Pr(&gt;Chisq)
fm2 5&nbsp; &nbsp; &nbsp; 194.03 -92.013
fm1 6&nbsp; &nbsp; &nbsp; 184.98 -86.492&nbsp; 11.043&nbsp; 1&nbsp; 0.0008902 ***</code></pre>
<ul>
<li><p>For “fm1” model, see Proportional Odds (PO) &gt;&gt; Example <span style="color: #990000">{ordinal}</span>, response = wine rating (1 to 5 = most bitter)</p></li>
<li><p>Special method for clm objects from the package; produces an Analysis of Deviance (ANODE) table</p></li>
<li><p>Adding “contact” produces a better model (pval &lt; 0.05)</p></li>
<li><p><span class="ribbon-highlight">Example</span>: <span style="color: #990000">{ordinal}</span>, variable LR tests</p></li>
</ul>
<pre><code>drop1(fm1, test = "Chi")

rating ~ contact + temp
&nbsp; &nbsp; &nbsp; Df&nbsp; AIC&nbsp; &nbsp; LRT&nbsp; &nbsp; Pr(&gt;Chi)
&lt;none&gt;&nbsp; &nbsp; 184.98
contact 1&nbsp; 194.03 11.043 0.0008902 ***
temp&nbsp; &nbsp; 1&nbsp; 209.91 26.928 2.112e-07 ***

fm0 &lt;- clm(rating ~ 1, data = wine)
add1(fm0, scope = ~ temp + contact, test = "Chi")

&nbsp; &nbsp; &nbsp; &nbsp; Df&nbsp; AIC&nbsp; &nbsp; LRT&nbsp; &nbsp; &nbsp; Pr(&gt;Chi)
&lt;none&gt;&nbsp; &nbsp; &nbsp; 215.44
temp&nbsp; &nbsp; 1&nbsp; &nbsp; 194.03&nbsp; 23.4113&nbsp; 1.308e-06 ***
contact 1&nbsp; &nbsp; 209.91&nbsp; 7.5263&nbsp; 0.00608 **</code></pre>
<ul>
<li>For “fm1” model, see Proportional Odds (PO) &gt;&gt; Example <span style="color: #990000">{ordinal}</span>, response = wine rating (1 to 5 = most bitter)</li>
<li><code>drop1</code>
<ul>
<li>Tests the same thing as the Wald tests in the summary except with χ2 instead of t-tests
<ul>
<li>i.e.&nbsp;whether the estimates, while controlling for the other variables, differ from 0, except with LR tests.</li>
</ul></li>
<li>In this case, LR tests slightly more significant than the Wald tests</li>
</ul></li>
<li><code>add1</code>
<ul>
<li>Tests variables where they’re the only explanatory variable in the model</li>
<li>Both variables still significant even without controlling for the other variable</li>
</ul></li>
</ul>
<p>Logistic Regression</p>
<ul>
<li></li>
</ul>
<p>Cumulative Link Models (CLM)</p>
<ul>
<li>A general class of ordinal regression models that include many of the models in this note.</li>
<li>Types
<ul>
<li>proportional odds model: CLM with a logit link</li>
<li>proportional hazards model - CLM with a log-log link, for grouped survival times<img src="./_resources/Regression,_Ordinal.resources/Screenshot (1130).png" class="img-fluid">
<ul>
<li>link function: log[− log(1 − γ)]</li>
<li>inverse link: 1 − exp[− exp(η)]</li>
<li>distribution: Gumbel (min)b (?)</li>
<li>1 − γj(xi) is the probability or survival beyond category j given xi .</li>
</ul></li>
<li>partial proportional odds - also referred to as unequal slopes, partial effects, and nominal effects</li>
<li>cumulative link mixed models (CLMM) - CLMs with normally distributed random effects</li>
</ul></li>
<li>Link functions<img src="./_resources/Regression,_Ordinal.resources/Screenshot (1139).png" class="img-fluid">
<ul>
<li>Note the shape of the distributions of the response (see EDA) to help choose a link function
<ul>
<li>See Proportional Odds (PO) &gt;&gt; Example: <span style="color: #990000">{ordinal}</span>, weighted complimentary log-log regression, comparing links</li>
<li>The probit link is often used when the model is interpreted with reference to a latent variable</li>
<li>Kurtotic, see <a href="Statistical Concepts">Statistical Concepts</a> &gt;&gt; Fundamentals &gt;&gt; Kurtosis (i.e.&nbsp;higher sharper peaks w/short tails, flatter peaks w/long tails)
<ul>
<li>Default parameter values fit a symmetric heavy tailed distribution (high, sharp peak)</li>
</ul></li>
</ul></li>
</ul></li>
<li>Model<img src="./_resources/Regression,_Ordinal.resources/Screenshot (1136).png" class="img-fluid">
<ul>
<li>j is the jth ordinal category where j1 &lt; j2 &lt; …</li>
<li>i is the ith observation</li>
<li>the regression part xTi β is independent of j, so β has the same effect for each of the J − 1 cumulative logits</li>
<li>The {θj} parameters provide each cumulative logit (for each j, see below) with its own intercept
<ul>
<li>θ is called a “threshold.” See below, Latent Variable Concept</li>
</ul></li>
</ul></li>
<li>Response variable follows the Multinomial distribution<img src="./_resources/Regression,_Ordinal.resources/Screenshot (1132).png" class="img-fluid">
<ul>
<li>The output is the probability that the response is the jth category or lower.</li>
<li>πij denotes the probability that the ith observation falls in response category j</li>
</ul></li>
<li>Cumulative Logits (Logit Link)<img src="./_resources/Regression,_Ordinal.resources/Screenshot (1129).png" class="img-fluid">
<ul>
<li>j = 1 , … , J - 1 so cumulative logits are defined for all but the last category</li>
<li>If x represent a treatment variable with two levels (e.g., placebo and treatment), then x2 − x1 =&nbsp; 0 - 1 = -1 and the odds ratio is exp(−βtreatment).
<ul>
<li>Similarly the odds ratio of the event Y ≥ j is exp(βtreatment) (i.e.&nbsp;inverse of Y ≤ j).</li>
</ul></li>
</ul></li>
<li>Latent Variable Concept
<ul>
<li>Notes from <a href="https://ssicentral.com/wp-content/uploads/2021/06/Models_for_proportional_and_non_proportional_odds.pdf">article</a></li>
<li>“To motivate the ordinal regression model, it is often assumed that there is an unobservable latent variable ( y* ) which is related to the actual response through the”<strong>threshold concept</strong>.” An example of this is when respondents are asked to rate their agreement with a given statement using the categories “Disagree,” “Neutral,” “Agree.” These three options leave no room for any other response, though one can argue that these are three possibilities along a continuous scale of agreement that would also make provision for “Strongly Agree” and “Disagree somewhat.” The ordinal responses captured in y and the latent continuous variable y* are linked through some fixed, but unknown, thresholds.”</li>
<li>A response occurs in category j (Y = j) if the latent response process y* exceeds the threshold value, θj-1 , but does not exceed the threshold value, θj .
<ul>
<li>I think y* is continous on the scale of logits. θjs are also intercepts in the model equations and also on the scale of logits (see Proportional Odds (PO) &gt;&gt; Example: {MASS::polr})</li>
</ul></li>
<li>The cumulative probabilities are given in terms of the cumulative logits with J −1 strictly increasing model thresholds θ1, θ2, … , θJ-1 .
<ul>
<li>With J = 4, we would have J −1 = 3 cumulative probabilities, given in terms of 3 thresholds θ1, θ2, and θ3 . The thresholds represent the marginal response probabilities in the J categories.</li>
<li>Each cumulative logit is a model equation with a threshold for an intercept</li>
</ul></li>
<li>To set the <em>location</em> of the latent variable, it is common to set a threshold to zero. Usually, the first of the threshold parameters (θ1) is set to zero.
<ul>
<li>Alternatively, the model intercept (β0) is set to zero and J −1 thresholds are estimated. (Think this is the way <span style="color: #990000">{ordinal}</span> does it.)</li>
</ul></li>
</ul></li>
<li>Structured Thresholds
<ul>
<li>If ratings are the response variable, placing restrictions on thresholds and fitting a model allows us to test assumptions on how the judges are using the response scale</li>
<li>An advantage of applying additional restrictions on the thresholds is model has fewer parameters to estimate which increases model sensitivity.</li>
<li>Threshold distances are affected by the shape of the latent variable distribution which is determined by the link function used
<ul>
<li>i.e.&nbsp;if it’s determined that threshold distances are equidistant under a normal distribution (logit link) assumption, then they will not be equidistant if a different link function is used.</li>
</ul></li>
<li><span class="ribbon-highlight">Example</span>: is the reponse scale being treated by judges as equidistant between values.
<ul>
<li>e.g.&nbsp;is the distance between a rating of 2 and a rating of 1 the same as the distance between a rating of 2 and a rating of 3?</li>
<li>Mathematically: θj − θj−1 = constant for j = 2, …, J−1 where θ are the thresholds and J is the number of levels in the response variable.</li>
<li>Fit equidistant model</li>
</ul></li>
</ul></li>
</ul>
<pre><code>fm.equi &lt;- clm(rating ~ temp + contact, data = wine, threshold = "equidistant")
summary(fm.equi)

link&nbsp; threshold&nbsp; nobs&nbsp; logLik&nbsp; AIC&nbsp; &nbsp; niter&nbsp; max.grad&nbsp; cond.H
logit equidistant 72&nbsp; -87.86&nbsp; 183.73 5(0)&nbsp; 4.80e-07&nbsp; 3.2e+01

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std.Error z.value Pr(&gt;|z|)
tempwarm&nbsp; 2.4632&nbsp; 0.5164&nbsp; &nbsp; 4.77&nbsp; &nbsp; 1.84e-06 ***
contactyes 1.5080&nbsp; 0.4712&nbsp; &nbsp; 3.20&nbsp; &nbsp; 0.00137 **

Threshold coefficients:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std.Error z.value
threshold.1 -1.0010&nbsp; 0.3978&nbsp; -2.517
spacing&nbsp; &nbsp; &nbsp; 2.1229&nbsp; 0.2455&nbsp; &nbsp; 8.646</code></pre>
<ul>
<li><p>spacing: average distance between consecutive thresholds</p></li>
<li><p>Compare spacing parameter with your model’s average spacing</p></li>
</ul>
<pre><code>mean(diff(coef(fm1)[1:4]))
2.116929</code></pre>
<ul>
<li><p>“fm1” is from an example in the Proportional Odds (PO) section</p></li>
<li><p>Result: “fm1” spacing is very close to “fm.equi” spacing. Judges are likely applying the response scale as having equal distance between rating values.</p></li>
<li><p>Does applying threshold restrictions decrease the model’s GOF</p></li>
</ul>
<pre><code>anova(fm1, fm.equi)
&nbsp; &nbsp; &nbsp; &nbsp; no.par AIC&nbsp; &nbsp; logLik LR.stat df Pr(&gt;Chisq)
fm.equi 4&nbsp; &nbsp; &nbsp; 183.73 -87.865
fm1&nbsp; &nbsp; 6&nbsp; &nbsp; &nbsp; 184.98 -86.492 2.7454&nbsp; 2&nbsp; 0.2534</code></pre>
<ul>
<li>No statistical difference in log-likelihoods. Fewer parameters to estimate is better, so keep the equidistant thresholds</li>
</ul>
<p>Proportional Odds (PO)</p>
<ul>
<li>Misc
<ul>
<li>The treatment effect for proportional odds model will be the average of the treatment effects of J-1 logistic regression models where each model is dichotmized at each, but not the last, ordinal level.
<ul>
<li>The intercepts in the proportional odds model will be similar to those intercepts from the J-1 logistic regression models
<ul>
<li>The intercepts of these logistic models have to be different, but the slopes could (in principle) be the same or same-ish. If they are the same, then the proportional odds assumption holds.</li>
</ul></li>
<li>The proportional odds model has a smaller std.error for its treatment effect than any of the treatment effects of the J-1 logistic regression models (i.e.&nbsp;more accurately estimated in p.o. model)</li>
</ul></li>
<li>Benefits
<ul>
<li>It enforces stochastic ordering (?)</li>
<li>Lots of choices for link functions.</li>
<li>Reasonable model for analysing ordinal data
<ul>
<li>β will be some sort of appropriately-weighted average of what you’d get for the separate logistic regressions</li>
</ul></li>
</ul></li>
</ul></li>
<li>Assumption: The independent variable effect is the same for all levels of the ordinal outcome variable
<ul>
<li>βs (i.e.&nbsp;treatment effect) are not allowed to vary with j (i.e.&nbsp;response variable levels) or equivalently that the threshold parameters {θj} are not allowed to depend on regression variables</li>
<li>Example:
<ul>
<li>outcome = health_status (1 for poor, 2 for average, 3 for good and 4 for excellent)</li>
<li>independent variable = family_income (1 for above avg, 0 for below average)</li>
<li>If the proportional odds assumption holds then:
<ul>
<li>The log odds of being at average health from poor health is ‘β1’ if family income increases to above average status.</li>
<li>The log odds of being at good heath from average health is ‘β1’ if family income increases to above average status.</li>
<li>The log odds of being at excellent heath from good health is ‘β1’ if family income increases to above average status.</li>
</ul></li>
</ul></li>
<li>Testing the assumption
<ul>
<li>**Even if the model fails the PO assumption, it can still be useful (see Misc &gt;&gt; Harrell summary and comparison of a PO model vs Logistic…)</li>
<li>Issues with testing
<ul>
<li>Small Sample Sizes: For some variables, you might not have enough power to detect important violations of the PO assumption.</li>
<li>Large Sample Sizes: For some variables, you will detect small, unimportant violations of the PO assumption and reject a good model.</li>
<li>Omnidirectional goodness-of-fit tests don’t tell you which variables you should look at for improvements.</li>
</ul></li>
<li>You can test this assumption by fitting a PO model and PPO model. Then, comparing both models via LR Test or using {ordinal::nominal_test} (see below, Partial Proportional Odds (PPO) examples)</li>
<li>Assess graphically (<a href="https://stats.oarc.ucla.edu/r/dae/ordinal-logistic-regression/">article</a>, Harrell RMS pg 316)
<ul>
<li>1.) Calculate estimated effects for each explanatory variable in a univariate logistic regression model (e.g.&nbsp;glm(apply ~ pared, family = binomial))</li>
</ul></li>
</ul></li>
</ul></li>
</ul>
<pre><code>sf &lt;- function(y) {
&nbsp; c('Y&gt;=1' = qlogis(mean(y &gt;= 1)),
&nbsp; &nbsp; 'Y&gt;=2' = qlogis(mean(y &gt;= 2)),
&nbsp; &nbsp; 'Y&gt;=3' = qlogis(mean(y &gt;= 3)))
}
(s &lt;- with(dat, summary(as.numeric(apply) ~ pared + public + gpa, fun=sf)))
## +-------+-----------+---+----+--------+------+
## |&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |N&nbsp; |Y&gt;=1|Y&gt;=2&nbsp; &nbsp; |Y&gt;=3&nbsp; |
## +-------+-----------+---+----+--------+------+
## |pared&nbsp; |No&nbsp; &nbsp; &nbsp; &nbsp; |337|Inf |-0.37834|-2.441|
## |&nbsp; &nbsp; &nbsp; |Yes&nbsp; &nbsp; &nbsp; &nbsp; | 63|Inf | 0.76547|-1.347|
## +-------+-----------+---+----+--------+------+
## |public |No&nbsp; &nbsp; &nbsp; &nbsp; |343|Inf |-0.20479|-2.345|
## |&nbsp; &nbsp; &nbsp; |Yes&nbsp; &nbsp; &nbsp; &nbsp; | 57|Inf |-0.17589|-1.548|
## +-------+-----------+---+----+--------+------+
## |gpa&nbsp; &nbsp; |[1.90,2.73)|102|Inf |-0.39730|-2.773|
## |&nbsp; &nbsp; &nbsp; |[2.73,3.00)| 99|Inf |-0.26415|-2.303|
## |&nbsp; &nbsp; &nbsp; |[3.00,3.28)|100|Inf |-0.20067|-2.091|
## |&nbsp; &nbsp; &nbsp; |[3.28,4.00]| 99|Inf | 0.06062|-1.804|
## +-------+-----------+---+----+--------+------+
## |Overall|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |400|Inf |-0.20067|-2.197|
## +-------+-----------+---+----+--------+------+</code></pre>
<ul>
<li><p>For Y ≥ 2 and “pared = no”, -0.37834 is the same as the intercept of the univariate model</p></li>
<li><p>For Y ≥ 2 and “pared = yes”, 0.76547 is the same as the intercept + coefficient of the univariate model</p></li>
<li><p>2.) For each variable, calculate differences in estimates between levels of the ordinal response</p></li>
</ul>
<pre><code>s[, 4] &lt;- s[, 4] - s[, 3]
s[, 3] &lt;- s[, 3] - s[, 3]
s
## +-------+-----------+---+----+----+------+
## |&nbsp; &nbsp; &nbsp; |&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |N&nbsp; |Y&gt;=1|Y&gt;=2|Y&gt;=3&nbsp; |
## +-------+-----------+---+----+----+------+
## |pared&nbsp; |No&nbsp; &nbsp; &nbsp; &nbsp; |337|Inf |0&nbsp; |-2.062|
## |&nbsp; &nbsp; &nbsp; |Yes&nbsp; &nbsp; &nbsp; &nbsp; | 63|Inf |0&nbsp; |-2.113|
## +-------+-----------+---+----+----+------+
## |public |No&nbsp; &nbsp; &nbsp; &nbsp; |343|Inf |0&nbsp; |-2.140|
## |&nbsp; &nbsp; &nbsp; |Yes&nbsp; &nbsp; &nbsp; &nbsp; | 57|Inf |0&nbsp; |-1.372|
## +-------+-----------+---+----+----+------+
## |gpa&nbsp; &nbsp; |[1.90,2.73)|102|Inf |0&nbsp; |-2.375|
## |&nbsp; &nbsp; &nbsp; |[2.73,3.00)| 99|Inf |0&nbsp; |-2.038|
## |&nbsp; &nbsp; &nbsp; |[3.00,3.28)|100|Inf |0&nbsp; |-1.890|
## |&nbsp; &nbsp; &nbsp; |[3.28,4.00]| 99|Inf |0&nbsp; |-1.864|
## +-------+-----------+---+----+----+------+
## |Overall|&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |400|Inf |0&nbsp; |-1.997|
## +-------+-----------+---+----+----+------+</code></pre>
<ul>
<li><p>For pared, the difference in estimates between Y ≥ 2 and Y ≥ 3 is -2.062 and -2.113. Therefore, it would seem that the PO assumption holds up pretty well for pared</p></li>
<li><p>For public, the difference in estimates between Y ≥ 2 and Y ≥ 3 is -2.140 and -1.372. Therefore, it would seem that the PO assumption does NOT hold up for public&nbsp;</p></li>
<li><p>If there was a Y ≥ 4, then for pared, the difference in estimates between Y ≥ 3 and Y ≥ 4 should be near 2 as well in order for the PO assumption to hold for that variable.</p></li>
<li><p>3.) Plot <code>plot(s, which=1:3, pch=1:3, xlab='logit', main=' ', xlim=range(s[,3:4]))</code><img src="./_resources/Regression,_Ordinal.resources/image.1.png" class="img-fluid"></p>
<ul>
<li>In addition to the PO assumption not seemingly holding for public, there also seems to be some substantial differences between the quantiles of gpa.
<ul>
<li>The 3rd and 4th seem to be in agreement, but not the 1st and maybe not the 2nd.</li>
</ul></li>
</ul></li>
<li><p><span class="ribbon-highlight">Example</span>: <span style="color: #990000">{ordinal}</span>, response = wine rating (1 to 5 = most bitter)</p></li>
</ul>
<pre><code>fm1 &lt;- clm(rating ~ contact + temp, data = wine)
summary(fm1)

formula: rating ~ contact + temp
data: wine

link threshold nobs logLik&nbsp; AIC&nbsp; &nbsp; niter max.grad&nbsp; cond.H
logit flexible 72&nbsp; -86.49&nbsp; 184.98&nbsp; 6(0)&nbsp; 4.01e-12&nbsp; 2.7e+01

Coefficients:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate&nbsp; Std.Error&nbsp; z value&nbsp; Pr(&gt;|z|)
contactyes 1.5278&nbsp; &nbsp; 0.4766&nbsp; &nbsp; 3.205&nbsp; &nbsp; 0.00135 **
tempwarm&nbsp; 2.5031&nbsp; &nbsp; 0.5287&nbsp; &nbsp; 4.735&nbsp; &nbsp; 2.19e-06 ***
---
Signif. codes: 0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Threshold coefficients:
&nbsp; &nbsp; Estimate Std.Error z value
1|2 -1.3444&nbsp; 0.5171&nbsp; -2.600
2|3&nbsp; 1.2508&nbsp; 0.4379&nbsp; &nbsp; 2.857
3|4&nbsp; 3.4669&nbsp; 0.5978&nbsp; &nbsp; 5.800
4|5&nbsp; 5.0064&nbsp; 0.7309&nbsp; &nbsp; 6.850

confint(fm1)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 2.5 %&nbsp; &nbsp; 97.5 %
tempwarm&nbsp; 1.5097627 3.595225
contactyes 0.6157925 2.492404</code></pre>
<ul>
<li>model: logit(P(Yi ≤ j)) = θj − β1(tempi ) − β2(contacti)</li>
<li>*response variable should be an ordered factor class
<ul>
<li>In this example, both explanatory variables were factor variables.</li>
</ul></li>
<li>“cond.H” - condition number of the Hessian is a measure of how identifiable the model is
<ul>
<li>Values larger than 1e4 indicate that the model may be ill defined</li>
</ul></li>
<li>Regression Coefficients
<ul>
<li>β1(warm − cold) = 2.50
<ul>
<li>The reference level is cold, and this is the effect of moving from cold to warm</li>
</ul></li>
<li>β2(yes − no) = 1.53
<ul>
<li>The odds ratio of bitterness being rated in category j or above (OR(Y ≥ j)) is exp(β2(yes − no)) = exp(1.53) = 4.61.
<ul>
<li>Note: this is Pr(Y ≥ j) which is why we’re using the positive β</li>
</ul></li>
<li>The reference level is no, and this is the effect of moving from no to yes</li>
</ul></li>
<li>Interpretation:
<ul>
<li>contact and warm temperature both lead to higher probabilities of observations in the high categories</li>
<li>Me: The odds of the rating being higher are 4.61 times greater when contact = yes than when contact = no.</li>
</ul></li>
</ul></li>
<li>Thresholds (aka intercepts)
<ul>
<li>{ θj} = {−1.34, 1.25, 3.47, 5.01}</li>
<li>Often the thresholds are not of primary interest, but they are an integral part of the model. .</li>
<li>It is not relevant to test whether the thresholds are equal to zero, so no p-values are provided for this test.</li>
</ul></li>
<li><span class="ribbon-highlight">Example</span>: <span style="color: #990000">{ordinal}</span>, weighted complimentary log-log regression, comparing links
<ul>
<li>data</li>
</ul></li>
</ul>
<pre><code>&nbsp; year&nbsp; pct income
1&nbsp; 1960&nbsp; 6.5&nbsp; &nbsp; 0-3
2&nbsp; 1960&nbsp; 8.2&nbsp; &nbsp; 3-5
3&nbsp; 1960 11.3&nbsp; &nbsp; 5-7
4&nbsp; 1960 23.5&nbsp; 7-10
5&nbsp; 1960 15.6&nbsp; 10-12
6&nbsp; 1960 12.7&nbsp; 12-15
7&nbsp; 1960 22.2&nbsp; &nbsp; 15+
8&nbsp; 1970&nbsp; 4.3&nbsp; &nbsp; 0-3
9&nbsp; 1970&nbsp; 6.0&nbsp; &nbsp; 3-5
10 1970&nbsp; 7.7&nbsp; &nbsp; 5-7
11 1970 13.2&nbsp; 7-10
12 1970 10.5&nbsp; 10-12
13 1970 16.3&nbsp; 12-15
14 1970 42.1&nbsp; &nbsp; 15+</code></pre>
<ul>
<li><p>“income” (ordered factor) are intervals in thousands of 1973 US dollars</p></li>
<li><p>“pct” (numeric) is percent of the population in that income bracket from that particular year</p></li>
<li><p>“year” (factor)</p></li>
<li><p>Comparing multiple links</p></li>
</ul>
<pre><code>&gt; links &lt;- c("logit", "probit", "cloglog", "loglog", "cauchit")
&gt; sapply(links, function(link) {
clm(income ~ year, data=income, weights=pct, link=link)$logLik })
logit&nbsp; &nbsp; probit&nbsp; &nbsp; cloglog&nbsp; loglog&nbsp; &nbsp; cauchit
-353.3589 -353.8036 -352.8980 -355.6028 -352.8434</code></pre>
<ul>
<li><p>The cauchy distribution has the highest log-likelihood and is therefore the best fit to the data, but is closely followed by the complementary log-log link</p></li>
<li><p>Fit the cloglog for interpretation convenience</p></li>
</ul>
<pre><code>mod &lt;- clm(income ~ year, data=income, weights=pct, link="cloglog")
summary(mod)

link&nbsp; &nbsp; threshold nobs&nbsp; logLik&nbsp; AIC&nbsp; &nbsp; niter max.grad cond.H&nbsp;
cloglog flexible&nbsp; 200.1 -352.90 719.80 6(0)&nbsp; 1.87e-11 7.8e+01

&nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error z value Pr(&gt;|z|)&nbsp; &nbsp;
year1970&nbsp; 0.5679&nbsp; &nbsp; 0.1749&nbsp; 3.247&nbsp; 0.00116 **

Threshold coefficients:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std. Error z value
0-3|3-5&nbsp; &nbsp; -2.645724&nbsp; 0.310948&nbsp; -8.509
3-5|5-7&nbsp; &nbsp; -1.765970&nbsp; 0.210267&nbsp; -8.399
5-7|7-10&nbsp; &nbsp; -1.141808&nbsp; 0.164710&nbsp; -6.932
7-10|10-12&nbsp; -0.398434&nbsp; 0.132125&nbsp; -3.016
10-12|12-15&nbsp; 0.004931&nbsp; 0.123384&nbsp; 0.040
12-15|15+&nbsp; &nbsp; 0.418985&nbsp; 0.120193&nbsp; 3.486</code></pre>
<ul>
<li>** The uncertainty of parameter estimates depends on the sample size, which is unknown here, so hypothesis tests should not be considered **</li>
<li>Interpretation
<ul>
<li>“If p1960(x) is proportion of the population with an income larger than $x in 1960 and p1970(x) is the equivalent in 1970, then approximately”<img src="./_resources/Regression,_Ordinal.resources/Screenshot (1164).png" class="img-fluid"></li>
<li>So for any income dollar amount, the proportion of the population in 1960 (or 1970 w/some algebra) with that income or greater can be estimated.</li>
</ul></li>
<li><span class="ribbon-highlight">Example</span>: {MASS::polr}, response = apply (3 levels) (<a href="https://stats.oarc.ucla.edu/r/dae/ordinal-logistic-regression/">article</a>)</li>
</ul>
<pre><code>m &lt;- polr(apply ~ pared + public + gpa, data = dat, Hess=TRUE)
summary(m)

## Coefficients:
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Value Std. Error t value
## pared&nbsp; 1.0477&nbsp; &nbsp; &nbsp; 0.266&nbsp; 3.942
## public -0.0588&nbsp; &nbsp; &nbsp; 0.298&nbsp; -0.197
## gpa&nbsp; &nbsp; 0.6159&nbsp; &nbsp; &nbsp; 0.261&nbsp; 2.363
##&nbsp;
## Intercepts:
##&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Value&nbsp; Std. Error t value
## unlikely|somewhat likely&nbsp; &nbsp; 2.204&nbsp; 0.780&nbsp; &nbsp; &nbsp; 2.827&nbsp;
## somewhat likely|very likely&nbsp; 4.299&nbsp; 0.804&nbsp; &nbsp; &nbsp; 5.345&nbsp;
##&nbsp;
## Residual Deviance: 717.02&nbsp;
## AIC: 727.02</code></pre>
<ul>
<li>Response: “apply” to grad school with levels “unlikely”, “somewhat likely”, and “very likely” (coded 1, 2, and 3)
<ul>
<li>The researchers believe there is a greater distance between “somewhat likely” and “very likely” than “somewhat likely” and “unlikely”
<ul>
<li>See Cumulative Link Models (CLM) &gt;&gt; Structured Thresholds</li>
</ul></li>
</ul></li>
<li>Explanatory:
<ul>
<li>“pared” - parent’s education (0/1),&nbsp; graduate school or not</li>
<li>“public” - public school or not (i.e.&nbsp;private) (0/1)</li>
<li>“gpa” - numeric</li>
</ul></li>
<li>model<img src="./_resources/Regression,_Ordinal.resources/Screenshot (1142).png" class="img-fluid">
<ul>
<li>equation shows the thresholds (aka cutpoints) as intercepts and the minus sign propugated through the rest of the regression equation</li>
</ul></li>
<li>Add p-values to the summary table</li>
</ul>
<pre><code>## store table
(ctable &lt;- coef(summary(m)))
## calculate and store p values
p &lt;- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
## combined table
(ctable &lt;- cbind(ctable, "p value" = p))</code></pre>
<ul>
<li>CIs:
<ul>
<li>profile CIs: <code>confint(m)</code></li>
<li>Assuming normality: <code>confint.default(m)</code></li>
</ul></li>
<li>Interpretation:
<ul>
<li>In ordered log odds (aka ordered logits)
<ul>
<li>pared: “for a one unit increase in”pared” (i.e., going from 0 to 1), we expect a 1.05 increase in the expected value of “apply” on the log odds scale, given all of the other variables in the model are held constant.”</li>
<li>gpa: “for one unit increase in”gpa”, we would expect a 0.62 increase in the expected value of “apply” in the log odds scale, given that all of the other variables in the model are held constant</li>
</ul></li>
<li>In odds ratios (aka proportional odds ratios): (w/CIs <code>exp(cbind(OR = coef(m), ci = confint(m))</code>
<ul>
<li>This is a proportional odds model so the effect size is the same at all levels of the response variable</li>
<li>pared:
<ul>
<li>“For students whose parents did have a grad degree, the odds of being more likely (i.e., <em>very</em> or <em>somewhat likely</em> versus <em>unlikely</em>) to apply is 2.85 times that of students whose parents did NOT have a grad degree, holding constant all other variables.”</li>
<li>“For students whose parents did have a grad degress, the odds of being less likely to apply (i.e., <em>unlikely</em> versus <em>somewhat</em> or <em>very likely</em>) is 2.85 times that of students whose parents did NOT have a grad degree, holding constant all other variables.”</li>
</ul></li>
<li>public
<ul>
<li>For students in public school, the odds of being more likely&nbsp;(i.e., <em>very</em> or <em>somewhat</em> <em>likely</em> versus <em>unlikely</em>) to apply is 5.71% lower [i.e., (1 -0.943) x 100%] than private school students, holding constant all other variables.
<ul>
<li>For students in private school, the odds of being more likely to apply is 1.06 times [i.e., 1/0.943] that of public school students, holding constant all other variables (positive odds ratio).</li>
</ul></li>
<li>For students in private school, the odds of being less likely to apply&nbsp;(i.e., <em>unlikely</em> versus <em>somewhat</em> or <em>very likely</em>) is 5.71% lower than public school students, holding constant all other variables.
<ul>
<li>For students in public school, the odds of being&nbsp;less likely to apply is 1.06 times that of private school students, holding constant all other variables (positive odds ratio).</li>
</ul></li>
</ul></li>
<li>gpa
<ul>
<li>For every one unit increase in student’s GPA the odds of being more likely to apply (<em>very</em> or <em>somewhat likely</em> versus <em>unlikely</em>) is multiplied 1.85 times (i.e., increases 85%), holding constant all other variables.</li>
<li>For every one unit decrease in student’s GPA the odds of being less likely to apply (<em>unlikely</em> versus <em>somewhat</em> or <em>very likely</em>) is multiplied 1.85 times, holding constant all other variables.</li>
</ul></li>
</ul></li>
<li>Predictions: <code>predict(m, data = newdat, type = "probs")</code></li>
<li>Plot Predictions<img src="./_resources/Regression,_Ordinal.resources/image.2.png" class="img-fluid"></li>
</ul></li>
</ul>
<pre><code>newdat &lt;- cbind(newdat, predict(m, newdat, type = "probs"))
lnewdat &lt;- melt(newdat, id.vars = c("pared", "public", "gpa"),
&nbsp; variable.name = "Level", value.name="Probability")
ggplot(lnewdat, aes(x = gpa, y = Probability, colour = Level)) +
&nbsp; geom_line() + facet_grid(pared ~ public, labeller="label_both")</code></pre>
<p>Partial Proportional Odds (PPO)</p>
<ul>
<li>βs are allowed to vary with j (ordinal outcome levels) or equivalently, the threshold parameters {θj} are allowed to depend on regression variables.</li>
<li>Two sets of thresholds are applied at conditions with and without an explanatory variable</li>
<li><span class="ribbon-highlight">Example</span>: <span style="color: #990000">{ordinal}</span>, PPO <em>for “contact”</em></li>
</ul>
<pre><code>fm.nom &lt;- clm(rating ~ temp, nominal = ~ contact, data = wine)
summary(fm.nom)

link threshold nobs logLik&nbsp; AIC&nbsp; &nbsp; niter&nbsp; max.grad&nbsp; cond.H
logit flexible 72&nbsp; -86.21&nbsp; 190.42&nbsp; 6(0)&nbsp; 1.64e-10&nbsp; 4.8e+01

&nbsp; &nbsp; &nbsp; &nbsp; Estimate&nbsp; Std.Error&nbsp; z.value&nbsp; Pr(&gt;|z|)
tempwarm 2.519&nbsp; &nbsp; 0.535&nbsp; &nbsp; &nbsp; 4.708&nbsp; &nbsp; 2.5e-06 ***

Threshold coefficients:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate Std.Error&nbsp; z.value
1|2.(Intercept) -1.3230&nbsp; 0.5623&nbsp; &nbsp; -2.353
2|3.(Intercept)&nbsp; 1.2464&nbsp; 0.4748&nbsp; &nbsp; 2.625
3|4.(Intercept)&nbsp; 3.5500&nbsp; 0.6560&nbsp; &nbsp; 5.411
4|5.(Intercept)&nbsp; 4.6602&nbsp; 0.8604&nbsp; &nbsp; 5.416
1|2.contactyes&nbsp; -1.6151&nbsp; 1.1618&nbsp; &nbsp; -1.390
2|3.contactyes&nbsp; -1.5116&nbsp; 0.5906&nbsp; &nbsp; -2.559
3|4.contactyes&nbsp; -1.6748&nbsp; 0.6488&nbsp; &nbsp; -2.581
4|5.contactyes&nbsp; -1.0506&nbsp; 0.8965&nbsp; &nbsp; -1.172</code></pre>
<ul>
<li>model: logit(P(Yi ≤ j)) = θj + β˜j (contacti) − β(tempi)</li>
<li>Two sets of thresholds are applied at conditions with (yes) and without (no) “contact”</li>
<li>Response variable should be an ordered factor class
<ul>
<li>In this example, both explanatory variables were factor variables.</li>
</ul></li>
<li>It is not possible to estimate both β2(contacti) and β˜j(contacti) in the same model. Consequently variables that appear in “nominal” cannot enter in the formula as well</li>
<li>Results
<ul>
<li>βˆ(warm − cold) = 2.52
<ul>
<li>The reference level is cold, and this is the effect of moving from cold to warm</li>
</ul></li>
<li>{ ˆθj} = {−1.32, 1.25, 3.55, 4.66}</li>
<li>{βˆ˜j (yes − no){style=‘color: #990000’}<span style="color: #990000">}</span> = {−1.62, − 1.51, − 1.67, − 1.05}</li>
</ul></li>
<li>The odds ratio of bitterness being rated in category j or above (OR(Y ≥ j)) now vary with j:
<ul>
<li>ORs = {exp(−β ˆ˜ j (yes− no)){style=‘color: #990000’}<span style="color: #990000">}</span> = exp{-(-1.6151), -(-1.5116), -(-1.6748), -(-1.0506){style=‘color: #990000’}<span style="color: #990000">}</span> = {5.03, 4.53, 5.34, 2.86}</li>
<li>Me: The odds of the rating being greater or equal to 2 are 4.53 times greater when contact = yes than when contact = no.</li>
</ul></li>
<li><span class="ribbon-highlight">Example</span>: <span style="color: #990000">{ordinal}</span>, Test the PO assumption for 1 variable w/LR Test</li>
</ul>
<pre><code>anova(fm1, fm.nom)

&nbsp; &nbsp; &nbsp; formula:&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; nominal: link: threshold:
fm1&nbsp; &nbsp; rating ~ temp + contact&nbsp; ~1&nbsp; &nbsp; &nbsp; logit flexible
fm.nom rating ~ temp&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ~contact logit flexible

&nbsp; &nbsp; &nbsp; no.par AIC&nbsp; &nbsp; logLik&nbsp; LR.stat df Pr(&gt;Chisq)
fm1&nbsp; &nbsp; 6&nbsp; &nbsp; &nbsp; 184.98 -86.492
fm.nom 9&nbsp; &nbsp; &nbsp; 190.42 -86.209&nbsp; 0.5667&nbsp; 3&nbsp; 0.904</code></pre>
<ul>
<li><p>“fm1” model from example in Proportional Odds section, but the “formula” column in the summary tells you what variables are in it.</p></li>
<li><p>There is only little difference in the log-likelihoods of the two models and the test is insignificant (pval &lt; 0.05). Thus there is no evidence that the proportional odds assumption is violated for contact.</p></li>
<li><p><span class="ribbon-highlight">Example</span>: <span style="color: #990000">{ordinal}</span>, Test the PO assumption for <em>all</em> variables w/LR Test</p></li>
</ul>
<pre><code>nominal_test(fm1)

&nbsp; &nbsp; &nbsp; &nbsp; Df&nbsp; logLik&nbsp; AIC&nbsp; &nbsp; LRT&nbsp; &nbsp; Pr(&gt;Chi)
&lt;none&gt;&nbsp; &nbsp; -86.492&nbsp; 184.98
temp&nbsp; &nbsp; 3&nbsp; -84.904&nbsp; 187.81&nbsp; 3.1750&nbsp; 0.3654
contact 3&nbsp; -86.209&nbsp; 190.42&nbsp; 0.5667&nbsp; 0.9040</code></pre>
<ul>
<li><input type="checkbox">Behavior of this function is similar to the <code>anova</code> example above except the action is taken with every variable in the formula
<ul>
<li>If any variables are in the “scale” argument, they are also tested.</li>
</ul></li>
<li>Note that “contact” has the same LRT, pval as the previous example</li>
<li>No pvals &lt; 0.05, therefore no violations of the PO assumption for any variable.</li>
</ul>
<p>Scale Effects</p>
<ul>
<li>An alternative to nominal effects (partial proportional odds) when nonproportional odds structures are encountered in the data.
<ul>
<li>Using scale effects is often a better approach, and it uses fewer parameters which often lead to more sensitive tests than nominal effects</li>
</ul></li>
<li>Something about allowing the scale parameter of the latent variable distribution to depend on explanatory variables.
<ul>
<li>latent distribution is determined by the choice of link function</li>
</ul></li>
<li><span class="ribbon-highlight">Example</span>: <span style="color: #990000">{ordinal}</span>, allow scale to vary according to a variable</li>
</ul>
<pre><code>fm.sca &lt;- clm(rating ~ temp + contact, scale = ~ temp, data = wine)
summary(fm.sca)

link threshold nobs logLik AIC niter max.grad cond.H
logit flexible 72 -86.44 186.88 8(0) 5.25e-09 1.0e+02

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Estimate&nbsp; Std.Error z.value&nbsp; Pr(&gt;|z|)
tempwarm&nbsp; 2.6294&nbsp; &nbsp; 0.6860&nbsp; &nbsp; 3.833&nbsp; &nbsp; 0.000127 ***
contactyes 1.5878&nbsp; &nbsp; 0.5301&nbsp; &nbsp; 2.995&nbsp; &nbsp; 0.002743 **

log-scale coefficients:
&nbsp; &nbsp; &nbsp; &nbsp; Estimate&nbsp; Std.Error z.value&nbsp; Pr(&gt;|z|)
tempwarm 0.09536&nbsp; 0.29414&nbsp; 0.324&nbsp; &nbsp; 0.746

Threshold coefficients:
&nbsp; &nbsp; Estimate Std.Error&nbsp; z value
1|2 -1.3520&nbsp; 0.5223&nbsp; &nbsp; -2.588
2|3&nbsp; 1.2730&nbsp; 0.4533&nbsp; &nbsp; 2.808
3|4&nbsp; 3.6170&nbsp; 0.7774&nbsp; &nbsp; 4.653
4|5&nbsp; 5.2982&nbsp; 1.2027&nbsp; &nbsp; 4.405</code></pre>
<ul>
<li>model<img src="./_resources/Regression,_Ordinal.resources/Screenshot (1138).png" class="img-fluid">
<ul>
<li>Scale parameter of the latent variable distribution varies by “temp”
<ul>
<li>The scale term in the denominator. See Cumulative Link Models (CLM) &gt;&gt; model for more details on this term</li>
</ul></li>
<li>Location parameter of the latent distribution is allowed to depend on both “temp” and “contact”
<ul>
<li>The location expression is the numerator</li>
</ul></li>
</ul></li>
<li>response variable should be an ordered factor class
<ul>
<li>In this example, both explanatory variables were factor variables.</li>
</ul></li>
<li>Results
<ul>
<li>Little to no idea what any of this practically means</li>
<li>The location of the latent distribution is shifted 2.63<strong>σ (scale units)</strong> when temperature is warm as compared to cold conditions and 1.59σ when there’s presence (yes) of contact as compared to absence (no) of contact. (reference levels: temp: cold, contact: no)</li>
<li>The scale of the latent distribution is σ at cold conditions but σ ∗ exp(ζ(warm−cold)) = σ ⨯ exp(0.095) = 1.10σ , i.e., 10% higher, at warm conditions.</li>
<li>The p value for the scale effect in the summary output shows that the ratio of scales is not significantly different from 1 (or equivalently that the difference on the log-scale is not different from 0).</li>
</ul></li>
<li><span class="ribbon-highlight">Example</span>: Detect scale effects of variables</li>
</ul>
<pre><code>scale_test(fm1)

&nbsp; &nbsp; &nbsp; &nbsp; Df logLik&nbsp; AIC&nbsp; &nbsp; LRT&nbsp; &nbsp; Pr(&gt;Chi)
&lt;none&gt;&nbsp; &nbsp; -86.492&nbsp; 184.98
temp&nbsp; &nbsp; 1&nbsp; -86.439&nbsp; 186.88 0.10492 0.7460
contact 1&nbsp; -86.355&nbsp; 186.71 0.27330 0.6011</code></pre>
<ul>
<li>“fm1” comes from example in Proportional Odds (PO) section</li>
<li>Function has similar behavior to <code>nominal_test</code> (see example in Partial Proportional Odds (PPO) section)</li>
<li>No pvals &lt; 0.05, therefore no evidence of scale effects for any variable.</li>
</ul>
<p>Generalized Ordinal Regression</p>
<ul>
<li></li>
</ul>



</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../qmd/regression-nonlinear.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">159</span>&nbsp; <span class="chapter-title">Regression, Nonlinear</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../qmd/regression-other.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">161</span>&nbsp; <span class="chapter-title">Regression, Other</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>