# Spreadsheets {#sec-spdsht .unnumbered}

## Misc {#sec-spdsht-misc .unnumbered}

-   Some Excel files are binaries and in order to use `download.file`, you must set [mode = "wb"]{.arg-text}

    ``` r
    download.file(url, 
                  destfile = glue("{rprojroot::find_rstudio_root_file()}/data/cases-age.xlsx"), 
                  mode = "wb")
    ```

-   Industry [studies](https://www.igi-global.com/article/know-spreadsheet-errors/55750) show that 90 percent of spreadsheets containing more than 150 rows have at least one major mistake.

## Catastrophes {#sec-spdsht-cats .unnumbered}

-   Releasing confidential information
    -   Irish police accidently handed out officers private information when sharing sheets with statistics due to a freedom of information request. ([link](https://arstechnica.com/science/2024/01/we-keep-making-the-same-mistakes-with-spreadsheets-despite-bad-consequences/?utm_brand=arstechnica&utm_social-type=owned&utm_source=mastodon&utm_medium=social))
-   Errors when combining sheets
    -   Wales dismissed anaesthesiologists after mistakenly deeming them "unappointable." Spreadsheets from different areas lacked standardization in formatting, naming conventions, and overall structure. To make matters worse, data was manually copied and pasted between various spreadsheets, a time-consuming and error-prone process. ([link](https://arstechnica.com/science/2024/01/we-keep-making-the-same-mistakes-with-spreadsheets-despite-bad-consequences/?utm_brand=arstechnica&utm_social-type=owned&utm_source=mastodon&utm_medium=social))
    -   When consolidating assets from different spreadsheets, the spreadsheet data was not “cleaned” and formatted properly. The Icelandic bank’s shares were subsequently undervalued by as much as £16 million. ([link](https://arstechnica.com/science/2024/01/we-keep-making-the-same-mistakes-with-spreadsheets-despite-bad-consequences/?utm_brand=arstechnica&utm_social-type=owned&utm_source=mastodon&utm_medium=social))
-   Data entry errors
    -   Cryto.com accidentally transferred \$10.5 million instead of \$100 into the account of an Australian customer due to an incorrect number being entered on a spreadsheet. ([link](https://arstechnica.com/science/2024/01/we-keep-making-the-same-mistakes-with-spreadsheets-despite-bad-consequences/?utm_brand=arstechnica&utm_social-type=owned&utm_source=mastodon&utm_medium=social))

## Best Practices {#sec-spdsht-bprac .unnumbered}

-   Notes from [Data organization in spreadsheets](https://peerj.com/preprints/3183/)
    -   Be consistent
    -   Write dates like YYYY-MM-DD
    -   Don't leave any cells empty
    -   Put just one thing in a cell
    -   Organize the data as a single rectangle (with subjects as rows and variables as columns, and with a single header row)
    -   Create a data dictionary
    -   Don't include calculations in the raw data files
    -   Don't use font color or highlighting as data
    -   Choose good names for things
    -   Make backups
    -   Use data validation to avoid data entry errors
    -   Save the data in plain text files.
