# Teaching {#sec-teach .unnumbered}

## Misc {#sec-teach-misc .unnumbered}

-   Also see
    -   Bkmks:
        -   Science and Mathematics \>\> Education
        -   Data Science \>\> Modeling \>\> Reporting, Sharing, Publishing \>\> Concepts \>\> Teaching
-   tl;dr for writing article or preparing a talk Audience
    -   Know their level of knowledge
    -   Why they should want to know this
    -   How does that reason get them closer to their goal
    -   (Maybe those last 2 are the same?)
-   Books
    -   Teaching what you dont know
    -   The discussion book - 50 great ways to get people talking
-   On average, 7 $\pm$ 2 things can be kept in short term memory
-   Teach chunks of your concept map. Each new chunk should be adjacent to the previous chunk.
-   Sacrifice truth for clarity to give learner actionable concept
-   Explaining an unclear concept from the homework or reading ([Gelman](https://statmodeling.stat.columbia.edu/2023/09/26/how-to-teach-certain-tricky-things-such-as-the-difference-between-standard-deviation-and-standard-error/))
    -   Better to work through an example than to try to clarify a definition or restate it, etc.
    -   Then, ask the students to get into pairs and explain to each other the meaning of each of the concepts in question
    -   Then, if students want to ask questions on the concept, we could do it in the context of this example that they've just been talking about. We could also loop back to their homework assignment.

## Steps {#sec-teach-steps .unnumbered}

-   State goalpost
-   Split goalpost into concepts
-   Connect concepts to form map
-   If more than 7 $\pm$ 2 concepts, then group in chunks
-   The next chunk of concepts you present should be adjacent to previous chunk
-   Summarize

## Characterize the Audience {#sec-teach-chtaud .unnumbered}

-   General background
-   relevant experience
-   perceived needs
-   special consideration

## Mental Model {#sec-teach-mentmod .unnumbered}

-   Draw a concept map. Concepts and connections between them
-   Examples: Venn diagrams, flow charts

## Assessments {#sec-teach-ass .unnumbered}

-   Summative
    -   Summary of what you want to be learned. Goalpost
    -   Guide to creating formative assessments by working backwards from the endpoint
-   Formative
    -   Is the learning working? 
    -   Types of mistakes or questions are clues to the types of misconceptions that learners are thinking and what you should say next.
    -   Diagnosing misconceptions by checking in every few minutes with questions. Think about what those answers might be and they mean.
    -   Questions should have diagnostic power
    -   Tells you if its okay to move on to the next lesson.

## Forces for Learning {#sec-teach-forces .unnumbered}

-   [Positive]{.underline}
    -   **Intrinsic Motivation** - Learner isnt being made to learn something, theyre choosing to learn
    -   **Utility** - Moves them towards their goals
    -   **Community** - Not alone in learning, connection to peers, more comfortable about not knowing someting
-   [Negative]{.underline}
    -   **Unpredictability** - "What i do doesnt seem to affect the outcome", learned helplessness
    -   **Unfairness** - Teacher Bias
    -   **Indifference** - Feeling that the teacher doesnt care about your problem
