# Diagrams {#sec-vis-dia .unnumbered}

## Misc {#sec-vis-dia-misc .unnumbered}

-   Packages
    -   [{]{style="color: #990000"}[ggdiagram](https://wjschne.github.io/ggdiagram/){style="color: #990000"}[}]{style="color: #990000"} ([diagram vignette](https://wjschne.github.io/ggdiagram/articles/causalpaths.html)) - Object-oriented approach to making diagrams and plots the results using ggplot2.
-   Tools
    -   [Draw.io](https://www.drawio.com/) - Has a [desktop app](https://github.com/jgraph/drawio-desktop/releases) and a VS Code [extension](https://marketplace.visualstudio.com/items?itemName=hediet.vscode-drawio). Seems to be the one that Dancho uses.

## Mermaid {#sec-vis-dia-merm .unnumbered}

### Misc {#sec-vis-dia-merm-misc .unnumbered}

-   Resources
    -   [Docs](https://mermaid.js.org/intro/), [Theming](https://mermaid.js.org/config/theming.html), [Cheatsheet](https://jojozhuang.github.io/tutorial/mermaid-cheat-sheet/), [Quarto](https://quarto.org/docs/authoring/diagrams.html#mermaid)
-   Currently mermaid code chunks cannot be placed below bullets

### Examples {#sec-vis-dia-merm-ex .unnumbered}

-   Flowchart Top-Bottom ([Source](https://carpentries.github.io/workbench-dev/remote/intro.html#sec-philosophy), [Code](https://github.com/carpentries/workbench-dev/blob/8941127f10b24e96e05df21b308a150cb0514df2/remote/intro.qmd#L22))

```{mermaid}
%%| echo: true

%% Top-Bottom direction
flowchart TB
    %% Classes with styling
    classDef default color:#383838,fill:#FFF7F1,stroke-width:1px
    classDef external color:#383838,fill:#E6EEF8,stroke-width:1px
    classDef normal color:#081457,fill:#E3E6FC,stroke-width:1px
    classDef local fill:#FFC700,stroke:#333,stroke-width:1px
    classDef remote fill:#D2BDF2,stroke:#201434,stroke-width:1px
    classDef notouch fill:#F99697,stroke:#A4050E,stroke-width:1px

    %% Aliases, classes, and shapes applied to nodes
    GH[("@main")]:::remote
    MDOUT[("@md-outputs")]:::notouch
    PAGES[("@gh-pages")]:::notouch
    DEPLOY(["ci_deploy()"]):::external
    CIBUILDMD(["ci_build_markdown()"]):::external
    CIBUILDSITE(["ci_build_site()"]):::external

    %% Box around subset of nodes
    %% Aliases, classes, and shapes applied
    subgraph virtual machine
    REPO["[repo]"]:::local
    BUILT["[repo]/site/built"]:::local
    SITE["[repo]/site/docs"]:::local
    VLESS("validate_lesson()"):::normal
    BUILDMD(["build_markdown()"]):::normal
    BUILDSITE(["build_site()"]):::normal
    end

    %% Arrows and connection types
    GH ---> REPO
    REPO -.- VLESS
    DEPLOY ---> VLESS
    DEPLOY ---> CIBUILDMD
    DEPLOY ---> CIBUILDSITE
    VLESS -.- BUILDMD
    CIBUILDMD ---> MDOUT
    MDOUT <-.-> BUILT
    CIBUILDMD ---> BUILDMD
    CIBUILDSITE ---> PAGES
    PAGES <-.-> SITE
    CIBUILDSITE ---> BUILDSITE
    BUILT -.- BUILDSITE
    VLESS -.- BUILDSITE
    BUILDMD --> BUILT
    BUILDSITE --> SITE
```

-   Flowchart Left-Right ([Source](https://carpentries.github.io/workbench-dev/remote/intro.html#workflows), [Code](https://github.com/carpentries/workbench-dev/blob/8941127f10b24e96e05df21b308a150cb0514df2/remote/intro.qmd#L165))

```{mermaid}
%%| echo: true

%% Left-Right direction
flowchart LR
    %% Classes with styling
    classDef default color:#383838,fill:#FFF7F1,stroke-width:1px
    classDef external color:#383838,fill:#E6EEF8,stroke-width:1px
    classDef normal color:#081457,fill:#E3E6FC,stroke-width:1px
    classDef local fill:#FFC700,stroke:#333,stroke-width:1px
    classDef remote fill:#D2BDF2,stroke:#201434,stroke-width:1px
    classDef notouch fill:#F99697,stroke:#A4050E,stroke-width:1px

    %% Classes and shapes applied to nodes
    WEEK[\"CRON weekly"\]:::remote
    MONTH[\"CRON monthly"\]:::remote

    %% Boxes around subsets of nodes
    %% Aliases, classes, and shapes applied
    subgraph MAIN WORKFLOW
    push[\"push to main"\]:::remote
    md-outputs[("md-outputs")]:::local
    gh-pages[("gh-pages")]:::local
    sandpaper-main.yaml:::normal
    end

    subgraph "UPDATES (requires SANDPAPER_WORKFLOW token)"
    update-cache.yaml:::normal
    update-workflows.yaml:::normal
    update-cache[("update/packages")]:::notouch
    update-workflows[("update/workflows")]:::notouch
    PR[/"pull request"/]:::remote
    end

    %% Arrows and connection types
    push --> sandpaper-main.yaml
    WEEK --> sandpaper-main.yaml
    sandpaper-main.yaml -.->|"pushes to"| md-outputs
    sandpaper-main.yaml -.->|"pushes to"| gh-pages
    WEEK --> update-cache.yaml
    MONTH --> update-workflows.yaml
    update-cache.yaml -.->|"pushes to"| update-cache
    update-workflows.yaml -.->|"pushes to"| update-workflows
    update-cache.yaml -.->|"creates"| PR
    update-workflows.yaml -.->|"creates"| PR
```

-   Gitgraph ([Source](https://carpentries.github.io/workbench-dev/hotfixes.html), [Code](https://github.com/carpentries/workbench-dev/blob/8941127f10b24e96e05df21b308a150cb0514df2/hotfixes.qmd#L18))

```{mermaid}
%%| echo: true

gitGraph
    commit id: "abcd"
    commit id: "efgh" tag: "0.14.0"
    branch feature1
    branch feature2
    checkout main
    checkout feature1
    commit id: "ijkl"
    commit id: "mnop"
    checkout main
    merge feature1 tag: "customTag"
    checkout feature2
    commit id: "qrst"
    commit id: "uvwx"
```

-   There's an issue currently with adding id and type options to merge.

## D2

-   Resources
    -   Quarto [extension](https://github.com/data-intuitive/quarto-d2)
    -   [Docs](https://d2lang.com/)
    -   SVG Sofware Architecture [Icons](https://icons.terrastruct.com/)
-   Packages
    -   [{]{style="color: #990000"}[d2r](https://elipousson.github.io/d2r/){style="color: #990000"}[}]{style="color: #990000"} - Supports the creation, reading, writing, and rendering of D2 diagrams using R
