# Web Design {#sec-webdes .unnumbered}

## Misc {#sec-webdes-misc .unnumbered}

-   Websites should be under 14kb ([article](https://endtimes.dev/why-your-website-should-be-under-14kb-in-size/))
    -   Most web servers TCP slow start algorithm starts by sending 10 TCP packets which works out to 14kb
-   404 pages
    -   Guidelines
        -   *be brief:* the message on the 404 page should be straightforward and easy to understand, informing the user that the page they were trying to access is not available.
        -   *be contrite*: the tone of the 404 page should be friendly and apologetic, acknowledging the user's inconvenience and expressing empathy.
        -   *be helpful*: provide links to other areas of the website or a search box that can help users find what they're looking for quickly and easily.
        -   *be informative*: include contact information, such as a feedback form, social media account, or email address to give users an alternative way to reach out to you for assistance.
        -   *be you*: incorporate your brand's visual identity, including logos and colors, to help reinforce brand recognition and create a cohesive user experience.
    -   Examples
        -   [404 Page SVG Animations That Maximize Visitor Retention](https://www.svgator.com/blog/404-page-svg-animations/)
        -   [21 Stunning 404 Pages to Convert Lost Visitors 2023](https://optinmonster.com/best-404-page-examples/)
        -   [guinslym/awesome-404: A curated list of awesome 404 web pages](https://github.com/guinslym/awesome-404) [greynoise's '404' equivalent](https://viz.greynoise.io/ip/19.5.4.1) and [hrbmstr's](https://rud.is/404).
