project:
  type: book
  
book:
  title: "Data Science"
  author: "Eric Book"
  date: "5/18/2023"
  favicon: images/ds-favicon-32.png
  reader-mode: true
  repo-url: https://github.com/ercbk/Data-Science-Notebook
  sidebar: 
    collapse-level: 1
    background: "#fffaf0"
    foreground: "#1E4477"
    tools: 
      - icon: house-fill
        href: https://ericbook.netlify.app/
  chapters:
    - index.qmd
    - part: "Algorithms"
      chapters: 
        - qmd/algorithms-learn-to-rank.qmd
        - qmd/algorithms-marketing.qmd
        - qmd/algorithms-ml.qmd
        - qmd/algorithms-product.qmd
        - qmd/algorithms-recommendation.qmd
    - qmd/anomaly-detection.qmd
    - part: "Apache"
      chapters:
        - qmd/apache-arrow.qmd
        - qmd/apache-spark.qmd
    - qmd/apis.qmd
    - part: "Association"
      chapters: 
        - qmd/association-copulas.qmd
        - qmd/association-general.qmd
        - qmd/association-time-series.qmd
    - qmd/aws.qmd
    - qmd/base-r.qmd
    - part: "Bayes"
      chapters: 
        - qmd/bayes-priors.qmd
        - qmd/bayes-reporting.qmd
        - qmd/bayes-troubleshooting-hmc.qmd
        - qmd/bayes-workflow.qmd
    - qmd/big-data.qmd
    - qmd/business-plots.qmd
    - qmd/causal-inference.qmd
    - qmd/classification.qmd
    - qmd/cli.qmd
    - qmd/cloud-services.qmd
    - part: "Clustering"
      chapters: 
        - qmd/clustering-time-series.qmd
        - qmd/clustering-general.qmd
    - part: "Code"
      chapters: 
        - qmd/code-debug.qmd
        - qmd/code-optimization.qmd
        - qmd/code-snippets.qmd
        - qmd/code-style-guide.qmd
        - qmd/code-testing.qmd
    - qmd/confidence-and-prediction-intervals.qmd
    - qmd/cross-validation.qmd
    - part: "CSS"
      chapters: 
        - qmd/css-general.qmd
        - qmd/css-recipes.qmd
    - qmd/data.table.qmd
    - part: "Databases"
      chapters: 
        - qmd/db-dbt.qmd
        - qmd/db-duckdb.qmd
        - qmd/db-engineering.qmd
        - qmd/db-feature-stores.qmd
        - qmd/db-lakes.qmd
        - qmd/db-other.qmd
        - qmd/db-postgres.qmd
        - qmd/db-relational.qmd
        - qmd/db-warehouses.qmd
    - qmd/decision-intelligence.qmd
    - part: "Diagnostics"
      chapters: 
        - qmd/diagnostics-bayes.qmd
        - qmd/diagnostics-classification.qmd
        - qmd/diagnostics-clustering.qmd
        - qmd/diagnostics-cv.qmd
        - qmd/diagnostics-dl.qmd
        - qmd/diagnostics-forecasting.qmd
        - qmd/diagnostics-glm.qmd
        - qmd/diagnostics-mixed-effects.qmd
        - qmd/diagnostics-model-agnostic.qmd
        - qmd/diagnostics-nlp.qmd
        - qmd/diagnostics-probabilistic.qmd
        - qmd/diagnostics-regression.qmd
    - qmd/distributions.qmd
    - part: "Deep Learning"
      chapters: 
        - qmd/dl-audio.qmd
        - qmd/dl-general.qmd
        - qmd/dl-graph.qmd
        - qmd/dl-image.qmd
        - qmd/dl-tabular.qmd
        - qmd/dl-training.qmd
    - part: "Docker"
      chapters: 
        - qmd/docker-aws.qmd
        - qmd/docker-fundamentals.qmd
        - qmd/docker-misc.qmd
    - part: "Econometrics"
      chapters: 
        - qmd/econometrics-discrete-choice-models.qmd
        - qmd/econometrics-fixed-effects.qmd
        - qmd/econometrics-general.qmd
        - qmd/econometrics-mixed-effects-bayes.qmd
        - qmd/econometrics-mixed-effects-frequentist.qmd
    - part: "EDA"
      chapters: 
        - qmd/eda-geospatial.qmd
        - qmd/eda-general.qmd
        - qmd/eda-multilevel-longitudinal.qmd
        - qmd/eda-text.qmd
        - qmd/eda-time-series.qmd
    - part: "Experiments"
      chapters: 
        - qmd/experiments-a_b-testing.qmd
        - qmd/experiments-analysis.qmd
        - qmd/experiments-design.qmd
        - qmd/experiments-general.qmd
        - qmd/experiments-rct.qmd
        - qmd/experiments-stepped-wedge-cluster-design.qmd
    - qmd/extreme-value-theory-(evt).qmd
    - part: "Feature Engineering"
      chapters: 
        - qmd/feature-engineering-embeddings.qmd
        - qmd/feature-engineering-general.qmd
        - qmd/feature-engineering-geospatial.qmd
        - qmd/feature-engineering-time-series.qmd
        - qmd/feature-engineering-splines.qmd
        - qmd/feature-engineering-tokenization.qmd
    - qmd/feature-reduction.qmd
    - qmd/feature-selection.qmd
    - part: "Forecasting"
      chapters: 
        - qmd/forecasting-decomposition.qmd
        - qmd/forecasting-dl.qmd
        - qmd/forecasting-ensembling.qmd
        - qmd/forecasting-functional.qmd
        - qmd/forecasting-hierarchical_grouped.qmd
        - qmd/forecasting-ml.qmd
        - qmd/forecasting-multivariate.qmd
        - qmd/forecasting-nonlinear.qmd
        - qmd/forecasting-statistical.qmd
    - qmd/generalized-additive-models-(gam).qmd
    - part: "Geospatial"
      chapters: 
        - qmd/geospatial-analysis.qmd
        - qmd/geospatial-general.qmd
        - qmd/geospatial-image-classification.qmd
        - qmd/geospatial-processing.qmd
    - part: "Git"
      chapters: 
        - qmd/git-general.qmd
        - qmd/git-github-actions.qmd
    - qmd/glossary-ds-terms.qmd
    - qmd/gnu-make.qmd
    - part: "Google"
      chapters: 
        - qmd/google-analytics-analysis.qmd
        - qmd/google-analytics-reports.qmd
        - qmd/google-bigquery.qmd
    - qmd/gtable-package.qmd
    - qmd/h2o-automl.qmd
    - qmd/html.qmd
    - qmd/information-theory.qmd
    - qmd/inkscape.qmd
    - part: "Job"
      chapters: 
        - qmd/job-management-leadership.qmd
        - qmd/job-on-the-job.qmd
        - qmd/job-organizational-and-team-development.qmd
        - qmd/job-reports.qmd
        - qmd/job-search.qmd
    - qmd/js.qmd
    - qmd/json.qmd
    - qmd/kubernetes.qmd
    - qmd/latex.qmd 
    - qmd/loss-functions.qmd
    - part: "Mathematics"
      chapters: 
        - qmd/mathematics-linear-algebra.qmd
        - qmd/mathematics-glossary.qmd
        - qmd/mathematics-notation.qmd
        - qmd/mathematics-probability.qmd
        - qmd/mathematics-statistics.qmd
    - qmd/misc.qmd
    - qmd/missingness.qmd
    - qmd/mlops.qmd
    - part: "Model Building"
      chapters: 
        - qmd/model-building-brms.qmd
        - qmd/model-building-concepts.qmd
        - qmd/model-building-ensembling.qmd
        - qmd/model-building-modeltime.qmd
        - qmd/model-building-rstanarm.qmd
        - qmd/model-building-sklearn.qmd
        - qmd/model-building-tidymodels.qmd
    - qmd/network-analysis.qmd
    - part: "NLP"
      chapters: 
        - qmd/nlp-fine-tuning.qmd
        - qmd/nlp-general.qmd
        - qmd/nlp-llms.qmd
        - qmd/nlp-prompt-engineering.qmd
        - qmd/nlp-sentiment.qmd
        - qmd/nlp-summarization-extraction.qmd
        - qmd/nlp-topic.qmd
        - qmd/nlp-transformers.qmd
    - qmd/optimization-equation-systems.qmd
    - qmd/outliers.qmd
    - qmd/package-development.qmd
    - part: "Post-Hoc Analysis"
      chapters: 
        - qmd/post-hoc-analysis-anova.qmd
        - qmd/post-hoc-analysis-emmeans.qmd
        - qmd/post-hoc-analysis-general.qmd
        - qmd/post-hoc-analysis-mixed-effects.qmd
    - qmd/privacy.qmd
    - part: "Production"
      chapters: 
        - qmd/production-data-validation.qmd
        - qmd/production-deployment.qmd
        - qmd/production-development.qmd
        - qmd/production-ml-monitoring.qmd
        - qmd/production-testing.qmd
        - qmd/production-tools.qmd
    - part: "Projects"
      chapters: 
        - qmd/project-development.qmd
        - qmd/project-management.qmd
        - qmd/project-planning.qmd
    - part: "Python"
      chapters: 
        - qmd/python-classes.qmd
        - qmd/python-general.qmd
        - qmd/python-jupyter.qmd
        - qmd/python-misc.qmd
        - qmd/python-numpy.qmd
        - qmd/python-pandas-recipes.qmd
        - qmd/python-pandas.qmd
        - qmd/python-reticulate.qmd
    - qmd/quarto-rmarkdown.qmd
    - part: "Regression"
      chapters: 
        - qmd/regression-discrete.qmd
        - qmd/regression-interactions.qmd
        - qmd/regression-linear.qmd
        - qmd/regression-logistic.qmd
        - qmd/regression-multinomial.qmd
        - qmd/regression-multivariate.qmd
        - qmd/regression-nonlinear.qmd
        - qmd/regression-ordinal.qmd
        - qmd/regression-other.qmd
        - qmd/regression-quantile.qmd
        - qmd/regression-regularized.qmd
        - qmd/regression-survival.qmd
    - qmd/renv.qmd
    - qmd/scraping.qmd
    - part: "Shiny"
      chapters: 
        - qmd/shiny-general.qmd
        - qmd/shiny-hosting.qmd
        - qmd/shiny-modules.qmd
        - qmd/shiny-production.qmd
        - qmd/shiny-python.qmd
        - qmd/shiny-ui.qmd
        - qmd/shiny-ui-examples.qmd
    - qmd/simulation-data.qmd
    - qmd/slack.qmd
    - qmd/spreadsheets.qmd
    - qmd/sql.qmd
    - qmd/stochastic-processes.qmd
    - part: "Surveys"
      chapters: 
        - qmd/surveys-analysis.qmd
        - qmd/surveys-census-data.qmd
        - qmd/surveys-design.qmd
        - qmd/surveys-sampling-methods.qmd
    - qmd/teaching.qmd
    - qmd/tidyeval.qmd
    - qmd/tuning.qmd
    - qmd/visualization.qmd
    - qmd/vs-code.qmd
    - qmd/web-design.qmd


format:
  html:
    toc-depth: 5
    theme: paper
    css: styles.css
    code-link: true
    backgroundcolor: "#fffaf0"
    fontcolor: "#404d59"
    mainfont: 'Lora'
    monofont: 'Fira Code Retina'
    linkcolor: '#0064B6FF'
    highlight-style: printing

editor: visual

execute:
    freeze: auto
