---
format:
  html: 
    css: index.css
---

# Preface {.unnumbered}

These notes were transferred from Evernote to Quarto, so some of notes may be difficult to read as the editing of the note format is still an ongoing process.

Notes without numbers in sidebar should be a good indicator of a note that I've finished formatting.

This notebook covers many aspects of data science: soft skills, technical skills, backend to frontend. The notebook is in an outline format, so some of the information may seem a bit fragmented. The bullets are bits of information that I've pulled from various articles, papers, books, etc.

Most of the code is written in R, but there is a substantial portion in Python. There are also sections devoted to SQL and Javascript.

Initially, I had no intent of publicly releasing these notes, so I haven't attributed all the authors of the content inside this notebook. If you see your work and want credit, please let me know.

This is a live document that's frequently updated.

Also, if you see any mistakes or have any questions, please open an issue at the github [repository](https://github.com/ercbk/Data-Science-Notebook).

Cover designed using Google Imagen 3
